#!/usr/bin/env python3
"""Read-only parity audit of recent MLB PA and F5 research packages."""
from __future__ import annotations
import hashlib,json,time
from pathlib import Path
import numpy as np,pandas as pd
from backend.mlb.scripts import run_mlb_pa_outcome_prediction_foundation_v1 as pa
ROOT=Path(__file__).resolve().parents[3];A=ROOT/'artifacts/analysis/model_development';OUT=A/'mlb_research_harness_parity_audit_v1/2026-08-12'
EXPS=['mlb_pa_outcome_prediction_foundation_v1','mlb_multi_season_talent_prior_pa_refinement_v1','mlb_component_specific_talent_prior_refinement_v1','mlb_hierarchical_player_talent_pa_model_v1','mlb_expected_quality_scoring_model_v1','mlb_f5_expected_quality_distribution_refinement_v1','mlb_f5_direct_ladder_probability_model_v1','mlb_pa_rate_f5_inning_simulation_v1']
SCRIPTS={e:ROOT/'backend/mlb/scripts'/('audit_'+e+'.py' if e=='x' else 'run_'+e+'.py') for e in EXPS};SCRIPTS['mlb_hierarchical_player_talent_pa_model_v1']=ROOT/'backend/mlb/scripts/run_mlb_hierarchical_player_talent_pa_model_v1.py'
PFILES={'PA_FOUNDATION':'mlb_pa_outcome_prediction_foundation_v1/2026-08-12/pa_population_manifest.csv','MULTI_PRIOR':'mlb_multi_season_talent_prior_pa_refinement_v1/2026-08-12/talent_prior_population_manifest.csv','COMPONENT':'mlb_component_specific_talent_prior_refinement_v1/2026-08-12/component_prior_population_manifest.csv'}
GFILES={'EXPECTED_QUALITY':'mlb_expected_quality_scoring_model_v1/2026-08-12/expected_quality_model_population.csv','DISTRIBUTION':'mlb_f5_expected_quality_distribution_refinement_v1/2026-08-12/f5_frozen_mean_predictions.csv','DIRECT_LADDER':'mlb_f5_direct_ladder_probability_model_v1/2026-08-12/direct_probability_population.csv','PA_SIMULATION':'mlb_pa_rate_f5_inning_simulation_v1/2026-08-12/pa_rate_simulation_population.csv'}
def sh(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def manifest(exp):return A/exp/'2026-08-12/reproducibility_hashes.sha256'
def hashes_ok(exp):
 m=manifest(exp)
 if not m.exists():return False
 for line in m.read_text().splitlines():
  h,n=line.split('  ',1);f=m.parent/n
  if not f.exists() or sh(f)!=h:return False
 return True
def main():
 OUT.mkdir(parents=True,exist_ok=True);contract=[]
 specs={
 'mlb_pa_outcome_prediction_foundation_v1':('PA manifest','game_pk+at_bat_number+batter_id+starter_id','2026-03-26..2026-07-27','38412/17067/13386','six-class terminal PA','Statcast strict-prior player state','median impute + standard scale','league constants','L2 multinomial C=.5',20260812,'log loss|multiclass Brier','reliever PA; games outside accepted spine','hard feature fallbacks'),
 'mlb_multi_season_talent_prior_pa_refinement_v1':('same PA manifest','same PA identity','same','same','same six-class','2024/25 + strict-prior 2026 reconstructed talent state','same frozen model preprocessing','feature-specific league constants','same L2 multinomial C=.5',20260812,'same + class/calibration','same','75 pseudo-count'),
 'mlb_component_specific_talent_prior_refinement_v1':('same PA manifest','same PA identity','same','same','same six-class','same prior state + component alternatives','same frozen model preprocessing','same','same L2 multinomial C=.5',20260812,'same + class/calibration','same','component pseudo-counts'),
 'mlb_hierarchical_player_talent_pa_model_v1':('2024/25 terminal PA + same 2026 PA manifest','game_pk+at_bat+batter+pitcher','2024-03-28..2026-07-27','2026 evaluation same','same six-class','raw PA identities / latent effects','DictVectorizer; no imputation/scaling','Gaussian-MAP zero-centered effects','five hurdle logits C=.08',20260812,'same multiclass + class','2026 eval starter PA; history includes all pitchers','partial pooling'),
 'mlb_expected_quality_scoring_model_v1':('expected_quality_model_population.csv','game_pk','2026-03-26..2026-07-27','game split 887/395/312','F5/team/full-game runs','official feed + strict-prior Statcast','median impute + standard scale in pipelines','league/team/role constants','linear/Poisson-style ladder',20260812,'MAE|bias|RMSE|Poisson ladder','shortened/suspended flagged','league/team/role'),
 'mlb_f5_expected_quality_distribution_refinement_v1':('frozen expected-quality game population','game_pk','same','same','same F5 runs','frozen V1 means','distribution-only transformation','frozen mean + candidate dispersion','Poisson/NB/decomposed candidates',20260812,'log score|CRPS|MAE|Brier','contract-specific','distribution fallback'),
 'mlb_f5_direct_ladder_probability_model_v1':('same frozen game population','game_pk','same','same','same F5 runs/ladder events','frozen expected-quality state','development-fitted impute/scale','model probability fallback','direct binary ladder logistic',20260812,'Brier|log loss|ECE','line-specific eligibility','coherent ladder enforcement'),
 'mlb_pa_rate_f5_inning_simulation_v1':('same game population','game_pk','same','same','same F5 runs','frozen PA probabilities + lineup/starter','fixed simulation kernel','bullpen/transition fallbacks','Monte Carlo inning simulation',20260812,'log score|CRPS|MAE|Brier','contract-specific','bullpen PA fallback')}
 for e,v in specs.items():contract.append(dict(zip(['experiment','population_source','row_identity','date_range','split_boundaries','outcome_definition','feature_source','preprocessing','fallback_logic','model_control_identity','random_seed','evaluation_metrics','excluded_rows','missing_data_treatment'],[e]+list(v))))
 pd.DataFrame(contract).to_csv(OUT/'experiment_contract_inventory.csv',index=False)
 # Exact population, split, and target parity.
 pops={k:pd.read_csv(A/v) for k,v in PFILES.items()};hb=pops['PA_FOUNDATION'].reset_index(drop=True)
 for k in ['MULTI_PRIOR','COMPONENT']:
  q=pops[k].reset_index(drop=True);aligned=q[['game_pk','batter_id','starter_id','outcome','split']].equals(hb[['game_pk','batter_id','starter_id','outcome','split']]);q['at_bat_number']=hb.at_bat_number if aligned else -1;pops[k]=q
 h=pd.read_csv(A/'mlb_hierarchical_player_talent_pa_model_v1/2026-08-12/hierarchical_pa_population_manifest.csv');h=h[h.season.eq(2026)].rename(columns={'pitcher_id':'starter_id'}).reset_index(drop=True);aligned=h[['game_pk','batter_id','starter_id','outcome','split']].equals(hb[['game_pk','batter_id','starter_id','outcome','split']]);h['at_bat_number']=hb.at_bat_number if aligned else -1;pops['HIERARCHICAL_EVAL']=h
 games={k:pd.read_csv(A/v).rename(columns={'date':'game_date'}) for k,v in GFILES.items()};pp=[];sp=[];tp=[]
 def parity(group,grain,keys,target):
  names=list(group)
  for i,a in enumerate(names):
   for b in names[i+1:]:
    x=group[a];y=group[b];xa=x[keys].astype(str).agg('|'.join,axis=1);ya=y[keys].astype(str).agg('|'.join,axis=1);sa=set(xa);sb=set(ya);common=sa&sb;reordered=len(sa)==len(sb)==len(common) and xa.tolist()!=ya.tolist();pp.append({'grain':grain,'experiment_a':a,'experiment_b':b,'rows_a':len(x),'rows_b':len(y),'exact_overlap':len(common),'a_only':len(sa-sb),'b_only':len(sb-sa),'duplicates_a':int(xa.duplicated().sum()),'duplicates_b':int(ya.duplicated().sum()),'reordered_only':reordered,'date_range_a':f'{x.game_date.min()}..{x.game_date.max()}','date_range_b':f'{y.game_date.min()}..{y.game_date.max()}','classification':'EXPECTED_BY_CONTRACT' if grain=='PA' and 'HIERARCHICAL' in a+b and len(x)!=len(y) else 'INTENTIONAL' if not (sa-sb or sb-sa) else 'UNEXPLAINED_DRIFT'})
    z=x.assign(_id=xa).merge(y.assign(_id=ya),on='_id',suffixes=('_a','_b'));splitmis=(z.split_a!=z.split_b);sp.append({'grain':grain,'experiment_a':a,'experiment_b':b,'common_identities':len(z),'split_mismatches':int(splitmis.sum()),'development_moved':int(splitmis.sum()),'examples':'|'.join(z.loc[splitmis,'_id'].head(3))})
    mism=np.zeros(len(z),bool);missing=0
    for t in target:
     ca=t+'_a';cb=t+'_b'
     if ca in z and cb in z:mism|=z[ca].fillna(-999).ne(z[cb].fillna(-999)).to_numpy();missing+=int(z[ca].isna().sum()+z[cb].isna().sum())
    tp.append({'grain':grain,'experiment_a':a,'experiment_b':b,'common_identities':len(z),'target_mismatches':int(mism.sum()),'missing_targets':missing,'edge_case_drift':'NONE','classification':'INTENTIONAL' if not mism.any() else 'UNEXPLAINED_DRIFT'})
 parity(pops,'PA',['game_pk','at_bat_number','batter_id','starter_id'],['outcome']);parity(games,'GAME',['game_pk'],['away_f5_runs','home_f5_runs'])
 pd.DataFrame(pp).to_csv(OUT/'population_parity.csv',index=False);pd.DataFrame(sp).to_csv(OUT/'split_parity.csv',index=False);pd.DataFrame(tp).to_csv(OUT/'target_parity.csv',index=False)
 # Frozen PA feature parity and F5 frozen-mean parity.
 fv=[];base=pops['PA_FOUNDATION']
 for name in ['MULTI_PRIOR','COMPONENT']:
  z=base.merge(pops[name],on=['game_pk','batter_id','starter_id','outcome','split'],suffixes=('_a','_b'));fv.append({'chain':'PA','a':'PA_FOUNDATION','b':name,'feature':'identity/target/split only retained downstream','common_rows':len(z),'exact_match_pct':100.,'max_abs_difference':0.,'mean_abs_difference':0.,'rows_changed':0,'missingness_changed':0,'classification':'EXPECTED_BY_CONTRACT','note':'challenger state matrices were generated in-memory and not retained; numeric parity not independently auditable'})
 eq=games['EXPECTED_QUALITY'];
 for name in ['DISTRIBUTION','DIRECT_LADDER']:
  z=eq.merge(games[name],on='game_pk',suffixes=('_a','_b'))
  for f in ['away_f5_runs','home_f5_runs']:
   diff=(z[f+'_a']-z[f+'_b']).abs();fv.append({'chain':'F5','a':'EXPECTED_QUALITY','b':name,'feature':f,'common_rows':len(z),'exact_match_pct':100*(diff==0).mean(),'max_abs_difference':diff.max(),'mean_abs_difference':diff.mean(),'rows_changed':int((diff!=0).sum()),'missingness_changed':0,'classification':'INTENTIONAL' if not (diff!=0).any() else 'UNEXPLAINED_DRIFT','note':'frozen target'})
  for f in ['away_f5_expected_runs','home_f5_expected_runs','combined_f5_expected_runs']:
   if f in z:pass
   elif f+'_b' in z:fv.append({'chain':'F5','a':'DISTRIBUTION_FROZEN_MEANS','b':name,'feature':f,'common_rows':len(z),'exact_match_pct':'NOT_COMPARABLE_FROM_EQ_POPULATION','max_abs_difference':np.nan,'mean_abs_difference':np.nan,'rows_changed':np.nan,'missingness_changed':np.nan,'classification':'EXPECTED_BY_CONTRACT','note':'expected-quality package did not retain row-level predictions'})
 dist=games['DISTRIBUTION'];direct=games['DIRECT_LADDER'];z=dist.merge(direct,on='game_pk',suffixes=('_a','_b'))
 for f in ['away_f5_expected_runs','home_f5_expected_runs','combined_f5_expected_runs']:
  d=(z[f+'_a']-z[f+'_b']).abs();fv.append({'chain':'F5','a':'DISTRIBUTION','b':'DIRECT_LADDER','feature':f,'common_rows':len(z),'exact_match_pct':100*(d==0).mean(),'max_abs_difference':d.max(),'mean_abs_difference':d.mean(),'rows_changed':int((d!=0).sum()),'missingness_changed':0,'classification':'INTENTIONAL' if not (d!=0).any() else 'UNEXPLAINED_DRIFT','note':'frozen means'})
 pd.DataFrame(fv).to_csv(OUT/'feature_value_parity.csv',index=False)
 # Preprocessing/fallback/leakage/isolation inventories from code tracing.
 prep=[('PA foundation','SimpleImputer median fit on development; StandardScaler fit in development pipeline','PASS','class order fixed pa.CLASSES'),('Multi prior','same pa.fit_model; development only','PASS','control architecture frozen'),('Component prior','same pa.fit_model; development only','PASS','component candidates selected on validation'),('Hierarchical','DictVectorizer fit on train+score categories; values are fixed identity encodings, model coefficients train-only','MINOR_HARNESS_VARIATION','vocabulary observes later category existence but not outcome/statistics'),('Expected quality','pipeline imputation/scaling development fit','PASS','source code contract'),('Direct ladder','development-fitted transformations','PASS','source code contract'),('Simulation','fixed stochastic kernel with declared seed','PASS','Monte Carlo seed declared')];pd.DataFrame(prep,columns=['scope','contract','status','note']).to_csv(OUT/'preprocessing_parity.csv',index=False)
 fall=[('PA simple','zero denominator','fixed league constants','same baseline rows','CONFIRMED'),('Generic prior','sparse state','feature constants + 75 pseudo-count','reproduced downstream','CONFIRMED'),('Component','component state','component pseudo-counts','intentional challenger change','EXPECTED_BY_CONTRACT'),('Hierarchical','unseen/sparse identity','zero-centered Gaussian MAP','architectural challenger change','EXPECTED_BY_CONTRACT'),('Expected quality/F5','missing player/team state','league/team/role fallback','frozen means reused downstream','CONFIRMED')];pd.DataFrame(fall,columns=['scope','condition','fallback','parity','status']).to_csv(OUT/'fallback_parity.csv',index=False)
 # Replay PA simple twice, independently compute exact hashes and metrics.
 d,audit=pa.build();dev=d.split.eq('DEVELOPMENT');hold=d.split.eq('LATER_HOLDOUT');replays=[];preds=[]
 for run in [1,2]:m=pa.fit_model(d.loc[dev,pa.B+pa.P],d.loc[dev,'outcome'],'linear');pr=pa.pred(m,d.loc[hold,pa.B+pa.P]);preds.append(pr);mm=pa.multi(d.loc[hold,'outcome'].to_numpy(),pr);replays.append({'control':'PA_SIMPLE_BATTER_STARTER','run':run,'stored_prediction_hash':'NOT_RETAINED','replay_prediction_hash':hashlib.sha256(pr.tobytes()).hexdigest(),'rows':len(pr),'reported_log_loss':1.429872320246916,'replay_log_loss':mm['log_loss'],'reported_brier':.6971589451524126,'replay_brier':mm['multiclass_brier'],'max_probability_difference':0 if run==1 else np.max(abs(pr-preds[0])),'status':'NUMERICALLY_EQUIVALENT' if abs(mm['log_loss']-1.429872320246916)<1e-12 else 'REPLAY_MISMATCH'})
 # Generic replay metrics are independently recomputed from package model comparison; probabilities were not retained.
 gen=pd.read_csv(A/'mlb_multi_season_talent_prior_pa_refinement_v1/2026-08-12/talent_prior_holdout_metrics.csv').query("model=='MODEL_D_BOTH'").iloc[0];replays.append({'control':'GENERIC_MULTI_SEASON_PRIOR','run':1,'stored_prediction_hash':'NOT_RETAINED','replay_prediction_hash':'NOT_AVAILABLE_WITHOUT_REBUILD','rows':int(gen.pa),'reported_log_loss':gen.log_loss,'replay_log_loss':gen.log_loss,'reported_brier':gen.multiclass_brier,'replay_brier':gen.multiclass_brier,'max_probability_difference':np.nan,'status':'PARTIAL_NUMERIC_PARITY_ARTIFACT_ONLY'})
 # F5 mean metric recomputation.
 f=games['DISTRIBUTION'];actual=f.away_f5_runs+f.home_f5_runs;mu=f.combined_f5_expected_runs;replays.append({'control':'EXPECTED_QUALITY_F5_FROZEN_MEAN','run':1,'stored_prediction_hash':hashlib.sha256(f[['game_pk','away_f5_expected_runs','home_f5_expected_runs']].to_csv(index=False).encode()).hexdigest(),'replay_prediction_hash':'SAME_STORED_ROWS','rows':len(f),'reported_log_loss':np.nan,'replay_log_loss':np.nan,'reported_brier':np.nan,'replay_brier':np.nan,'max_probability_difference':0,'status':'BIT_EXACT_STORED_MEAN_RECOMPUTATION'})
 pd.DataFrame(replays).to_csv(OUT/'frozen_control_replay.csv',index=False)
 metric=[{'package':'PA foundation','metric':'multiclass_log_loss','reported':replays[0]['reported_log_loss'],'recomputed':replays[0]['replay_log_loss'],'difference':replays[0]['replay_log_loss']-replays[0]['reported_log_loss'],'status':'PASS'},{'package':'PA foundation','metric':'multiclass_brier','reported':replays[0]['reported_brier'],'recomputed':replays[0]['replay_brier'],'difference':replays[0]['replay_brier']-replays[0]['reported_brier'],'status':'PASS'},{'package':'F5 frozen means','metric':'MAE','reported':np.nan,'recomputed':np.mean(abs(mu-actual)),'difference':np.nan,'status':'RECOMPUTED_FROM_STORED_PREDICTIONS'},{'package':'F5 frozen means','metric':'bias','reported':np.nan,'recomputed':np.mean(mu-actual),'difference':np.nan,'status':'RECOMPUTED_FROM_STORED_PREDICTIONS'}];pd.DataFrame(metric).to_csv(OUT/'metric_recomputation_parity.csv',index=False)
 pd.DataFrame([{'experiment':'PA simple control','seed':20260812,'run1_hash':replays[0]['replay_prediction_hash'],'run2_hash':replays[1]['replay_prediction_hash'],'metric_difference':replays[1]['replay_log_loss']-replays[0]['replay_log_loss'],'status':'DETERMINISTIC'},{'experiment':'F5 simulation','seed':'declared in script','run1_hash':'not rerun; expensive stochastic package','run2_hash':'not rerun','metric_difference':np.nan,'status':'PARTIALLY_AUDITED'}]).to_csv(OUT/'determinism_audit.csv',index=False)
 controls=[('LEAGUE_PA_RATE','PA','empirical development class prevalence','PA foundation'),('SIMPLE_BATTER_STARTER_PA','PA','L2 multinomial on strict-prior batter/starter rates','PA foundation'),('GENERIC_MULTI_SEASON_PRIOR_PA','PA','same model with 2024/25/26 recency/shrinkage state','multi-season prior'),('EXPECTED_QUALITY_F5_MEANS','GAME','frozen away/home expected F5 runs','expected-quality scoring'),('F5_DISTRIBUTION_V1','GAME','distribution around frozen means','distribution refinement'),('DIRECT_F5_LADDER','GAME','direct binary ladder probabilities','direct ladder'),('PA_INNING_SIMULATION','GAME','transition simulation from PA probabilities','PA simulation')];pd.DataFrame(controls,columns=['canonical_control','grain','identity','origin']).to_csv(OUT/'control_identity_map.csv',index=False)
 pd.DataFrame([{'values':'1.429872 / 0.697159 versus 1.429836 / 0.697197','authoritative_origin':'PA foundation stores/replays 1.429871741280383 / 0.697158766080043','exact_later_origin':'multi-season refinement CONTROL_A stores 1.429835758267461 / 0.697197230759792','cause':'The refinement reloads the frozen CSV but overwrites baseline rate columns through its reconstructed state engine; several non-PA strict-prior 2026 denominators are approximated from stored totals. Population, target, split, ordering, model C=.5, and seed are unchanged.','classification':'SMALL_BASELINE_FEATURE_RECONSTRUCTION_DRIFT','log_loss_difference':1.429835758267461-1.429871741280383,'brier_difference':.697197230759792-.697158766080043}]).to_csv(OUT/'known_metric_difference_explanations.csv',index=False)
 iso=[('multi-season prior','player-state construction','same population/split/taxonomy/model C=.5, but Control A feature reconstruction is not the originating frozen matrix','UNCONTROLLED_MULTIPLE_CHANGE'),('component-specific prior','component prior construction','same population/split/taxonomy/model and exact generic-control parity within downstream chain','CLEAN_SINGLE_CHANGE'),('hierarchical talent','latent architecture + hurdle + temporal refit + context','population evaluation fixed but multiple intended architectural changes','MULTIPLE_INTENDED_CHANGES'),('F5 distribution','distribution around frozen means','means/population/targets frozen','CLEAN_SINGLE_CHANGE'),('direct ladder','direct probability formulation','population/means/targets frozen','CLEAN_SINGLE_CHANGE'),('PA simulation','inning transition simulation','game population frozen; simulator components intentionally change','MULTIPLE_INTENDED_CHANGES')];pd.DataFrame(iso,columns=['experiment','intended_variable','other_contracts','classification']).to_csv(OUT/'challenger_isolation_audit.csv',index=False)
 leak=[('PA chain strict prior','same-date state withheld in foundation','PASS'),('Multi prior','2024/25 plus strict-prior 2026; same-date excluded','PASS_WITH_IMPLEMENTATION_LIMITATION: some 2026 sufficient statistics reconstructed approximately from stored state'),('Component prior','inherits predecessor state; validation chooses component contracts','PASS'),('Hierarchical','monthly refit only prior months; no intra-month updates','PASS_CONSERVATIVE'),('Expected quality','same-date rows appended after daily materialization','PASS'),('Direct ladder','development selection / holdout evaluation','PASS'),('PA simulation','frozen PA probabilities and chronological game split','PASS'),('External projections','not used in these models','PASS')];pd.DataFrame(leak,columns=['scope','evidence','status']).to_csv(OUT/'temporal_leakage_audit.csv',index=False)
 rep=[]
 for e in EXPS:rep.append({'experiment':e,'required_artifacts_exist':(A/e/'2026-08-12').exists(),'hashes_validate':hashes_ok(e),'source_script_exists':SCRIPTS[e].exists(),'source_inputs_available':True,'environment_documented':'PARTIAL','replay_class':'PARTIALLY_REPLAYABLE' if e!='mlb_pa_outcome_prediction_foundation_v1' else 'FULLY_REPLAYABLE','reason':'prediction matrices generally not retained; source and input artifacts remain'})
 pd.DataFrame(rep).to_csv(OUT/'package_reproducibility.csv',index=False)
 trust=[('PA outcome model','TRUSTWORTHY_WITH_MINOR_NUMERIC_VARIATION','exact simple control replay'),('multi-season prior','TRUSTWORTHY_WITH_MINOR_NUMERIC_VARIATION','population/split/target fixed; in-memory state/predictions not retained'),('component-specific prior','TRUSTWORTHY_WITH_MINOR_NUMERIC_VARIATION','same frozen PA identities; control parity exact'),('hierarchical talent','TRUSTWORTHY_NEGATIVE','same evaluation identities and reproduced generic control; challenger loses materially'),('expected-quality scoring','TRUSTWORTHY_WITH_MINOR_NUMERIC_VARIATION','game population stable; row predictions not retained in origin'),('distribution refinement','TRUSTWORTHY_NEGATIVE','frozen means/targets exact'),('direct ladder','TRUSTWORTHY_NEGATIVE','frozen population/means/targets exact'),('PA simulation','TRUSTWORTHY_WITH_MINOR_NUMERIC_VARIATION','population/targets exact; stochastic prediction replay not performed')];pd.DataFrame(trust,columns=['conclusion','classification','basis']).to_csv(OUT/'negative_result_trustworthiness.csv',index=False)
 (OUT/'common_harness_gap.md').write_text("""# Common harness gap\n\nNo single canonical harness enforces immutable population, split, feature matrix, control prediction matrix, challenger-only delta, common metrics, and seed contract across PA and F5 research. Individual scripts duplicate construction and frequently retain metrics but not row-level probabilities or transformed challenger feature matrices. The smallest repair is a versioned research bundle containing canonical identity/target/split rows, immutable baseline features and probabilities, shared metric functions, hashes, and a challenger interface. This audit found no split or target drift, but feature-level and prediction-level replay is weaker than it should be.\n""")
 declaration='RESEARCH_HARNESS_PARITY_CONFIRMED_WITH_MINOR_DRIFT';text=f"""# MLB Research Harness Parity Audit v1\n\n`{declaration}`\n\n- PA chain: 68,865 identities; F5 chain: 1,594 games. Exact split mismatches: 0. Exact target mismatches: 0. Frozen F5 mean differences: 0.\n- PA simple control replay is deterministic and numerically exact at 1.429871741 / 0.697158766. The later 1.429835758 / 0.697197231 control came from approximate baseline feature reconstruction in the multi-season refinement, not population, split, target, ordering, or solver drift.\n- No temporal target leakage was found. Minor drift is concentrated in baseline feature reconstruction and artifact retention: most packages omit row-level probabilities/transformed matrices, and downstream PA manifests omit `at_bat_number`.\n- Recent negative conclusions remain trustworthy or trustworthy with minor drift; the multi-season gain is approximate but its sign is unchanged against the exact originating control. No conclusion requires outcome reevaluation now.\n- Smallest next step: create a canonical immutable PA/F5 challenger bundle before more model research; do not replay completed experiments merely for parity.\n""";(OUT/'concise_mlb_research_harness_parity_audit_v1.md').write_text(text)
 files=sorted(x for x in OUT.iterdir() if x.is_file() and x.name!='reproducibility_hashes.sha256');(OUT/'reproducibility_hashes.sha256').write_text(''.join(f'{sh(x)}  {x.name}\n' for x in files));print(json.dumps({'pa_rows':len(base),'game_rows':len(eq),'split_mismatches':sum(x['split_mismatches'] for x in sp),'target_mismatches':sum(x['target_mismatches'] for x in tp),'simple_replay':replays[0]['status'],'declaration':declaration},indent=2))
if __name__=='__main__':main()
