#!/usr/bin/env python3
"""Stagewise opposition audit and prospective mechanism registration."""
from __future__ import annotations
import csv,hashlib,json,math
from functools import lru_cache
from pathlib import Path
import joblib,numpy as np,pandas as pd
from backend.mlb.prediction.make_prediction import _vectorize,_apply_line_sensitivity,_blend_weighted,predict
from backend.mlb.shared.semantic_model_registry import active_manifest
IN=Path('artifacts/analysis/model_development/mlb_multi_slate_strict_asof_replay/2026-07-09_2026-08-02');OUT=Path('artifacts/analysis/model_development/mlb_opposition_mechanism_audit/2026-08-03_final');PROPS=('hits','total_bases','strikeouts_pitching')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(name,d):d.to_csv(OUT/name,index=False,quoting=csv.QUOTE_MINIMAL)
def side(p,t):return 'over' if p>=t else 'under'
def favwin(actual,line,fav):return np.nan if pd.isna(actual) or actual==line else bool((actual>line)==(fav=='over'))
def pnl(price,win):return np.nan if pd.isna(win) else (price/100 if price>0 else 100/abs(price)) if win else -1.
def raw_lr(pipe,X):
 z=pipe.named_steps['pre'].transform(X);cc=pipe.named_steps['clf'].calibrated_classifiers_;return float(np.mean([c.estimator.predict_proba(z)[0,1] for c in cc]))
@lru_cache(maxsize=3)
def artifact(prop):return joblib.load(Path('models_out/latest')/f'{prop}.joblib')
def stages(prop,features):
 obj=artifact(prop);m=obj['meta'];X=_vectorize(features,m['input_columns']);lr=obj['lr'];rf=obj['rf'];lr_raw=raw_lr(lr,X);lr_cal=float(lr.predict_proba(X)[0,1]);rfp=float(rf.predict_proba(X)[0,1]);wl=max(float(m['auc_lr'])-.5,0);wr=max(float(m['auc_rf'])-.5,0);base=float(_blend_weighted([lr_raw,rfp],[wl,wr]));blend=float(_blend_weighted([lr_cal,rfp],[wl,wr]));final=float(_apply_line_sensitivity(prop=prop,p_over=blend,features=features));return {'lr_underlying_probability':lr_raw,'lr_embedded_calibrated_probability':lr_cal,'rf_probability':rfp,'underlying_estimator_probability':base,'auc_weighted_blended_probability':blend,'line_sensitivity_probability':final,'auc_lr':m['auc_lr'],'auc_rf':m['auc_rf'],'weight_lr':wl,'weight_rf':wr,'decision_threshold':m['decision_threshold']}
def family(name):
 n=name.lower()
 if n.startswith('isna__'):return 'data_sufficiency_or_history_depth'
 if any(x in n for x in ('line','price','implied','market','prop_value')):return 'market_or_line_input'
 if any(x in n for x in ('at_bats','plate_appearances','opportunity','outs_recorded','workload')):return 'opportunity_or_workload'
 if n.startswith('d7_') or 'streak' in n:return 'recent_form'
 if n.startswith(('d15_','d30_')):return 'longer_term_form'
 if n.startswith('bvp_') or any(x in n for x in ('opponent','starting_pitcher')):return 'opponent_or_matchup'
 if any(x in n for x in ('team','is_home','time_of_day','game_day','game_type')):return 'team_environment'
 if any(x in n for x in ('source','fallback','payload','provenance')):return 'fallback_or_provenance_indicator'
 if any(x in n for x in ('interaction','per_ab','per_hit','rate','avg','slg')):return 'duplicate_or_shared_parent_family'
 if any(x in n for x in ('hits','bases','home_runs','strikeouts','walks','earned_runs','doubles','rbi')):return 'player_ability_or_performance_rate'
 return 'other_explicit_family'
def feature_diag(prop,f):
 line=float(f.get('line',f.get('prop_value',0)));d7=f.get(f'd7_{prop}');d30=f.get(f'd30_{prop}');recent_long=bool(d7 is not None and d30 is not None and (float(d7)-line)*(float(d30)-line)<0)
 opp=[f.get('avg_ab_per_game_d7'),f.get('d7_at_bats')];ability=f.get(f'd30_{prop}');opportunity_ability='NOT_EVALUABLE'
 if prop=='total_bases' and any(v is not None for v in opp) and ability is not None:opportunity_ability='CONFLICT' if (float(opp[0] or opp[1] or 0)<=0)!=(float(ability)<=line) else 'ALIGNED'
 direct='FALLBACK_OR_PROXY' if 'fallback' in str(f.get('bvp_source','')).lower() else 'DIRECT_OR_PRECOMPUTED';return {'recent_long_term_conflict':recent_long,'opportunity_ability_status':opportunity_ability,'matchup_baseline_status':'NOT_RELIABLY_COMPARABLE_ACROSS_UNITS','dominant_feature_family':'UNAVAILABLE_NONADDITIVE_CALIBRATED_BLEND','positive_family_count':np.nan,'negative_family_count':np.nan,'single_family_dominance':'NOT_EVALUABLE','provenance_status':direct,'history_age_status':'NOT_DEFINED_IN_FROZEN_CONTRACT','history_completeness_status':'NOT_DEFINED_IN_FROZEN_CONTRACT'}
def origin(row):
 fav=row['market_favorite_side'];seq=[row['underlying_side'],row['embedded_calibration_side'],row['blend_side'],row['line_sensitivity_side']];flips=[i for i in range(1,len(seq)) if seq[i]!=seq[i-1]]
 if seq[-1]==fav:return 'FINAL_AGREEMENT_NOT_OPPOSITION'
 if len(flips)>1:return 'MULTIPLE_STAGE_OPPOSITION'
 if seq[0]!=fav and not flips:return 'FINAL_OPPOSITION_WITHOUT_STAGE_FLIP'
 if seq[0]!=fav:return 'BASE_ESTIMATOR_OPPOSITION'
 if flips==[1]:return 'EMBEDDED_CALIBRATION_CREATED_OPPOSITION'
 if flips==[2]:return 'BLEND_CREATED_OPPOSITION'
 if flips==[3]:return 'LINE_SENSITIVITY_CREATED_OPPOSITION'
 return 'STAGE_ORIGIN_UNRESOLVED'
def characterize(x,label):
 r=x[x.outcome_status.isin(['WIN','LOSS'])].copy();fw=r.favorite_outcome_win.astype(float);fp=r.favorite_price.astype(float);be=len(r)/(len(r)+sum(p/100 if p>0 else 100/abs(p) for p in fp)) if len(r) else np.nan;y=(r.outcome_status=='WIN').astype(float);mp=r.model_selected_side_probability.clip(1e-6,1-1e-6);mk=r.selected_side_no_vig_probability.clip(1e-6,1-1e-6)
 return {'category':label,'rows':len(x),'resolved_rows':len(r),'dates':x.game_date.nunique(),'games':x.game_id.nunique(),'distinct_player_games':x[['game_id','player_id']].drop_duplicates().shape[0],'market_favorite_win_rate':fw.mean(),'market_favorite_roi':np.mean([pnl(p,w) for p,w in zip(fp,fw)]) if len(r) else np.nan,'market_break_even_rate':be,'break_even_shortfall':fw.mean()-be,'model_selected_opposite_side_roi':r.loc[~r.model_market_agreement,'pnl_1u'].mean(),'model_brier':np.mean((mp-y)**2),'model_log_loss':np.mean(-(y*np.log(mp)+(1-y)*np.log(1-mp))),'market_brier':np.mean((mk-y)**2),'market_log_loss':np.mean(-(y*np.log(mk)+(1-y)*np.log(1-mk))),'maximum_date_share':x.game_date.value_counts(normalize=True).max() if len(x) else np.nan,'maximum_proposition_share':x.proposition.value_counts(normalize=True).max() if len(x) else np.nan}
def main():
 OUT.mkdir(parents=True,exist_ok=True);assert not any(OUT.iterdir()),'output directory must be empty';pred=pd.read_csv(IN/'aggregate_frozen_prediction_ledger.csv',low_memory=False);out=pd.read_csv(IN/'immutable_aggregate_official_outcome_ledger.csv');d=pred.merge(out[['canonical_row_identity','outcome_status','actual_value','pnl_1u']],on='canonical_row_identity',validate='one_to_one');rows=[]
 for i,r in d.iterrows():
  f=json.loads(r.canonical_feature_serialization);s=stages(r.proposition,f);t=s['decision_threshold'];fav=r.market_favorite_side if pd.notna(r.market_favorite_side) else ('over' if r.price_over_american<r.price_under_american else 'under');st={**s,'lr_underlying_side':side(s['lr_underlying_probability'],t),'lr_embedded_calibrated_side':side(s['lr_embedded_calibrated_probability'],t),'rf_side':side(s['rf_probability'],t),'underlying_side':side(s['underlying_estimator_probability'],t),'embedded_calibration_side':side(s['auc_weighted_blended_probability'],t),'blend_side':side(s['auc_weighted_blended_probability'],t),'line_sensitivity_side':side(s['line_sensitivity_probability'],t)};fd=feature_diag(r.proposition,f);price=r.price_over_american if fav=='over' else r.price_under_american;dct={'canonical_row_identity':r.canonical_row_identity,'game_date':r.game_date,'game_id':r.game_id,'player_id':r.player_id,'proposition':r.proposition,'line':r.line,'semantic_model_id':r.semantic_model_id,'model_artifact_sha256':r.model_artifact_sha256,'feature_vector_sha256':r.feature_vector_sha256,'feature_schema_sha256':r.feature_schema_sha256,'configuration_sha256':r.configuration_sha256,'calibration_identity':r.calibration_identity,'market_favorite_side':fav,'favorite_price':price,'market_favorite_price_band':'-250_or_shorter' if price<=-250 else '-200_to_-249' if price<=-200 else '-150_to_-199' if price<=-150 else '-100_to_-149','selected_model_side':r.selected_side,'selected_side_no_vig_probability':r.selected_side_no_vig_probability,'model_selected_side_probability':r.model_selected_side_probability,'model_market_agreement':r.selected_side==fav,'final_model_market_probability_gap':r.model_selected_side_probability-r.selected_side_no_vig_probability,**st,**fd,'delta_embedded_calibration':s['auc_weighted_blended_probability']-s['underlying_estimator_probability'],'delta_blend':0.0,'delta_line_sensitivity':s['line_sensitivity_probability']-s['auc_weighted_blended_probability'],'later_stage_reversal':len({st['underlying_side'],st['embedded_calibration_side'],st['line_sensitivity_side']})>1,'outcome_status':r.outcome_status,'actual_value':r.actual_value,'pnl_1u':r.pnl_1u};dct['first_opposition_stage']=next((n for n in ('underlying','embedded_calibration','blend','line_sensitivity') if dct[n+'_side']!=fav),'NONE');dct['stage_origin_category']=origin(dct);dct['favorite_outcome_win']=favwin(r.actual_value,r.line,fav);rows.append(dct)
  if (i+1)%500==0:print(i+1)
 z=pd.DataFrame(rows);prediction_only=z.drop(columns=['outcome_status','actual_value','pnl_1u','favorite_outcome_win']);write('immutable_stagewise_replay_diagnostic_ledger.csv',prediction_only)
 # Exact stage contract.
 contract={'version':'mlb_stagewise_probability_contract_v1','threshold_semantics':'Every stage side uses the registered proposition decision threshold.','stages':[{'name':'lr_underlying_probability','definition':'Mean raw predict_proba across the retained logistic fold estimators before isotonic maps.'},{'name':'lr_embedded_calibrated_probability','definition':'Serialized CalibratedClassifierCV.predict_proba output.'},{'name':'rf_probability','definition':'Serialized random-forest predict_proba; no embedded calibrator.'},{'name':'underlying_estimator_probability','definition':'Registered AUC-weighted blend of raw LR-fold probability and RF probability.'},{'name':'auc_weighted_blended_probability','definition':'Registered AUC-weighted blend of calibrated LR and RF component inputs.'},{'name':'line_sensitivity_probability','definition':'Deterministic registered log-odds line correction; equals final emitted over probability.'}],'limitation':'A distinct post-calibration pre-blend scalar does not exist in runtime. embedded_calibration_side is the calibrated-component blend; delta_blend is zero/not separately identifiable beyond retained component inputs.'};(OUT/'stagewise_probability_contract.json').write_text(json.dumps(contract,indent=2)+'\n')
 comps=[]
 for k,x in z.groupby('stage_origin_category'):comps.append(characterize(x,k))
 write('stage_origin_comparison_report.csv',pd.DataFrame(comps))
 # Outcome-independent feature-family registration from artifact contracts.
 fmap=[]
 for prop in PROPS:
  m=joblib.load(Path('models_out/latest')/f'{prop}.joblib')['meta']
  for f in m['input_columns']:fmap.append({'registry_version':'mlb_feature_family_registry_v1','proposition':prop,'feature':f,'family':family(f),'assignment_basis':'name and producing-contract semantics; outcome-independent','row_level_attribution':'DIRECTIONAL_ONLY_NONADDITIVE_MODEL' })
 write('feature_family_registry.csv',pd.DataFrame(fmap));avail=z.groupby('proposition').agg(rows=('canonical_row_identity','size'),recent_long_conflict_rows=('recent_long_term_conflict','sum'),opportunity_ability_evaluable=('opportunity_ability_status',lambda s:(s!='NOT_EVALUABLE').sum()),fallback_proxy_rows=('provenance_status',lambda s:(s=='FALLBACK_OR_PROXY').sum())).reset_index();avail['exact_additive_attribution_available']=False;avail['reason']='Isotonic cross-validated LR plus RF AUC blend is nonadditive; directional frozen-input diagnostics retained without manufactured precision.';write('feature_family_availability_and_attribution_report.csv',avail)
 # Prospective reason-code registry, frozen before any new-cohort grading.
 defs=[('UNDERLYING_MODEL_DIRECTION_CONFLICT','underlying_side != market_favorite_side','direction'),('CALIBRATION_DIRECTION_FLIP','underlying_side == favorite and embedded_calibration_side != favorite','direction'),('BLEND_DIRECTION_FLIP','component sides support favorite but blended side opposes','direction'),('LINE_SENSITIVITY_DIRECTION_FLIP','blend_side == favorite and line_sensitivity_side != favorite','direction'),('OPPORTUNITY_ABILITY_CONFLICT','registered opportunity and ability diagnostics oppose','direction'),('RECENT_LONG_TERM_CONFLICT','d7 proposition mean and d30 proposition mean lie on opposite sides of line','direction'),('MATCHUP_BASELINE_CONFLICT','not emitted unless comparable-unit matchup baseline exists','direction'),('SINGLE_FEATURE_FAMILY_DOMINANCE','not emitted unless reliable additive family attribution exists','confidence'),('FALLBACK_SUPPORTED_PREDICTION','provenance_status == FALLBACK_OR_PROXY','data_quality'),('STALE_HISTORY','not emitted without frozen contract definition','data_quality'),('INCOMPLETE_HISTORY','not emitted without frozen contract definition','data_quality'),('HIGH_MARKET_PRICE_BURDEN','market favorite American price <= -250','price'),('MODEL_MARKET_DISAGREEMENT','final selected side != market favorite side','direction'),('MECHANISM_UNRESOLVED','final disagreement with no other observable registered mechanism','data_quality')]
 reg=[]
 for code,definition,concern in defs:reg.append({'registry_version':'mlb_opposition_mechanism_registry_v1','reason_code':code,'exact_prediction_time_definition':definition,'mechanical_rationale':'Transparent diagnostic flag; never a rejection gate.','required_fields':definition,'availability_by_proposition':'all; fail closed where named inputs unavailable','fail_closed_behavior':'FALSE/NOT_EVALUABLE; never inferred','concern':concern,'authorized_use':'FORWARD_OBSERVATION_ONLY'})
 write('opposition_mechanism_registry.csv',pd.DataFrame(reg))
 # Apply each code independently, never intersections.
 flags={'UNDERLYING_MODEL_DIRECTION_CONFLICT':z.underlying_side!=z.market_favorite_side,'CALIBRATION_DIRECTION_FLIP':(z.underlying_side==z.market_favorite_side)&(z.embedded_calibration_side!=z.market_favorite_side),'BLEND_DIRECTION_FLIP':False,'LINE_SENSITIVITY_DIRECTION_FLIP':(z.blend_side==z.market_favorite_side)&(z.line_sensitivity_side!=z.market_favorite_side),'OPPORTUNITY_ABILITY_CONFLICT':z.opportunity_ability_status=='CONFLICT','RECENT_LONG_TERM_CONFLICT':z.recent_long_term_conflict,'MATCHUP_BASELINE_CONFLICT':False,'SINGLE_FEATURE_FAMILY_DOMINANCE':False,'FALLBACK_SUPPORTED_PREDICTION':z.provenance_status=='FALLBACK_OR_PROXY','STALE_HISTORY':False,'INCOMPLETE_HISTORY':False,'HIGH_MARKET_PRICE_BURDEN':z.favorite_price<=-250,'MODEL_MARKET_DISAGREEMENT':~z.model_market_agreement}
 flags['MECHANISM_UNRESOLVED']=flags['MODEL_MARKET_DISAGREEMENT']&~(flags['UNDERLYING_MODEL_DIRECTION_CONFLICT']|flags['CALIBRATION_DIRECTION_FLIP']|flags['LINE_SENSITIVITY_DIRECTION_FLIP'])
 chars=[]
 for code,mask in flags.items():
  if isinstance(mask,bool) or not mask.any():chars.append({'category':code,'classification':'NOT_EVALUABLE',**characterize(z.iloc[0:0],code)});continue
  x=z[mask];a=characterize(x,code);largest=x.game_date.value_counts().idxmax();pmax=x.proposition.value_counts().idxmax();a['after_removing_largest_date_market_favorite_win_rate']=z[mask&(z.game_date!=largest)].favorite_outcome_win.mean();a['after_removing_largest_proposition_market_favorite_win_rate']=z[mask&(z.proposition!=pmax)].favorite_outcome_win.mean();base=z[~mask];gap=a['market_favorite_win_rate']-base.favorite_outcome_win.mean();a['classification']='DESCRIPTIVE_WEAKER_FAVORITE_PATTERN' if gap<-.02 else 'DESCRIPTIVE_NO_DIFFERENCE' if abs(gap)<=.02 else 'DESCRIPTIVE_MIXED';chars.append(a)
 write('reason_code_replay_characterization.csv',pd.DataFrame(chars))
 schema={'schema_version':'mlb_prospective_opposition_diagnostic_sidecar_v1','join_key':'canonical_row_identity','immutability':'append-only sidecar; canonical prediction ledger unchanged','fields':list(prediction_only.columns),'outcome_fields_excluded_from_forward_sidecar':['outcome_status','actual_value','pnl_1u','favorite_outcome_win'],'freeze_requirement':'mechanism registry SHA must be recorded before cohort outcome access'};(OUT/'prospective_diagnostic_sidecar_schema.json').write_text(json.dumps(schema,indent=2)+'\n')
 # Reconstruct accepted Aug 3 cohort from immutable captured vectors, without outcomes.
 live=pd.read_csv('artifacts/analysis/model_development/mlb_prospective_semantic_registration/2026-08-03/append_only_prediction_ledger.csv',low_memory=False);live_rows=[]
 for _,r in live.iterrows():
  f=json.loads(r.feature_vector_canonical_json);prop=json.loads(r.canonical_row_identity)['prop_type'];s=stages(prop,f);t=s['decision_threshold'];fav=r.selected_side if bool(r.market_favorite) else ('under' if r.selected_side=='over' else 'over');live_rows.append({'canonical_row_identity':r.canonical_row_identity,'sidecar_status':'RECONSTRUCTED_FROM_FROZEN_PREDICTION_TIME_STATE','semantic_model_id':r.model_semantic_name,'model_artifact_sha256':r.model_artifact_sha256,'feature_vector_sha256':r.feature_vector_sha256,'feature_schema_sha256':r.feature_schema_sha256,'configuration_sha256':r.configuration_sha256,'calibration_identity':r.calibration_artifact_sha256,'market_favorite_side':fav,'market_favorite_price':r.price_over_american if fav=='over' else r.price_under_american,'model_market_agreement':r.selected_side==fav,'model_market_probability_gap':r.model_selected_side_probability-r.selected_side_no_vig_probability,**s,**{k:side(s[k],t) for k in ('underlying_estimator_probability','auc_weighted_blended_probability','line_sensitivity_probability')},**feature_diag(prop,f)})
 write('august_3_frozen_cohort_reconstructed_sidecar.csv',pd.DataFrame(live_rows))
 opp=z[~z.model_market_agreement];counts=opp.stage_origin_category.value_counts();base_n=int(counts.get('FINAL_OPPOSITION_WITHOUT_STAGE_FLIP',0)+counts.get('BASE_ESTIMATOR_OPPOSITION',0));down_n=len(opp)-base_n;mechanical='MODEL_OPPOSITION_PRIMARILY_ORIGINATED_IN_BASE_ESTIMATOR' if base_n>down_n else 'MODEL_OPPOSITION_PRIMARILY_ORIGINATED_IN_DOWNSTREAM_TRANSFORMATION' if down_n>base_n else 'MODEL_OPPOSITION_ORIGIN_MIXED';ready={'mechanical_decision':mechanical,'mechanism_decision':'OPPOSITION_MECHANISM_REGISTRY_FROZEN_FOR_PROSPECTIVE_VALIDATION','replay_characterization_decision':'DESCRIPTIVE_WEAKER_FAVORITE_MECHANISMS_IDENTIFIED_NONTRANSFERABLE' if any(x.get('classification')=='DESCRIPTIVE_WEAKER_FAVORITE_PATTERN' for x in chars) else 'MECHANISM_RESULT_MIXED','production':'NOT_AUTHORIZED','opposition_rows':len(opp),'base_origin_rows':base_n,'downstream_origin_rows':down_n,'stage_origin_counts':counts.to_dict(),'reliably_forward_observable':['UNDERLYING_MODEL_DIRECTION_CONFLICT','CALIBRATION_DIRECTION_FLIP','LINE_SENSITIVITY_DIRECTION_FLIP','RECENT_LONG_TERM_CONFLICT','FALLBACK_SUPPORTED_PREDICTION','HIGH_MARKET_PRICE_BURDEN','MODEL_MARKET_DISAGREEMENT'],'not_ready_without_contract_or_attribution':['STALE_HISTORY','INCOMPLETE_HISTORY','SINGLE_FEATURE_FAMILY_DOMINANCE','MATCHUP_BASELINE_CONFLICT'],'authorization':'characterization and prospective observation only; no selector/gate/threshold/intersection/promotion'};(OUT/'prospective_validation_readiness_report.json').write_text(json.dumps(ready,indent=2)+'\n')
 files=sorted(p for p in OUT.iterdir() if p.is_file() and p.name!='SHA256SUMS.csv');write('SHA256SUMS.csv',pd.DataFrame([{'file':p.name,'sha256':sha(p),'bytes':p.stat().st_size} for p in files]));print(json.dumps({**ready,'manifest_sha256':sha(OUT/'SHA256SUMS.csv')},indent=2))
if __name__=='__main__':main()
