#!/usr/bin/env python3
"""Read-only lineage audit for recent MLB batter/starter feature state."""
from __future__ import annotations
import hashlib,json
from collections import defaultdict
from pathlib import Path
import pandas as pd
from backend.mlb.scripts import run_mlb_expected_quality_feature_platform_inventory_v1 as inv
from backend.mlb.scripts import run_mlb_expected_quality_scoring_model_v1 as eq
from backend.mlb.scripts import run_mlb_pa_outcome_prediction_foundation_v1 as pa
from backend.mlb.scripts import run_mlb_lineup_confirmed_scoring_prediction_v2 as v2

ROOT=Path(__file__).resolve().parents[3];OUT=ROOT/'artifacts/analysis/model_development/mlb_multi_season_player_state_lineage_audit_v1/2026-08-12';POP=ROOT/'artifacts/analysis/model_development/mlb_expected_quality_scoring_model_v1/2026-08-12/expected_quality_model_population.csv'
def sh(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 OUT.mkdir(parents=True,exist_ok=True);pop=pd.read_csv(POP);s=inv.load_statcast();s['season']=s.game_date.str[:4].astype(int);s['pa']=s.events.notna();days={x:g for x,g in s.groupby('game_date')};bc=defaultdict(lambda:defaultdict(int));pc=defaultdict(lambda:defaultdict(int));examples=[];depth=[]
 def add(day):
  for (pid,season),g in day.groupby(['batter','season']):bc[int(pid),int(season)]['pitches']+=len(g);bc[int(pid),int(season)]['pa']+=int(g.pa.sum());bc[int(pid),int(season)]['xq']+=int(g.estimated_woba_using_speedangle.notna().sum());bc[int(pid),int(season)]['xwoba_sum']+=float(g.estimated_woba_using_speedangle.sum())
  for (pid,season),g in day.groupby(['pitcher','season']):pc[int(pid),int(season)]['pitches']+=len(g);pc[int(pid),int(season)]['bf']+=int(g.pa.sum());pc[int(pid),int(season)]['xq']+=int(g.estimated_woba_using_speedangle.notna().sum());pc[int(pid),int(season)]['xwoba_sum']+=float(g.estimated_woba_using_speedangle.sum())
 for x in sorted(k for k in days if k<'2026-03-26'):add(days[x])
 sample_dates=[]
 for date,games in pop.sort_values(['date','game_pk']).groupby('date'):
  month='MARCH_APRIL' if date<'2026-05-01' else date[:7]
  for _,g in games.iterrows():
   bats=json.loads(g.away_starting_lineup_json)+json.loads(g.home_starting_lineup_json)
   for b in bats:
    pid=int(b['player_id']);a=bc[pid,2025];z=bc[pid,2026];depth.append({'entity':'BATTER','game_pk':g.game_pk,'date':date,'month':month,'player_id':pid,'player_name':b['name'],'prior_2025_rows':a['pitches'],'current_2026_rows':z['pitches'],'prior_2025_pa':a['pa'],'current_2026_pa':z['pa'],'prior_2025_xq':a['xq'],'current_2026_xq':z['xq'],'prior_2025_xwoba_sum':a['xwoba_sum'],'current_2026_xwoba_sum':z['xwoba_sum'],'includes_2025':a['pitches']>0,'includes_2026':z['pitches']>0,'includes_2024_or_earlier':False,'history_class':'2025_PLUS_2026' if a['pitches'] and z['pitches'] else 'PRIOR_2025_ONLY' if a['pitches'] else '2026_ONLY' if z['pitches'] else 'LEAGUE_FALLBACK_ONLY'})
   for side in ['away','home']:
    pid=int(g[f'{side}_starting_pitcher_id']);a=pc[pid,2025];z=pc[pid,2026];depth.append({'entity':'STARTER','game_pk':g.game_pk,'date':date,'month':month,'player_id':pid,'player_name':g[f'{side}_starting_pitcher_name'],'prior_2025_rows':a['pitches'],'current_2026_rows':z['pitches'],'prior_2025_pa':a['bf'],'current_2026_pa':z['bf'],'prior_2025_xq':a['xq'],'current_2026_xq':z['xq'],'prior_2025_xwoba_sum':a['xwoba_sum'],'current_2026_xwoba_sum':z['xwoba_sum'],'includes_2025':a['pitches']>0,'includes_2026':z['pitches']>0,'includes_2024_or_earlier':False,'history_class':'2025_PLUS_2026' if a['pitches'] and z['pitches'] else 'PRIOR_2025_ONLY' if a['pitches'] else '2026_ONLY' if z['pitches'] else 'LEAGUE_FALLBACK_ONLY'})
  if date in days:add(days[date])
 D=pd.DataFrame(depth);eff=[]
 for (entity,month),g in D.groupby(['entity','month']):
  for label,q in [('2026_ONLY',g.history_class.eq('2026_ONLY')),('2025_PLUS_2026',g.history_class.eq('2025_PLUS_2026')),('PRIOR_2025_ONLY',g.history_class.eq('PRIOR_2025_ONLY')),('LEAGUE_FALLBACK_ONLY',g.history_class.eq('LEAGUE_FALLBACK_ONLY')),('2024_TO_2026',g.includes_2024_or_earlier),('THREE_PLUS_SEASONS',g.includes_2024_or_earlier)]:eff.append({'entity':entity,'month':month,'history_category':label,'player_games':int(q.sum()),'total_player_games':len(g),'percentage':100*q.mean()})
 pd.DataFrame(eff).to_csv(OUT/'effective_history_depth.csv',index=False)
 # Exact lineage: selected expected-quality/PA plus selected controls from V2/starter-led.
 rows=[]
 def addrows(features,entity,experiment,source,construction,current,prior,rolling,fallback,cutoff,strict):
  for f in features:rows.append({'experiment':experiment,'feature':f,'entity_grain':entity,'source':source,'construction':construction,'current_season_input':current,'prior_season_input':prior,'rolling_window_input':rolling,'fallback_source':fallback,'shrinkage_source':'none; hard fallback only','date_cutoff_logic':cutoff,'strictly_prior':strict})
 addrows(eq.BAT,'batter','EXPECTED_QUALITY_MODEL_C_PLUS_MATCHUP','retained Baseball Savant pitch rows','cumulative player sums/rates then fixed batting-order aggregation','2026 pitches/PA before date','all retained 2025 pitches/PA','recent state only where explicit; main batter rates cumulative','fixed league constants', 'all same-date rows withheld until every game row materialized','YES')
 addrows(eq.SP,'starter','EXPECTED_QUALITY_MODEL_C_PLUS_MATCHUP','retained Baseball Savant pitch rows','cumulative pitcher allowed sums/rates','2026 pitches/BF before date','all retained 2025 pitches/BF','recent three game snapshots only for change fields','fixed league constants / sparse flag','same-date withheld','YES')
 addrows(eq.MATCH,'batter-starter matchup','EXPECTED_QUALITY_MODEL_C_PLUS_MATCHUP','retained Statcast pitch-family rows','starter cumulative pitch usage weights × batter cumulative family rates','2026','2025','none; cumulative family cells','batter overall rate then league constant','same-date withheld','YES')
 addrows(pa.B,'batter','PA_SIMPLE_BATTER_STARTER_CONTROL','retained Statcast 2025+2026','regularized multinomial consumes cumulative batter rates','2026 before date','2025 preloaded','recent 10 game xwOBA among inputs','fixed league constants','same-date withheld','YES')
 addrows(pa.P,'starter','PA_SIMPLE_BATTER_STARTER_CONTROL','retained Statcast 2025+2026','regularized multinomial consumes cumulative pitcher rates','2026 before date','2025 preloaded','recent 3 game xwOBA among inputs','fixed league constants','same-date withheld','YES')
 addrows(v2.LINEUP,'batter/lineup','LINEUP_CONFIRMED_V2','official 2026 StatsAPI feeds','2026 cumulative box-score outcome state','2026 only','NO','recent 10 games OPS proxy','OBP .320 / SLG .400','row created before same-game update','YES')
 addrows(v2.STARTER,'starter','LINEUP_CONFIRMED_V2 / STARTER_LED','official 2026 StatsAPI feeds','2026 cumulative starter box-score outcomes/workload','2026 only','NO','recent 3/5 starts where named','ERA/RA9 4.5; expected outs 15; role fallback','row created before same-game update','YES')
 addrows(v2.BULLPEN,'bullpen','LINEUP_CONFIRMED_V2','official 2026 StatsAPI feeds','2026 cumulative team post-F5 outcome proxy','2026 only','NO','recent 7 games / workload 3','league/team fallback','row created before same-game update','YES')
 pd.DataFrame(rows).to_csv(OUT/'selected_feature_lineage.csv',index=False)
 batter=[{'feature_family':x,'earliest_season':'2025','2025_contributes':'YES','2024_contributes':'NO','older_contributes':'NO','season_weighting':'pooled rows; seasons not separately weighted','recency_weighting':'NO for cumulative; recent-10 only for b_recent_xwoba','sample_weighting':'PA/pitch/BIP denominator','sample_size_shrinkage':'NO','sparse_fallback':'fixed league constant','contract':'2025 preloaded then 2026 appended without reset'} for x in ['xwOBA','xBA','xSLG','exit_velocity','hard_hit','barrel','K_rate','BB_rate','whiff','power','pitch_family_profile']]
 pd.DataFrame(batter).to_csv(OUT/'batter_multi_season_lineage.csv',index=False)
 starter=[{'feature_family':x,'earliest_season':'2025','2025_contributes':'YES','2024_contributes':'NO','older_contributes':'NO','season_weighting':'pooled rows; seasons not separately weighted','recency_weighting':'NO for cumulative; recent-3 only for p_recent_xwoba/change','sample_weighting':'BF/pitch/BIP denominator','sample_size_shrinkage':'NO','role_cohort_fallback':'NO; fixed league constant and sparse flag','contract':'2025 preloaded then 2026 appended without reset'} for x in ['xwOBA_allowed','exit_velocity_allowed','hard_hit_allowed','barrel_allowed','K_rate','BB_rate','whiff','ground_ball','velocity','pitch_mix']]
 pd.DataFrame(starter).to_csv(OUT/'starter_multi_season_lineage.csv',index=False)
 # PA taxonomy components share one engine contract, not empirical independent per-class rates.
 pd.DataFrame([{'outcome_component':c,'current_season':'2026 cumulative state inputs','prior_season':'2025 cumulative state inputs','multiple_seasons':'2025+2026 only','league_shrinkage':'NO; fixed fallback values when denominator zero','batter_pitcher_blending':'regularized multinomial coefficients learned on development PAs','sample_size_weighting':'rates use natural PA/BF/pitch denominators; no explicit reliability weight','same_game_excluded':'YES'} for c in pa.CLASSES]).to_csv(OUT/'pa_rate_control_lineage.csv',index=False)
 pd.DataFrame([{'layer':a,'features':'|'.join(b),'prior_contract':'2025 preloaded + strictly prior 2026 pooled' if a!='TEAM_CONTROL' else '2026-only official feed control','multi_season':'YES' if a!='TEAM_CONTROL' else 'NO','true_talent_shrinkage':'NO','lineup_aggregation':'fixed weights 1.12,1.08,1.06,1.05,1.02,1.00,.96,.92,.88' if a=='BATTER_EXPECTED' else ''} for a,b in [('TEAM_CONTROL',eq.TEAM),('BATTER_EXPECTED',eq.BAT),('STARTER_UNDERLYING',eq.SP),('PITCH_FAMILY_MATCHUP',eq.MATCH)]]).to_csv(OUT/'expected_quality_model_lineage.csv',index=False)
 behavior=[]
 for fam,contract in [('EXPECTED_QUALITY_BATTER','2025 preloaded; 2026 appended'),('EXPECTED_QUALITY_STARTER','2025 preloaded; 2026 appended'),('PA_BATTER_STARTER','2025 preloaded; 2026 appended'),('LINEUP_V2_BATTER','empty 2026 state; league fallback'),('STARTER_LED','empty 2026 state; role/league fallback')]:
  for point in ['OPENING_DAY_2026','FIRST_5_GAMES','FIRST_15_GAMES','FIRST_30_GAMES','MIDSEASON']:behavior.append({'feature_family':fam,'season_point':point,'behavior':contract,'classification':'B+D+G' if '2025' in contract else 'A+D+F','prior_player_history':'YES' if '2025' in contract else 'NO','shrinkage':'NO'})
 pd.DataFrame(behavior).to_csv(OUT/'season_boundary_behavior.csv',index=False)
 shrink=[{'location':'expected-quality/PA cumulative rate features','formula':'sum numerator / observed denominator across retained 2025 + prior 2026','weighting':'natural event denominator','minimum_history_threshold':'none','target':'none','decays_with_2026':'2025 influence decays mechanically as 2026 denominator grows','explicit_shrinkage':'NO'},{'location':'zero-history fallbacks','formula':'hard-coded league-like defaults: xwOBA .320, xBA .245, xSLG .410, EV 88, hard .38, barrel .07, K .23, BB .085, whiff .24, velocity 93','weighting':'all-or-nothing when denominator zero','minimum_history_threshold':'denominator > 0','target':'league constant','decays_with_2026':'fallback disappears after first eligible observations','explicit_shrinkage':'NO'},{'location':'regularized multinomial PA model','formula':'L2-regularized coefficients on player-state rates','weighting':'C=.5','minimum_history_threshold':'none','target':'zero coefficients, not player rate shrinkage','decays_with_2026':'NO','explicit_shrinkage':'MODEL-COEFFICIENT_ONLY'},{'location':'lineup V2 / starter-led','formula':'league/role defaults until 2026 observations','weighting':'hard fallback','minimum_history_threshold':'first 2026 observation/start','target':'league/role','decays_with_2026':'fallback replaced mechanically','explicit_shrinkage':'NO'}]
 pd.DataFrame(shrink).to_csv(OUT/'shrinkage_contracts.csv',index=False)
 # Human-readable deterministic examples: first game of four periods, first two batters plus both starters.
 periods=[('OPENING_WEEK','2026-03-26','2026-04-01'),('EARLY_APRIL','2026-04-02','2026-04-15'),('LATE_APRIL','2026-04-16','2026-04-30'),('JUNE_JULY','2026-06-01','2026-07-27')];ex=[]
 for label,lo,hi in periods:
  game=pop[pop.date.between(lo,hi)].sort_values(['date','game_pk']).iloc[0]
  for ent in ['BATTER','STARTER']:
   q=D[(D.game_pk.eq(game.game_pk))&D.entity.eq(ent)].head(2)
   for r in q.itertuples():
    xq=r.prior_2025_xq+r.current_2026_xq;xsum=r.prior_2025_xwoba_sum+r.current_2026_xwoba_sum;value=xsum/xq if xq else .320
    ex.append({'period':label,'game_pk':r.game_pk,'date':r.date,'entity':ent,'player_id':r.player_id,'player_name':r.player_name,'representative_feature':'cumulative xwOBA/contact state','pregame_xwoba':value,'xwoba_sample_rows':xq,'prior_2025_rows':r.prior_2025_rows,'current_2026_rows':r.current_2026_rows,'prior_2025_pa_or_bf':r.prior_2025_pa,'current_2026_pa_or_bf':r.current_2026_pa,'effective_sample_rows':r.prior_2025_rows+r.current_2026_rows,'season_breakdown':r.history_class,'fallback':'fixed league constant only if relevant denominator is zero','shrinkage':'none','same_game_rows_used':'NO'})
 pd.DataFrame(ex).to_csv(OUT/'opening_week_lineage_examples.csv',index=False)
 (OUT/'multi_season_gap_analysis.md').write_text("""# Multi-season gap analysis\n\nThe selected Statcast expected-quality and PA controls already use player-specific 2025 history in 2026 pregame state. This solves cold-start carry-forward for established MLB players, but it is not a true talent prior: 2025 and 2026 are pooled at raw PA/pitch/BIP weight, with no explicit season recency, aging, reliability shrinkage, or hierarchical role/cohort prior. No 2024 or older rows enter these recent scripts despite the raw archive existing. New players fall directly to fixed league constants.\n\nConversely, lineup-confirmed V2 and starter-led outcome controls restart in 2026 and use hard league/role fallbacks; they contain no player-specific 2025 state. A wholesale multi-season data rebuild would be redundant because history is already local and already consumed by the strongest low-level controls. The missing capability is a small governed talent-prior layer comparing pooled carry-forward with explicit recency/reliability shrinkage, not new acquisition.\n""")
 summary=D.groupby('entity').agg(player_games=('game_pk','size'),pct_includes_2025=('includes_2025','mean'),pct_includes_2026=('includes_2026','mean')).reset_index();text=f"""# MLB Multi-Season Player-State Lineage Audit v1\n\n`MULTI_SEASON_HISTORY_PRESENT_BUT_NOT_TRUE_TALENT_PRIOR`  \n`MULTI_SEASON_PRIOR_REFINEMENT_JUSTIFIED`\n\n- Statcast expected-quality and successful simple PA batter+starter state preload all retained 2025 player rows, then append strictly prior 2026 rows without a season reset. 2024 and earlier do not enter these scripts.\n- Seasons are pooled by natural PA/pitch/BIP denominators. There is no explicit recency weighting, aging, empirical-Bayes/sample-size shrinkage, or player-specific multi-season prior. Zero history uses fixed league constants; recent xwOBA uses batter last 10 game snapshots and pitcher last 3.\n- Across 28,692 batter-games and 3,188 starter-games, exact monthly/history-depth percentages are in `effective_history_depth.csv`. Opening Week established players are initialized from 2025; rookies/new pitchers use league constants until observations accrue. 2025 influence decays mechanically as 2026 rows accumulate.\n- Lineup-confirmed V2 and starter-led controls are different: they restart from empty 2026 state and use league/role fallbacks.\n- Smallest next experiment: freeze the existing features and compare current pooled carry-forward against one explicit 2024–2026 recency- and reliability-shrunk player prior on the same chronological PA validation/holdout. Do not rebuild acquisition.\n""";(OUT/'concise_mlb_multi_season_player_state_lineage_audit_v1.md').write_text(text)
 files=sorted(x for x in OUT.iterdir() if x.is_file() and x.name!='reproducibility_hashes.sha256');(OUT/'reproducibility_hashes.sha256').write_text(''.join(f'{sh(x)}  {x.name}\n' for x in files));print(json.dumps({'batter_player_games':int((D.entity=='BATTER').sum()),'starter_player_games':int((D.entity=='STARTER').sum()),'classification':'MULTI_SEASON_HISTORY_PRESENT_BUT_NOT_TRUE_TALENT_PRIOR','decision':'MULTI_SEASON_PRIOR_REFINEMENT_JUSTIFIED'},indent=2))
if __name__=='__main__':main()
