name: Cron Runner

on:
  schedule:
    - cron: "0 0,8,16 * * *" # Runs at 02:00, 10:00, 18:00 UTC daily
  workflow_dispatch: # ✅ Manual trigger from GitHub UI

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # ✅ Match your current environment

      - name: 📥 Install dependencies
        run: npm install

      - name: 🚀 Run Cron Script
        run: node scripts/cronRunner.js
        env: # ✅ Correct placement — tied to this step
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GITHUB_ACTIONS: true
