name: Update Player Streak Profiles

on:
  schedule:
    - cron: "16 6 * * *" # 🕕 Runs daily at 06:16 UTC
  workflow_dispatch: # ✅ Allows manual triggering

jobs:
  update-player-streaks:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v3

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 📦 Install Dependencies
        run: |
          npm install

      - name: 🔐 Export Environment Secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
          echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" >> $GITHUB_ENV

      - name: 🧠 Run Player Streak Profiles Update (User-Added)
        run: |
          node backend/scripts/generatePlayerStreakProfiles.js

      - name: 🧠 Run Player Streak Backfill from Training (Stat-Derived)
        run: |
          node backend/scripts/runStreakBackfillFromTraining.js
