#!/usr/bin/env python3
"""Assess prospective NHL goalie source readiness without network acquisition."""
from __future__ import annotations
import argparse,hashlib,json,os,re,subprocess
from pathlib import Path
import pandas as pd
from backend.nhl.analysis_package_guard import require_create_only,verify_parents

DATE='2026-08-10'; CHAMPION='NHL_MONEYLINE_TEAM_SCHEDULE_LOGIT_CONTROL_V1'; PRED_SHA='83beb11588f7e7e31919f23be2dea51ff49863954fc9be750509b30a0eff2cda'
PARENTS={'prospective':('nhl_season_2026_mainline_prospective_readiness','2026-07-13','bccba8eae9f13088d1b25f057349039a5ecccb688acdc09c0355dec1e83f3a95'),'opening':('nhl_season_2026_opening_preseason_context_readiness','2026-07-13','96f2f5e5e9f2125c95863f95fc4f58944868d4ae68533aade3fc93a10becade9'),'persistence':('nhl_season_opening_team_strength_persistence','2026-08-10','441663f6c06292b6b4a1dc91dec682be547b46ab1e7d9eec6705077f320a642c')}
DOCS={'workflow':'https://sportsdata.io/developers/workflow-guide/nhl','dictionary':'https://sportsdata.io/developers/data-dictionary/nhl','api':'https://sportsdata.io/developers/api-documentation/nhl','nhl_api':'https://api-web.nhle.com/v1','sportradar':'https://developer.sportradar.com/ice-hockey/reference/global-ice-hockey-season-lineups'}
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def csv(d,p): d.to_csv(p,index=False,lineterminator='\n')
def js(o,p): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+'\n')
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[3]); ap.add_argument('--output-dir',type=Path); a=ap.parse_args(); root=a.repo_root.resolve(); base=root/'artifacts/analysis/model_development'; out=(a.output_dir or base/f'nhl_season_2026_goalie_source_integration_readiness/{DATE}').resolve()
 pp={k:base/name/stamp for k,(name,stamp,_) in PARENTS.items()};verify_parents([(p,PARENTS[k][2]) for k,p in pp.items()]);require_create_only(out);out.mkdir(parents=True);before={str(x):sha(x) for p in pp.values() for x in p.iterdir() if x.is_file()}
 frozen=base/'nhl_moneyline_simple_baseline_process_validation/2026-07-13/nhl_moneyline_simple_baseline_control_predictions_2026-07-13.csv'; assert sha(frozen)==PRED_SHA
 configured={n:bool(os.environ.get(n)) for n in ['SPORTSDATAIO_API_KEY','SPORTSDATA_API_KEY','SPORTRADAR_API_KEY']}; assert not any(configured.values())

 existing=pd.DataFrame([
  ['goalie_game_logs_raw','database + backend/nhl/scripts/seed_goalie_logs_for_date.py','actual identity, saves, shots faced, TOI after participation','ACTUAL_STARTER_ONLY','actual max-TOI/start context is postgame and never pregame evidence'],
  ['seed_goalie_features_for_slate.sql','backend/nhl/sql/seed_goalie_features_for_slate.sql','candidate roster goalies plus strict-prior performance','REUSABLE_WITH_MINOR_ADAPTATION','does not identify projected starter'],
  ['official roster collection','refresh_players_and_roster_today.py|import_roster_today.py','goalie roster membership and NHL player IDs','CURRENT_STATE_ONLY','roster membership is not starting status; current upserts are not append-only'],
  ['player_external_ids','nhl.player_external_ids and seed_skater_logs_for_date.py','provider player crosswalk framework','REUSABLE','new SportsDataIO provider rows require governed deterministic creation'],
  ['team_external_ids','nhl.team_external_ids and import_schedule_today.py','provider team crosswalk framework','REUSABLE','official NHL team mapping exists; new provider namespace required'],
  ['official schedule importer','backend/nhl/scripts/import_schedule_today.py','NHL game ID, teams, start, season, game type','REUSABLE','authoritative binding target'],
  ['mainline H2H binder','backend/nhl/mainline_shadow/core.py:normalize_h2h','exact home/away plus start within 15 minutes','REUSABLE_WITH_MINOR_ADAPTATION','fallback template; goalie binding must add team/player identity'],
  ['mainline timestamp helpers','backend/nhl/mainline_shadow/core.py:parse_utc','UTC parsing and pre-start gates','REUSABLE','provider Eastern timestamps require explicit timezone conversion'],
  ['dormant goalie projection integration','repository search','none found','NOT_USEFUL_FOR_PREGAME','no connected projected/confirmed goalie feed'],
 ],columns=['component','location','capability','classification','boundary']); csv(existing,out/f'nhl_existing_goalie_capability_inventory_{DATE}.csv')

 candidates=pd.DataFrame([
  ['SportsDataIO Starting Goaltenders by Date','commercial JSON/XML API','API key and account/product access','COMMERCIAL_TRIAL_OR_PAID',True,True,True,False,False,'SportsDataIO GameID/TeamID/PlayerID','documented projections around prior-night 21:00 Eastern and confirmations after announcements','vendor archive/product dependent','medium','strongest semantics, but documented StartingGoaltenders schema lacks Created/Updated/source-change timestamp'],
  ['Official NHL schedule/gamecenter/boxscore','public JSON API','none','FREE',False,False,True,True,True,'native NHL game/team/player IDs','schedule/game-state updates; no projected starter state','official historical game data','low','identity authority and actual outcome context only'],
  ['Repository NHL roster path','public NHL API plus existing database','existing database credentials','ALREADY_CONNECTED',False,False,False,True,True,'native NHL team/player IDs; game roster binding','poll driven','current mutable roster plus sparse historical rows','low','roster membership does not establish starter'],
  ['Sportradar Global Ice Hockey lineups','commercial JSON/XML API','API key trial/production','COMMERCIAL',False,False,True,True,True,'Sportradar event/team/player IDs','30-second cache documented for lineup endpoint','provider dependent','high','documentation says starter and played are not differentiated; unsuitable for projected/confirmed NHL goalie state'],
  ['Public goalie-report websites','HTML pages','terms/access vary','UNASSESSED',True,True,False,False,False,'names and teams','page dependent','custom scraping required','high','excluded: arbitrary web scraping is not governed or authorized'],
 ],columns=['source','access_method','authentication','commercial_status','projected_support','confirmed_support','actual_support','source_timestamp_documented','update_timestamp_documented','identity_fields','update_cadence','historical_archive','expected_integration_effort','finding']); csv(candidates,out/f'nhl_goalie_candidate_source_inventory_{DATE}.csv')

 schema=pd.DataFrame([
  ['source_game_id','GameID','documented integer SportsDataIO game identity','AVAILABLE','requires crosswalk to NHL game_id'],['canonical_season','Season','SportsDataIO uses end-year convention','AVAILABLE_REQUIRES_TRANSFORM','convert explicitly to repository starting-year identity; never persist provider season as canonical'],['season_type','SeasonType','provider: 1 regular, 2 preseason, 3 postseason','AVAILABLE_REQUIRES_MAPPING','provider type codes differ from official NHL codes and need source-specific mapping'],['scheduled_start_time_utc','DateTime','documented US Eastern datetime','AVAILABLE_REQUIRES_TIMEZONE','convert EST/EDT to UTC with zone-aware parser'],['home_team','HomeTeamID + HomeTeam','vendor ID and abbreviation','AVAILABLE','crosswalk to official NHL team ID'],['away_team','AwayTeamID + AwayTeam','vendor ID and abbreviation','AVAILABLE','crosswalk to official NHL team ID'],['projected_goalie','HomeGoaltender/AwayGoaltender + Confirmed=false','nested Goaltender','AVAILABLE','maps to PROJECTED; LIKELY is not separately documented'],['confirmed_goalie','HomeGoaltender/AwayGoaltender + Confirmed=true','nested Goaltender','AVAILABLE','maps to CONFIRMED'],['source_player_id','Goaltender.PlayerID','career-stable SportsDataIO ID','AVAILABLE','requires deterministic NHL player crosswalk'],['goalie_name','FirstName + LastName','documented names','AVAILABLE','diagnostic only; never certified name-only identity'],['source_timestamp_utc','no documented field on StartingGoaltenders','required state-change timestamp','NOT_AVAILABLE','cannot certify provider state-change time'],['record_updated_utc','no documented Created/Updated on StartingGoaltenders','last modified time','NOT_AVAILABLE','other SportsDataIO records expose Updated, but it is not documented for this feed'],['capture_timestamp_utc','collector clock','Proppadia acquisition time','AVAILABLE_IF_IMPLEMENTED','cannot substitute for source timestamp'],['goalie_status','derived from null goalie + Confirmed','NO_PROJECTION|PROJECTED|CONFIRMED|UNKNOWN','PARTIAL','LIKELY and CHANGED_AFTER_CONFIRMATION require state comparison, not native values'],
 ],columns=['proppadia_field','sportsdataio_field','semantics','readiness','constraint']); csv(schema,out/f'nhl_goalie_source_schema_mapping_{DATE}.csv')

 game_contract={'canonical_season':2026,'preferred_binding':'maintained SportsDataIO GameID -> official NHL game_id crosswalk established from a deterministic match','required_source_fields':['GameID','DateTime','HomeTeamID','HomeTeam','AwayTeamID','AwayTeam'],'fallback_rule':'exact mapped home team + exact mapped away team + scheduled start within 15 minutes + matching source-specific season type','statuses':['EXACT_ID_MATCH','DETERMINISTIC_CROSSWALK','NAME_TEAM_FALLBACK','AMBIGUOUS','UNBOUND'],'certified_statuses':['EXACT_ID_MATCH','DETERMINISTIC_CROSSWALK'],'fail_closed':['zero or multiple NHL candidates','unmapped team','start difference over 15 minutes','source game key changed without explicit supersession','season type conflict'],'reschedule_policy':'retain every external and NHL schedule state; re-evaluate crosswalk append-only; never rewrite prior event binding','current_readiness':'READY_WITH_BOUNDED_LIMITS_DESIGN_ONLY'}; js(game_contract,out/f'nhl_goalie_game_identity_crosswalk_contract_{DATE}.json')
 player_contract={'preferred_binding':'SportsDataIO PlayerID -> repository player_id -> NHL provider_player_id through governed player_external_ids rows','required_source_fields':['PlayerID','TeamID','FirstName','LastName'],'statuses':['EXACT_ID_MATCH','DETERMINISTIC_CROSSWALK','NAME_TEAM_FALLBACK','AMBIGUOUS','UNBOUND'],'certified_statuses':['EXACT_ID_MATCH','DETERMINISTIC_CROSSWALK'],'name_team_policy':'may create a review candidate only; never pregame-qualified identity','crosswalk_creation':'requires exact authoritative NHL player confirmation and preserved evidence; no fuzzy match','team_consistency':'source goalie team must equal bound game side and mapped NHL team','current_readiness':'NOT_READY_NO_SPORTSDATAIO_TO_NHL_CROSSWALK'}; js(player_contract,out/f'nhl_goalie_player_identity_crosswalk_contract_{DATE}.json')
 timestamp_contract={'required_fields':['source','source_game_id','game_id','team_id','goalie_player_id','goalie_status','source_timestamp_utc','capture_timestamp_utc','scheduled_start_time_utc','identity_status','timestamp_status'],'qualification':'source_timestamp_utc present AND capture_timestamp_utc present AND deterministic game binding AND deterministic goalie binding AND source_timestamp_utc < scheduled_start_time_utc AND capture_timestamp_utc < scheduled_start_time_utc','statuses':['NO_PROJECTION','PROJECTED','LIKELY','CONFIRMED','CHANGED_AFTER_CONFIRMATION','UNKNOWN'],'actual_starter_status':'ACTUAL_STARTER_OUTCOME_CONTEXT','actual_starter_policy':'postgame-only separate event; never overwrites pregame state','missing_source_timestamp':'TIMESTAMP_UNCERTIFIED_RETAIN_RAW_EXCLUDE_PREGAME_QUALIFIED','sportsdataio_documentation_result':'StartingGoaltenders documents Confirmed and identities but no Created/Updated/state-change timestamp','current_readiness':'BLOCKED_BY_TIMESTAMP_SEMANTICS'}; js(timestamp_contract,out/f'nhl_goalie_timestamp_certification_contract_{DATE}.json')
 transition={'grain':['canonical_season','game_id','team_id','source','source_timestamp_utc','goalie_status'],'append_only':True,'event_id':'sha256(canonical JSON of grain + source_player_id + raw_payload_sha256)','required_fields':['previous_event_id','previous_goalie_player_id','goalie_player_id','goalie_status','change_reason','source_timestamp_utc','capture_timestamp_utc','raw_payload_sha256'],'deduplication':'same event ID and same payload is idempotent; same event ID with different payload fails closed','transition_examples':[{'source_timestamp_utc':'fixture_12:00Z','goalie_status':'PROJECTED','goalie_name':'Goalie A'},{'source_timestamp_utc':'fixture_16:30Z','goalie_status':'LIKELY','goalie_name':'Goalie A'},{'source_timestamp_utc':'fixture_18:20Z','goalie_status':'CONFIRMED','goalie_name':'Goalie B','previous_goalie_name':'Goalie A'}],'actual_starter_separate':True,'latest_state':'derived view only; never stored by overwriting events','current_readiness':'READY_CONTRACT_ONLY'}; js(transition,out/f'nhl_goalie_state_transition_contract_{DATE}.json')

 cadence=pd.DataFrame([
  ['PRIOR_NIGHT','after documented ~21:00 Eastern projection publication','capture initial PROJECTED state','high for announcements after capture','single snapshot misses overnight changes','requires source access'],['MIDDAY','local midday','capture morning confirmation/news state','medium','late scratches/changes missed','recommended if connected'],['T_MINUS_2_TO_3_HOURS','2-3 hours before scheduled start','capture late likely/confirmed changes','low-to-medium','changes inside final window missed','recommended if rate limit permits'],['FINAL_PREGAME','bounded final run before start','capture latest pregame state','lowest among scheduled snapshots','provider delay or last-minute change still possible','required validation state'],['EVENT_DRIVEN','provider webhook/change feed','not documented for evaluated feed','unknown','cannot recommend without evidence','DEFER'],['SUB_HOUR_RECURRING','less than hourly','not operationally justified by current documentation','unknown','rate/cost burden and still lacks source timestamp','NOT_RECOMMENDED'],
 ],columns=['capture_state','cadence','purpose','late_change_miss_risk','limitation','recommendation']); csv(cadence,out/f'nhl_goalie_polling_cadence_assessment_{DATE}.csv')
 cost=pd.DataFrame([
  ['SportsDataIO','API key; product/account access','commercial trial or paid; exact tier not established','new user authorization for account/subscription, credential provision, approved secret storage, rate-limit confirmation','BLOCKED_BY_SUBSCRIPTION_AND_CREDENTIALS','no purchase or signup performed'],['Official NHL API','none evident','public','none for read-only identity/actual context','READY_NOW','not a projected source'],['Sportradar','API key and trial/production access','commercial','separate approval and credentials','BLOCKED_BY_SUBSCRIPTION_AND_CREDENTIALS','not semantically adequate for projected/confirmed requirement'],['Repository database','SUPABASE_DB_URL already used elsewhere','existing infrastructure','no new authorization for read-only design inspection','READY_NOW','no external projected source data'],
 ],columns=['source','credential_requirement','cost_status','approval_needed','readiness','action_taken']); csv(cost,out/f'nhl_goalie_cost_and_authorization_inventory_{DATE}.csv')
 prototype=pd.DataFrame([
  ['credential_presence_check',True,'variable names checked only; all SportsDataIO/Sportradar keys NOT_CONFIGURED'],['live_fetch_performed',False,'prohibited without credentials/account; no fake payload used'],['sample_parser_created',False,'documentation mapping and contracts only; implementation not authorized'],['production_write_performed',False,'analysis package only'],['purchase_or_signup_performed',False,'none'],['prototype_status',True,'NOT_APPLICABLE_BLOCKED_BY_CREDENTIALS_AND_TIMESTAMP_SEMANTICS'],
 ],columns=['check','passed_or_performed','evidence']); csv(prototype,out/f'nhl_goalie_read_only_prototype_audit_{DATE}.csv')
 archive_fields=['canonical_season','game_id','team_id','goalie_player_id','goalie_name','goalie_status','source','source_game_id','source_player_id','source_timestamp_utc','capture_timestamp_utc','scheduled_start_time_utc','pregame_qualified','identity_status','timestamp_status','notes']
 archive=pd.DataFrame([{'field':f,'existing_context_contract_compatible':True,'required':True,'normalization':{'goalie_status':'controlled enum','source_timestamp_utc':'UTC or null/unqualified','capture_timestamp_utc':'UTC collector time','pregame_qualified':'derived fail-closed boolean','identity_status':'controlled enum','timestamp_status':'QUALIFIED|MISSING|POST_START|UNCERTIFIED'}.get(f,'preserve normalized value'),'overwrite_policy':'APPEND_ONLY_NEVER_UPDATE'} for f in archive_fields]); csv(archive,out/f'nhl_goalie_context_archive_compatibility_{DATE}.csv')
 failure_rows=[
  ['source unavailable','retain failed acquisition event/health status; no fabricated observation','FAIL_CLOSED'],['API timeout','bounded retry only in future authorized collector; archive error metadata','FAIL_CLOSED'],['timestamp missing','preserve raw; TIMESTAMP_UNCERTIFIED; pregame_qualified=false','FAIL_CLOSED'],['duplicate event','idempotent only when event ID and payload hash match','IDEMPOTENT_OR_FAIL'],['goalie changed late','append CHANGED_AFTER_CONFIRMATION/CONFIRMED event; keep earlier states','APPEND_ONLY'],['projected goalie absent','append NO_PROJECTION when source response is authoritative and timestamped','RETAIN_EXPLICIT'],['player ID unknown','UNBOUND; no name-only certification','FAIL_CLOSED'],['team mismatch','retain diagnostic; identity AMBIGUOUS/UNBOUND','FAIL_CLOSED'],['game rescheduled','append schedule/crosswalk revision; reassess all pregame timestamps against revised start','APPEND_ONLY_REQUALIFY'],['postponed game','retain events; no pregame qualification for replacement event without deterministic binding','FAIL_CLOSED'],['source game key changes','explicit supersession edge; never silently replace key','FAIL_CLOSED'],['conflicting projected starters same source','retain both events; order only by certified source timestamp; conflict if tied/missing','FAIL_CLOSED'],['conflicting future sources','keep independent source streams; no automatic priority or merge','SEPARATE_STREAMS'],
 ]; csv(pd.DataFrame(failure_rows,columns=['failure_mode','handling','certification_behavior']),out/f'nhl_goalie_failure_mode_audit_{DATE}.csv')
 preseason="""# NHL Season 2026 Goalie Preseason Validation Plan\n\nPreseason is `PLUMBING_VALIDATION_ONLY`. It may validate official-game binding, provider team/player crosswalks, timestamp presence, projected-to-confirmed transitions, scheduled capture cadence, append-only identity, reschedules, and failure handling. It may not measure champion lift, calibration, ROI, or recommendation quality.\n\nA valid future test requires explicit source access authorization. Run prior-night/MIDDAY, 2–3-hours-pregame, and `FINAL_PREGAME` captures against the same official games. Each response and normalized event must be create-only. Confirm that a goalie change creates a new event, earlier hashes remain unchanged, and actual starter is appended after the game as `ACTUAL_STARTER_OUTCOME_CONTEXT`.\n\nSportsDataIO cannot be timestamp-certified from current documentation alone because the StartingGoaltenders schema does not document a source update timestamp. A credentialed sample/schema confirmation must prove such a field before any observation can become `pregame_qualified`; capture time alone is insufficient.\n"""; (out/f'nhl_goalie_preseason_validation_plan_{DATE}.md').write_text(preseason)
 decisions={'NHL_SEASON_2026_GOALIE_SOURCE_CANDIDATES_IDENTIFIED':'READY','NHL_SEASON_2026_GOALIE_SOURCE_SCHEMA_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_GOALIE_GAME_IDENTITY_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_GOALIE_PLAYER_IDENTITY_READINESS':'NOT_READY','NHL_SEASON_2026_GOALIE_TIMESTAMP_CERTIFICATION_READINESS':'BLOCKED_BY_TIMESTAMP_SEMANTICS','NHL_SEASON_2026_GOALIE_STATE_TRANSITION_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_GOALIE_ARCHIVE_COMPATIBILITY':'READY','NHL_SEASON_2026_GOALIE_POLLING_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_GOALIE_COST_AUTHORIZATION_STATUS':'BLOCKED_BY_SUBSCRIPTION_AND_CREDENTIALS','NHL_SEASON_2026_GOALIE_INTEGRATION_READINESS':'NOT_READY','NHL_SEASON_2026_GOALIE_PRESEASON_VALIDATION_READINESS':'BLOCKED_BY_SOURCE_ACCESS_AND_TIMESTAMP_SEMANTICS','NHL_SEASON_2026_FROZEN_CHAMPION_STATUS':'UNCHANGED'}
 recommendation='NO_SOURCE_READY'; decision={'integration_recommendation':recommendation,'best_documented_candidate':'SportsDataIO Starting Goaltenders by Date','decisions':decisions,'recommended_next_bounded_task':'USER_DECISION_ON_COMMERCIAL_GOALIE_SOURCE_ACCESS_AND_TIMESTAMP_REQUIREMENT','unlocked':['A user decision whether to authorize a SportsDataIO trial/subscription credential solely for one bounded schema/response proof, contingent on confirming a provider source-update timestamp'],'still_blocked':['goalie collector implementation','recurring polling','pregame timestamp certification','player crosswalk activation','goalie model/challenger work','champion changes','ROI','wagering','promotion','automation'],'purchase_performed':False,'credentials_accessed':False,'live_fetch_performed':False,'champion_changed':False,'model_fit_performed':False}; js(decision,out/f'nhl_goalie_source_integration_decision_{DATE}.json')
 report=f"""# NHL Season 2026 Timestamp-Certified Goalie Source Integration Readiness\n\n## Recommendation\n\n`{recommendation}`. SportsDataIO remains the best documented semantic candidate: its NHL workflow states that projected goalies are published around 21:00 Eastern the prior night and updated as news arrives, with confirmations recorded within minutes of announcements. Its `StartingGoaltenders` schema provides vendor GameID, scheduled time, teams, nested goalie PlayerID/name, and a `Confirmed` boolean. It does not document `Created`, `Updated`, or another state-change timestamp on that record. Capture time cannot substitute for source time under the certified contract.\n\nNo SportsDataIO or Sportradar credential is configured. No purchase, signup, secret access, network fetch, parser fiction, or production write occurred. A credentialed response proof might reveal undocumented response metadata, but current evidence cannot assume it. Therefore SportsDataIO is schema-ready with bounded limits, commercially blocked, and not timestamp-certified.\n\nOfficial NHL schedule/gamecenter is the deterministic authority for game/team/player identity and postgame actual starter context, but supplies no projected/confirmed starter state. Repository goalie logs are actual-starter-only; roster collection is current-state-only. Sportradar's documented global lineup feed does not differentiate starter from played and is not a substitute. Arbitrary website scraping is excluded.\n\nThe game crosswalk prefers a maintained external GameID-to-NHL game_id mapping; fallback requires exact mapped teams, source-specific game type, and start within 15 minutes. Player binding requires a governed SportsDataIO PlayerID-to-repository/NHL crosswalk. Name/team fallback never certifies identity. All goalie states are append-only; actual starter remains `ACTUAL_STARTER_OUTCOME_CONTEXT`.\n\nIf source access and a true source timestamp are later proven, practical captures are prior-night, MIDDAY, 2–3 hours pregame, and `FINAL_PREGAME`. Sub-hour polling is not justified. Preseason can validate plumbing only.\n\nPrimary provider documentation: {DOCS['workflow']}, {DOCS['dictionary']}, {DOCS['api']}, and {DOCS['sportradar']}.\n\n## Decisions\n\n"""+'\n'.join(f'- `{k}` = `{v}`' for k,v in decisions.items())+'\n'; (out/f'nhl_season_2026_goalie_source_integration_readiness_report_{DATE}.md').write_text(report); (out/f'nhl_goalie_source_integration_one_page_summary_{DATE}.md').write_text(report)
 assert before=={str(x):sha(x) for p in pp.values() for x in p.iterdir() if x.is_file()}; assert not any(configured.values()); source=Path(__file__).read_text(); forbidden=['url'+'open(','requests'+'.get(','httpx'+'.get(','.fi'+'t(']; assert not any(x in source for x in forbidden); text='\n'.join(x.read_text(errors='ignore') for x in out.iterdir() if x.suffix in {'.md','.json','.csv'}); assert not re.search(r'\b20\d{2}[-–/]20\d{2}\b',text)
 identity={'package_name':'nhl_season_2026_goalie_source_integration_readiness','version':'1.0.0','assessment_date':DATE,'generated_by':str(Path(__file__).relative_to(root)),'canonical_season':2026,'champion_identity':CHAMPION,'champion_prediction_sha256':PRED_SHA,'parent_manifest_sha256':{k:v for k,(_,_,v) in PARENTS.items()},'documentation_sources':DOCS,'credential_status':{k:'NOT_CONFIGURED' for k in configured},'purchase_performed':False,'live_fetch_performed':False,'production_write_performed':False,'model_fit_performed':False,'champion_changed':False,'source_mutation_check':'PASS'}; js(identity,out/f'package_identity_{DATE}.json')
 files=sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'); assert len(files)==17; (out/'SHA256SUMS').write_text(''.join(f'{sha(x)}  {x.name}\n' for x in files)); subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=out,check=True,capture_output=True); print(json.dumps({'output_dir':str(out),'manifest_sha256':sha(out/'SHA256SUMS'),'recommendation':recommendation,'best_candidate':'SportsDataIO','live_fetch_performed':False},indent=2))
if __name__=='__main__': main()
