#!/usr/bin/env python3
"""Design the season 2026 NHL mainline immutable shadow-observation contract."""
from __future__ import annotations
import argparse,hashlib,json,re,subprocess
from pathlib import Path
import pandas as pd

DATE="2026-07-13"; CHAMP="NHL_MONEYLINE_TEAM_SCHEDULE_LOGIT_CONTROL_V1"; CHAMP_HASH="83beb11588f7e7e31919f23be2dea51ff49863954fc9be750509b30a0eff2cda"
PARENTS={"certification":("nhl_moneyline_frozen_baseline_certification","8bb36073fee4f055f399c651f942b8de6eb1bb3b75b96b6112dd9d4af4224cf5"),"challenger_execution":("nhl_moneyline_champion_challenger_execution","162ae2e630d6128de381179beae8c92c819544b0555b8d6ef175a37fc03c54b3")}
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def js(o,p): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+"\n")
def csv(d,p): d.to_csv(p,index=False,lineterminator="\n")
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[3]); ap.add_argument('--output-dir',type=Path); a=ap.parse_args(); root=a.repo_root.resolve(); base=root/'artifacts/analysis/model_development'; out=(a.output_dir or base/f'nhl_season_2026_mainline_prospective_readiness/{DATE}').resolve(); out.mkdir(parents=True,exist_ok=True)
 pp={k:base/s/DATE for k,(s,h) in PARENTS.items()}; before={str(f):sha(f) for p in pp.values() for f in p.iterdir() if f.is_file()}
 for k,p in pp.items(): assert sha(p/'SHA256SUMS')==PARENTS[k][1]; subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=p,check=True,capture_output=True)
 bp=base/f'nhl_moneyline_simple_baseline_process_validation/{DATE}'; pred=bp/f'nhl_moneyline_simple_baseline_control_predictions_{DATE}.csv'; assert sha(pred)==CHAMP_HASH
 champion_spec=json.loads((bp/f'nhl_moneyline_simple_baseline_specification_{DATE}.json').read_text()); coef=pd.read_csv(bp/f'nhl_moneyline_simple_baseline_coefficient_audit_{DATE}.csv'); assert len(coef)==7 and champion_spec['feature_order']==['diff_std_goal_diff_pg','diff_r10_goal_diff_pg','diff_std_shot_diff_pg','diff_days_rest','home_back_to_back','away_back_to_back']
 evidence=[
 ['game_identity_schedule','NHL official schedule API','backend/nhl/scripts/import_schedule_today.py','game_id,startTimeUTC,home/away,gameState; DB upsert','AVAILABLE_NOW','Stable identity path exists; immutable raw response archive still needed','MVP_REQUIRED'],
 ['champion_team_history','Certified team-game summaries and official results','backend/nhl/scripts/build_nhl_moneyline_team_goalie_feature_spine.py','goals,shots,strict-prior rolling rates','AVAILABLE_WITH_MINOR_INTEGRATION','Historical builder proves formulas; prospective as-of builder/parity gate not implemented','MVP_REQUIRED'],
 ['champion_schedule_history','NHL schedule plus repaired date-chain logic','backend/nhl/scripts/remediate_nhl_season_2024_utah_game_dates.py','days rest,back-to-back,chronology','AVAILABLE_WITH_MINOR_INTEGRATION','Prospective strict-prior schedule chain can reuse certified rules','MVP_REQUIRED'],
 ['champion_model_state','Frozen artifact parameters','artifacts/analysis/model_development/nhl_moneyline_simple_baseline_process_validation/2026-07-13','feature order,medians,scaler,coefficients,intercept','AVAILABLE_NOW','Parameter representation is hashable; governed scorer wrapper remains to implement','MVP_REQUIRED'],
 ['mainline_market_source','The Odds API configurable NHL endpoint','backend/nhl/cli.py:fetch_odds','event,commence_time,bookmakers,markets,outcomes,last_update','SOURCE_EXISTS_NOT_CONNECTED','Fetcher accepts configurable markets but defaults to player props and overwrites latest files; h2h immutable lane absent','MVP_REQUIRED'],
 ['mainline_quote_history','No NHL mainline immutable archive','backend/nhl/site/data and backend/nhl/exports/odds_history','current player-prop snapshots only','NOT_AVAILABLE','Must implement append-only h2h snapshots with capture/source timestamps','MVP_REQUIRED'],
 ['active_roster','NHL roster endpoint and roster_status','backend/nhl/scripts/refresh_players_and_roster_today.py','game/team/player,active_flag,asof_ts,optional roles','AVAILABLE_NOW','Current upsert mutates current state and is not an immutable lineup history','MVP_OPTIONAL'],
 ['goalie_projection_confirmation','No connected pregame authority','repository inspection','player/team/game/status/source/source_ts','TIMING_UNCERTIFIED','Goalies exist in rosters/logs, but projected/confirmed starter history and immutable change events do not','PHASE_2'],
 ['injury_scratch_lines','No connected timestamp-certified source','repository inspection','injuries,scratches,lines,pairs,PP units','NOT_AVAILABLE','Roster activity is not equivalent to injury/scratch or line-combination state','PHASE_2'],
 ['official_outcome','NHL schedule/gamecenter plus certified full-game winner logic','backend/nhl/scripts/certify_nhl_full_game_moneyline_population.py','final score,winner,decision type,status','AVAILABLE_WITH_MINOR_INTEGRATION','Prospective grader must append outcome separately and preserve source timestamp/hash','MVP_REQUIRED'],
 ['SOG_shared_infrastructure','Existing independent prop lane','backend/nhl/cli.py and backend/nhl/scripts/build_sog_with_market.py','schedule,teams,raw odds transport','AVAILABLE_NOW','Share transport/identity utilities only; do not share populations or policies','MVP_OPTIONAL'],
 ]
 inventory=pd.DataFrame(evidence,columns=['component','source','repository_evidence','observed_fields_or_behavior','readiness','gap_or_constraint','mvp_class']); csv(inventory,out/f'nhl_season_2026_mainline_source_readiness_inventory_{DATE}.csv')
 runid={"canonical_season":2026,"identity_fields":["canonical_season","slate_date","run_timestamp_utc","run_type"],"canonical_format":"nhlmlobs_s{canonical_season}_d{slate_date_compact}_t{run_timestamp_utc_compact_microseconds}_{run_type}_v1","run_types":{"MIDDAY":"One slate-wide observation after the official daily schedule is loaded; intended to preserve an earlier market state.","FINAL_PREGAME":"Per-game or start-time cohort snapshot targeted 30 minutes before scheduled start; never after start."},"cadence_rationale":"Two states reflect actual source change behavior without multiplying redundant captures: a stable daily schedule/early quote state and a final pregame state for market/goalie changes.","timestamp_standard":"UTC RFC3339 with six fractional digits and Z","collision_policy":"CREATE_NEW_ONLY; exclusive creation fails if run_id or path exists; never update/replace","path_template":"artifacts/observations/nhl/mainline/canonical_season=2026/slate_date={YYYY-MM-DD}/run_id={run_id}/","required_run_metadata":["run_id","run_timestamp_utc","run_type","host_clock_utc","source_versions","source_capture_timestamps","scheduled_start_times","file_sha256","package_sha256"],"late_run_policy":"Any game with run_timestamp_utc >= scheduled_start_time_utc is excluded from pregame populations and recorded POST_START_REJECTED.","immutability":"Every later state creates a new run and source event; earlier files are read-only."}; js(runid,out/f'nhl_season_2026_mainline_run_identity_contract_{DATE}.json')
 fields=[]
 def add(names,category,stage,required,typ,notes):
  for x in names: fields.append([x,category,stage,required,typ,notes])
 add(['canonical_season','slate_date','game_id','game_date','scheduled_start_time_utc','home_team_id','home_team','away_team_id','away_team','game_status'],'game_identity','PREGAME_CAPTURE','REQUIRED','mixed','Official schedule identity; season must equal 2026.')
 add(['run_id','run_timestamp_utc','run_type'],'run_identity','PREGAME_CAPTURE','REQUIRED','text/timestamp','Immutable observation identity.')
 add(champion_spec['feature_order'],'champion_input','PREGAME_CAPTURE','REQUIRED_FOR_POPULATION_A','float/bool','Strict-prior value computed as of run timestamp; exact frozen feature semantics.')
 add(['champion_missingness_status','champion_home_win_probability','champion_away_win_probability','champion_predicted_side','champion_model_sha256'],'champion_output','PREGAME_CAPTURE','REQUIRED_FOR_POPULATION_A','mixed','Frozen scorer only; probabilities complementary.')
 add(['sportsbook','market_type','home_moneyline_american','away_moneyline_american','home_decimal_price','away_decimal_price','quote_timestamp_utc','source_timestamp_utc','market_capture_timestamp_utc','market_status','market_source_id','raw_implied_home_probability','raw_implied_away_probability','overround','devig_home_probability','devig_away_probability','vig_method','market_capture_status'],'market','PREGAME_CAPTURE','REQUIRED_FOR_POPULATION_B','mixed','One record per book quote/snapshot; h2h full game only; never attach post-start quote.')
 add(['home_projected_goalie_id','home_projected_goalie_name','away_projected_goalie_id','away_projected_goalie_name','home_confirmed_goalie_id','home_confirmed_goalie_name','away_confirmed_goalie_id','away_confirmed_goalie_name','goalie_source','goalie_source_timestamp_utc','goalie_capture_timestamp_utc','goalie_certainty'],'goalie','PREGAME_CAPTURE','OPTIONAL_POPULATION_C','mixed','Append-only goalie state; actual starter never rewrites pregame state.')
 add(['lineup_source','lineup_source_timestamp_utc','lineup_capture_timestamp_utc','injury_scratch_summary_json','active_roster_json','projected_lines_json','confirmed_lines_json','defensive_pairs_json','power_play_units_json','lineup_certainty','material_lineup_change'],'lineup','PREGAME_CAPTURE','OPTIONAL_POPULATION_D','mixed','Capture quality explicit; no requirement for champion population.')
 add(['official_final_home_goals','official_final_away_goals','official_full_game_winner','decision_type','grading_timestamp_utc','outcome_source','outcome_source_timestamp_utc','outcome_source_sha256','outcome_conflict_status'],'outcome','POSTGAME_GRADING','POSTGAME_ONLY','mixed','Separate append-only grading record; prohibited in pregame capture payload.')
 add(['execution_evidence_id','execution_side','execution_price','execution_timestamp_utc','execution_source'],'execution','USER_SUPPLIED_ONLY','NEVER_INFER','mixed','Population E only; null without user evidence.')
 csv(pd.DataFrame(fields,columns=['field_name','category','write_stage','requirement','data_type','contract']),out/f'nhl_season_2026_mainline_game_record_contract_{DATE}.csv')
 frozen_state={r.feature_name:{"coefficient":float(r.standardized_coefficient) if r.feature_name!='__INTERCEPT__' else None,"median":float(r.fit_imputation_median) if pd.notna(r.fit_imputation_median) else None,"scaler_mean":float(r.fit_scaler_mean) if pd.notna(r.fit_scaler_mean) else None,"scaler_scale":float(r.fit_scaler_scale) if pd.notna(r.fit_scaler_scale) else None} for _,r in coef.iterrows()}; intercept=float(coef.loc[coef.feature_name.eq('__INTERCEPT__'),'standardized_coefficient'].iloc[0])
 replay={"champion_name":CHAMP,"champion_prediction_sha256":CHAMP_HASH,"specification_sha256":sha(bp/f'nhl_moneyline_simple_baseline_specification_{DATE}.json'),"parameter_state_sha256":sha(bp/f'nhl_moneyline_simple_baseline_coefficient_audit_{DATE}.csv'),"feature_order":champion_spec['feature_order'],"preprocessing":{"imputation":"frozen fit medians","scaling":"(imputed_value - frozen fit mean) / frozen fit scale","state":frozen_state},"intercept":intercept,"probability":"sigmoid(intercept + sum(coefficient_i * scaled_i)); home is class 1; away=1-home","mutation_prohibitions":["no retraining","no online coefficient update","no recalibration","no feature reordering","no missingness amendment"],"prospective_parity_test":{"fixture":"All 2,798 historical matrix-audit rows","expected_prediction_file_sha256":CHAMP_HASH,"maximum_probability_difference":1e-12,"identity_and_order":"canonical_season + game_id exact","required_before_shadow_capture":"PASS"},"season_2026_scoring_status":"IMPLEMENTATION_REQUIRED; contract and state are ready"}; js(replay,out/f'nhl_season_2026_mainline_champion_replay_contract_{DATE}.json')
 price={"market_family":"FULL_GAME_MONEYLINE_INCLUDING_OVERTIME_AND_SHOOTOUT","provider_market_key":"h2h","source_candidate":"The Odds API through a new mainline-only wrapper; do not alter prop defaults","quote_grain":["game_id","sportsbook","market_family","side","quote_timestamp_utc","capture_timestamp_utc"],"required_fields":["provider_event_id","game_id","sportsbook_key","sportsbook_name","market_key","side","american_price","decimal_price","provider_market_last_update_utc","quote_timestamp_utc","source_timestamp_utc","capture_timestamp_utc","scheduled_start_time_utc","market_status","source_url_identity","raw_payload_sha256"],"identity_matching":"Exact normalized home and away identities plus commence_time within 15 minutes of NHL scheduled start; ambiguity fails closed.","snapshot_classes":{"OPENING_OBSERVED":"First valid quote observed per game/book","EARLY_OBSERVED":"Quote preserved by MIDDAY run","LATEST_BEFORE_CHAMPION_PREDICTION":"Maximum valid quote timestamp <= champion run timestamp","LATEST_BEFORE_PUCK_DROP":"Maximum valid quote/capture timestamp < scheduled start","EXECUTION_PRICE":"Only explicit user-supplied execution evidence"},"immutability":"Persist every raw payload and normalized quote append-only. Latest is a derived view, never the only stored state.","timing_rules":{"valid_pregame":"quote_timestamp_utc and capture_timestamp_utc strictly before scheduled_start_time_utc","unknown_provider_timestamp":"retain raw quote but market_capture_status=TIMING_UNCERTIFIED; exclude Population B","post_start":"POST_START_REJECTED","stale":"Flag when quote age exceeds 30 minutes at associated run; retain but exclude latest-at-run qualification unless no qualified status is claimed"},"missing_side":"Preserve available side with INCOMPLETE_TWO_WAY; exclude de-vig and Population B","suspended":"Retain event with SUSPENDED status; do not normalize as active quote","overwrite":"PROHIBITED","current_readiness":"SOURCE_EXISTS_NOT_CONNECTED; immutable h2h capture implementation is required"}; js(price,out/f'nhl_season_2026_mainline_price_capture_contract_{DATE}.json')
 vig={"method":"PROPORTIONAL_TWO_WAY_NORMALIZATION_V1","american_to_decimal":{"positive":"1 + american/100","negative":"1 + 100/abs(american)","zero":"INVALID"},"raw_implied_probability":"1 / decimal_price","overround":"raw_home + raw_away - 1","devig_home":"raw_home / (raw_home + raw_away)","devig_away":"raw_away / (raw_home + raw_away)","requirements":["exactly one active home and away outcome from same book/market snapshot","positive decimal prices","timestamps valid pregame"],"edge_cases":{"missing_side":"NO_DEVIG_INCOMPLETE_TWO_WAY","duplicate_side":"AMBIGUOUS_REJECT","suspended":"NO_DEVIG_SUSPENDED","stale":"COMPUTE_AND_FLAG_STALE; exclude qualified comparison","nonpositive_overround":"COMPUTE but flag NONPOSITIVE_OVERROUND","post_start":"REJECT_FROM_PREGAME"},"separation":"Champion probability and de-vig market probability remain distinct; never overwrite either.","optimization":"Method frozen before observation; no performance-based selection."}; js(vig,out/f'nhl_season_2026_mainline_vig_policy_{DATE}.json')
 goalie={"event_identity":["canonical_season","game_id","team_id","goalie_player_id","source_timestamp_utc","capture_timestamp_utc"],"statuses":["NO_PROJECTION","PROJECTED","LIKELY","CONFIRMED","CHANGED_AFTER_CONFIRMATION","UNKNOWN"],"required_update_fields":["game_id","team_id","goalie_player_id","goalie_name","source","source_record_id","source_timestamp_utc","capture_timestamp_utc","status","confidence","previous_event_identity","raw_payload_sha256"],"append_only":True,"change_policy":"Every change creates a new event pointing to the previous event. CHANGED_AFTER_CONFIRMATION never mutates CONFIRMED.","actual_starter_policy":"Postgame actual starter is a separate grading/context fact and cannot rewrite any pregame event.","valid_pregame":"Both source and capture timestamps strictly precede scheduled start.","current_sources":{"active_roster":"AVAILABLE_NOW but does not establish starter","projected_or_confirmed_starter":"TIMING_UNCERTIFIED; no connected immutable source"},"mvp":"OPTIONAL; absence does not fail champion/market snapshot","readiness":"BLOCKED_BY_PREGAME_GOALIE_SOURCE_INTEGRATION"}; js(goalie,out/f'nhl_season_2026_mainline_goalie_capture_contract_{DATE}.json')
 lineup={"event_identity":["canonical_season","game_id","team_id","source_timestamp_utc","capture_timestamp_utc","source_record_id"],"capture_fields":["injured_players","scratches","active_roster","projected_lines","confirmed_lines","defensive_pairs","power_play_units","material_lineup_change","source","source_timestamp_utc","capture_timestamp_utc","raw_payload_sha256"],"quality":["NO_SOURCE","ROSTER_ONLY","PARTIAL_PROJECTED","PROJECTED_COMPLETE","CONFIRMED_PARTIAL","CONFIRMED_COMPLETE","TIMING_UNCERTIFIED"],"append_only":True,"current_state":{"active_roster":"AVAILABLE_NOW","injury_scratch":"NOT_AVAILABLE","line_combinations":"NOT_AVAILABLE","timestamp_certification":"TIMING_UNCERTIFIED"},"mvp":"OPTIONAL; missing context is explicit and does not fail Population A/B","material_change":"Deterministic comparison with immediately preceding same-source pregame event; preserve both states","readiness":"BLOCKED_BY_TIMESTAMPED_LINEUP_INJURY_SOURCE"}; js(lineup,out/f'nhl_season_2026_mainline_lineup_capture_contract_{DATE}.json')
 populations=pd.DataFrame([
 ['A_CHAMPION_PREDICTION','Every scheduled game with deterministic identity and all six strict-prior champion inputs or frozen missingness support','game_id unique per run; champion hash/parity pass; run before start','Market,goalie,lineup may be absent','Prediction quality'],['B_MARKET_QUALIFIED','Population A row with active two-sided h2h quote certified before associated run/start','same game/book snapshot; both sides; timestamp certified','Incomplete,stale,post-start,suspended excluded','Market-relative quality; never execution'],['C_GOALIE_CONTEXT','Population A row with valid projected/likely/confirmed goalie event before start','source and capture timestamps pre-start','NO_PROJECTION/UNKNOWN excluded from qualified subset but retained','Goalie context characterization'],['D_LINEUP_CONTEXT','Population A row with timestamped roster/lineup/injury event','quality and source timestamp explicit','NO_SOURCE retained outside qualified subset','Lineup context characterization'],['E_EXECUTION','Population B row with explicit user-supplied execution evidence','execution ID,side,price,timestamp,source required','Never inferred from recommendation or market snapshot','Execution-only evaluation'],
 ],columns=['population','inclusion','required_gates','exclusion_or_retention','allowed_evaluation']); csv(populations,out/f'nhl_season_2026_mainline_population_contracts_{DATE}.csv')
 outcome={"target":"home_win_target","definition":{"1":"official home full-game winner including overtime/shootout","0":"official away full-game winner including overtime/shootout"},"source_priority":["NHL official gamecenter/boxscore final","NHL official schedule final state"],"required_fields":["canonical_season","game_id","official_final_home_goals","official_final_away_goals","regulation_home_goals","regulation_away_goals","decision_type","official_full_game_winner","home_win_target","grading_timestamp_utc","source_timestamp_utc","source_uri_identity","raw_source_sha256","outcome_conflict_status"],"append_policy":"Write a separate grading record linked to immutable run/game rows. No UPDATE to pregame snapshot payloads.","eligibility":"Grade only authoritative final, decisive scores; pending/conflict rows remain ungraded.","conflict":"Conflicting authorities set CONFLICT_REVIEW_REQUIRED; no metric contribution until resolved with lineage.","separation_assertion":"Outcome fields prohibited from pregame capture schema and champion feature computation.","readiness":"AVAILABLE_WITH_MINOR_INTEGRATION"}; js(outcome,out/f'nhl_season_2026_mainline_outcome_grading_contract_{DATE}.json')
 evaluation="""# NHL Season 2026 Mainline Prospective Evaluation Plan\n\nEvaluation is descriptive and population-specific. Population A supports accuracy, Brier score, log loss, ROC AUC, fixed-bucket calibration, ECE, mean probability, and observed home-win rate. Population B additionally supports champion probability minus proportional-de-vig market probability, model/market direction agreement, and movement from the earliest observed quote to the latest certified pre-puck-drop quote.\n\nPopulation C characterizes results by projected, likely, confirmed, changed, and unknown goalie states. Population D characterizes capture quality and material lineup changes. These context analyses do not authorize feature fitting. Population E alone may later support execution-return calculations, and only from user-supplied execution price evidence. Market snapshots must never be treated as execution.\n\nNo betting threshold, candidate filter, ROI claim, recalibration, or champion retraining is defined here. Review prediction quality and capture completeness separately after a minimum of 200 graded Population A games and at least 60 calendar days of shadow observation; this is a review trigger, not a promotion threshold.\n"""; (out/f'nhl_season_2026_mainline_evaluation_plan_{DATE}.md').write_text(evaluation)
 mvp=pd.DataFrame([
 ['official_schedule_game_identity','MVP_REQUIRED','AVAILABLE_NOW','Implement immutable raw schedule snapshot'],['six_strict_prior_champion_inputs','MVP_REQUIRED','AVAILABLE_WITH_MINOR_INTEGRATION','Implement prospective as-of feature builder and historical parity fixture'],['frozen_champion_probability','MVP_REQUIRED','AVAILABLE_WITH_MINOR_INTEGRATION','Implement parameter-only scorer bound to frozen hashes'],['timestamped_h2h_prices','MVP_REQUIRED','SOURCE_EXISTS_NOT_CONNECTED','Implement mainline-only immutable Odds API capture'],['immutable_run_archive','MVP_REQUIRED','NOT_IMPLEMENTED','Implement create-only run directory, metadata, and hashes'],['postgame_outcome_reconciliation','MVP_REQUIRED','AVAILABLE_WITH_MINOR_INTEGRATION','Implement append-only official final grader'],['goalie_state','MVP_OPTIONAL','TIMING_UNCERTIFIED','Phase 2 source integration; absence explicit'],['lineup_injury_state','PHASE_2','NOT_AVAILABLE','Integrate timestamped source without blocking MVP'],['wager_recommendations','DEFER','NOT_AUTHORIZED','Prohibited in shadow mode'],['execution_automation','DEFER','NOT_AUTHORIZED','Prohibited'],
 ],columns=['component','mvp_class','current_readiness','required_next_action']); csv(mvp,out/f'nhl_season_2026_mainline_mvp_scope_{DATE}.csv')
 workflow=pd.DataFrame([
 [1,'schedule_acquisition','EXISTING_ADAPTABLE','SLATE_DATE=<date> .venv/bin/python backend/nhl/scripts/import_schedule_today.py','Fetch/upsert official schedule; implementation must additionally archive raw immutable source','Automated after later authorization'],[2,'feature_preparation','TO_IMPLEMENT','python -m backend.nhl.scripts.build_mainline_observation --stage features --slate-date <date> --run-type <type>','Construct six strict-prior inputs as of run timestamp','Automated after implementation'],[3,'champion_scoring','TO_IMPLEMENT','python -m backend.nhl.scripts.build_mainline_observation --stage score --run-id <run_id>','Load frozen parameter state and emit probability with parity/hash checks','Automated after implementation'],[4,'mainline_odds_capture','EXISTING_TRANSPORT_NEW_WRAPPER_REQUIRED','python -m backend.nhl.scripts.capture_mainline_h2h --run-id <run_id>','Call Odds API h2h only; archive raw and normalized append-only quotes','Automated after implementation'],[5,'goalie_lineup_capture','PHASE_2_MANUAL_OR_SOURCE_DEPENDENT','python -m backend.nhl.scripts.capture_mainline_context --run-id <run_id>','Append available context events; optional absence reported','Manual until source certified'],[6,'snapshot_packaging','TO_IMPLEMENT','python -m backend.nhl.scripts.finalize_mainline_observation --run-id <run_id>','Create-only archive, metadata, hashes, coverage summary','Automated after implementation'],[7,'integrity_validation','TO_IMPLEMENT','python -m backend.nhl.scripts.validate_mainline_observation --run-id <run_id>','Run health gates; fail closed on critical violations','Automated after implementation'],[8,'postgame_grading','EXISTING_LOGIC_NEW_WRAPPER_REQUIRED','python -m backend.nhl.scripts.grade_mainline_observations --slate-date <date>','Append official outcomes without modifying pregame records','Automated after implementation'],
 ],columns=['order','stage','repository_status','planned_command','contract','operation_mode']); csv(workflow,out/f'nhl_season_2026_mainline_daily_workflow_map_{DATE}.csv')
 gates={"critical_fail_closed":[{"gate":"schedule_loaded","rule":"at least one official game or explicit NO_GAMES slate authority"},{"gate":"unique_game_identity","rule":"canonical_season + game_id unique within run"},{"gate":"start_time_valid","rule":"scheduled_start_time_utc parseable and later than pregame run"},{"gate":"strict_prior_features","rule":"all source events precede target game start; no target game contribution"},{"gate":"champion_identity","rule":"specification and parameter hashes exact; historical parity max difference <= 1e-12"},{"gate":"probability_semantics","rule":"finite 0<=home<=1 and abs(home+away-1)<=1e-12"},{"gate":"market_timing","rule":"Population B quote/source/capture timestamps strictly before start"},{"gate":"immutable_output","rule":"create-only path and complete SHA256 manifest"}],"bounded_noncritical":[{"gate":"market_coverage","behavior":"Report missing/incomplete books; game remains Population A"},{"gate":"goalie_coverage","behavior":"Record NO_PROJECTION/UNKNOWN; do not fail slate"},{"gate":"lineup_coverage","behavior":"Record NO_SOURCE/quality; do not fail slate"}],"post_start":"Any contaminated market/context record rejected from pregame-qualified population and logged; identity/model contamination fails entire run.","health_output":"machine-readable gate ledger plus coverage counts and manifest","production_write":"No recommendation, candidate, wager, or execution table writes permitted in shadow implementation."}; js(gates,out/f'nhl_season_2026_mainline_health_gate_contract_{DATE}.json')
 shadow={"mode":"SHADOW_OBSERVATION_ONLY","allowed":["generate frozen champion probabilities","capture immutable timestamped prices","capture optional goalie/lineup context","append later official grades","compute descriptive prediction/market/context quality"],"prohibited":["wager recommendation","candidate selection","automatic execution","champion retraining","recalibration","threshold optimization","frontend behavior change","production promotion"],"review_trigger":{"minimum_graded_population_A_games":200,"minimum_calendar_days":60,"required_before_review":["capture completeness report","timestamp contamination audit","champion parity pass history","prediction/calibration report","Population B coverage report"],"meaning":"Triggers governance review only; does not authorize promotion."},"start_authorization":"Separate shadow-capture implementation and then explicit job-enablement authorization required.","mode_label_required_on_every_output":True}; js(shadow,out/f'nhl_season_2026_mainline_shadow_mode_contract_{DATE}.json')
 sog="""# SOG Lane Boundary\n\nThe NHL player shots-on-goal lane remains independent. Mainline observation must not replace or disable SOG jobs, share player-prop candidate policies, merge player/game populations, reuse thresholds, or write into SOG recommendation/execution outputs.\n\nShared infrastructure is limited to official schedule/team identity, raw HTTP/odds transport patterns, timestamp utilities, immutable archive conventions, and generic hashing/health-check helpers. Mainline uses game-level `h2h`; SOG uses player-level proposition markets. Each lane keeps separate run IDs, schemas, health ledgers, grading populations, and governance decisions.\n"""; (out/f'nhl_season_2026_mainline_sog_lane_boundary_{DATE}.md').write_text(sog)
 decisions={"NHL_SEASON_2026_MAINLINE_GAME_IDENTITY_READINESS":"READY","NHL_SEASON_2026_MAINLINE_CHAMPION_REPLAY_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_MAINLINE_PRICE_CAPTURE_READINESS":"BLOCKED_BY_IMMUTABLE_H2H_CAPTURE_IMPLEMENTATION","NHL_SEASON_2026_MAINLINE_PRICE_TIMESTAMP_READINESS":"BLOCKED_BY_MAINLINE_TIMESTAMP_PERSISTENCE","NHL_SEASON_2026_MAINLINE_GOALIE_CAPTURE_READINESS":"BLOCKED_BY_PREGAME_GOALIE_SOURCE_INTEGRATION","NHL_SEASON_2026_MAINLINE_LINEUP_CAPTURE_READINESS":"BLOCKED_BY_TIMESTAMPED_LINEUP_INJURY_SOURCE","NHL_SEASON_2026_MAINLINE_OUTCOME_GRADING_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_MAINLINE_MVP_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_MAINLINE_HEALTH_GATE_READINESS":"READY","NHL_SEASON_2026_MAINLINE_SHADOW_OBSERVATION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_MAINLINE_WAGER_RECOMMENDATION_READINESS":"NOT_READY","NHL_SEASON_2026_MAINLINE_OPERATIONAL_RESTART_READINESS":"SHADOW_ONLY"}
 decision={"decisions":decisions,"recommended_next_bounded_task":"NHL_SEASON_2026_MAINLINE_PROSPECTIVE_SHADOW_CAPTURE_IMPLEMENTATION","unlocked":["Implementation, but not job enablement or wagering, of the contracted season 2026 mainline shadow-capture path"],"still_blocked":["historical odds backfill","challenger fitting","model promotion","wager recommendations","automated execution","unattended job enablement","frontend changes"],"mode":"SHADOW_OBSERVATION_ONLY"}; js(decision,out/f'nhl_season_2026_mainline_prospective_readiness_decision_{DATE}.json')
 report=f"""# NHL Season 2026 Mainline Prospective Readiness\n\n## Decision\n\nSeason 2026 mainline observation is `READY_WITH_BOUNDED_LIMITS` for a separately authorized implementation in `SHADOW_OBSERVATION_ONLY`. Game identity is ready. Champion parameters and parity evidence are frozen, but a governed prospective scorer wrapper is not implemented. The Odds API transport can request `h2h`, but the current NHL path defaults to player props, overwrites latest files, and does not preserve an immutable mainline quote history.\n\nGoalie roster identity exists without a certified projected/confirmed-starter source. Active roster plumbing exists, but injuries, scratches, line combinations, and immutable timing are not connected. These remain optional/Phase 2 and do not block the MVP.\n\n## MVP\n\nThe MVP requires official game identity, six strict-prior champion inputs, frozen probability, timestamped two-sided full-game moneyline quotes, create-only run archives, health manifests, and append-only outcome grading. Runs are limited to `MIDDAY` and `FINAL_PREGAME`; every later state creates a new run.\n\nMarket normalization is proportional two-way de-vig. Raw prices, implied probabilities, overround, and normalized probabilities remain separate from champion probabilities. Execution is never inferred.\n\n## Workflow and governance\n\nImplementation should adapt the existing schedule importer and Odds API transport behind new mainline-only wrappers, then add feature preparation, frozen scoring, packaging, validation, and grading commands shown in the workflow map. No command is enabled here. Corrupt identity, model/hash mismatch, feature leakage, probability invalidity, post-start attachment, or overwrite attempts fail closed. Missing optional goalie/lineup context does not fail the slate.\n\nThe SOG lane remains independent at player-prop grain. Only transport, schedule identity, timestamps, and hashing conventions may be shared.\n\nThe single next bounded task is **NHL season 2026 mainline prospective shadow-capture implementation**. Wagering, recommendations, promotion, automated execution, unattended jobs, and frontend changes remain unauthorized.\n"""; (out/f'nhl_season_2026_mainline_prospective_one_page_summary_{DATE}.md').write_text(report); (out/f'nhl_season_2026_mainline_prospective_readiness_report_{DATE}.md').write_text(report+'\n## Required decisions\n\n'+'\n'.join(f'- `{k}` = `{v}`' for k,v in decisions.items())+'\n')
 # Run-id format collision exercise: distinct timestamp microseconds and type must remain distinct.
 fmt=lambda ts,t:f"nhlmlobs_s2026_d20261010_t{ts}_{t}_v1"; ids={fmt('20261010T160000000000Z','MIDDAY'),fmt('20261010T160000000001Z','MIDDAY'),fmt('20261010T160000000000Z','FINAL_PREGAME')}; assert len(ids)==3 and all(re.fullmatch(r'nhlmlobs_s2026_d\d{8}_t\d{8}T\d{12}Z_(MIDDAY|FINAL_PREGAME)_v1',x) for x in ids)
 assert before=={str(f):sha(f) for p in pp.values() for f in p.iterdir() if f.is_file()}
 pkg={"package_name":"nhl_season_2026_mainline_prospective_readiness","version":"1.0.0","as_of_date":DATE,"canonical_season":2026,"generated_by":str(Path(__file__).relative_to(root)),"champion":CHAMP,"champion_prediction_sha256":CHAMP_HASH,"mode":"SHADOW_OBSERVATION_ONLY","production_writes":False,"jobs_enabled":False,"parent_manifest_sha256":{k:h for k,(_,h) in PARENTS.items()},"run_identity_collision_test":"PASS","source_mutation_check":"PASS"}; js(pkg,out/f'package_identity_{DATE}.json')
 files=sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'); (out/'SHA256SUMS').write_text(''.join(f'{sha(x)}  {x.name}\n' for x in files)); print(json.dumps({"output_dir":str(out),"shadow_readiness":decisions['NHL_SEASON_2026_MAINLINE_SHADOW_OBSERVATION_READINESS'],"manifest_sha256":sha(out/'SHA256SUMS'),"production_writes":False},indent=2))
if __name__=='__main__': main()
