#!/usr/bin/env python3
"""Package the authorized NHL morning LaunchAgent activation evidence."""
from pathlib import Path
import csv,hashlib,json
D="2026-08-10";R=Path(__file__).resolve().parents[3];O=R/f"artifacts/analysis/model_development/nhl_season_2026_morning_launchagent_activation/{D}"
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 O.mkdir(parents=True,exist_ok=False)
 def j(n,x):(O/n).write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
 def c(n,rows):
  fs=list(dict.fromkeys(k for r in rows for k in r))
  with (O/n).open("x",newline="") as f:w=csv.DictWriter(f,fieldnames=fs);w.writeheader();w.writerows(rows)
 jobs=[
 ("com.proppadia.mlb.bvp.prewarm.daily","03:30","/Users/jerrystrain/bin/proppadia_mlb_bvp_prewarm.sh","loaded/enabled","~30-60m; some anomalous longer/missing DONE","PostgreSQL MLB schema; MLB/Odds APIs","artifacts/ops/mlb_bvp_prewarm_daily.*.log"),
 ("com.proppadia.mlb.dh-forward-capture","every 600s",".venv/bin/python -m backend.mlb.scripts.run_mlb_dh_forward_capture","loaded/enabled","short polling","MLB Stats API; league-isolated artifacts","artifacts/ops/mlb_dh_forward_capture.*.log"),
 ("com.proppadia.mlb.dh-forward-grade","08:15",".venv/bin/python -m backend.mlb.scripts.run_mlb_dh_forward_grade","loaded/enabled","short","MLB artifacts","artifacts/ops/mlb_dh_forward_grade.*.log"),
 ("com.proppadia.mlb.refresh.daily","05:30,08:30,11:00,13:00,16:30","/Users/jerrystrain/bin/proppadia_mlb_refresh_daily.sh","loaded/enabled","08:00 run observed ~22m; resource-heavy","shared PostgreSQL server, MLB schema; several APIs","artifacts/ops/mlb_refresh_daily.*.log"),
 ("com.proppadia.mlb.starter-skill-workload.daily","11:20,13:20",".venv/bin/python -m backend.mlb.scripts.run_mlb_starter_skill_workload_daily_research --mode dry_run --latest-view","loaded","short/research","MLB API and artifacts","artifacts/ops/mlb_starter_skill_workload_daily.*.log"),
 ("com.proppadia.pregame-lineup-study.20260708/09","every 300s fixed historical dates",".venv/bin/python -m backend.mlb.scripts.run_pregame_lineup_availability_study","loaded","short polling","MLB API; MLB-only artifacts","artifacts/analysis/mlb/pregame_lineup_capture/logs"),
 ("com.proppadia.mlb.retrain.weekly","Tue 23:05","/Users/jerrystrain/bin/proppadia_mlb_retrain_weekly.sh","installed not loaded","potentially expensive","MLB DB/model paths","artifacts/ops/mlb_retrain_weekly.*.log")]
 c(f"mlb_launchagent_overlap_inventory_{D}.csv",[{"label":a,"cadence":b,"program_arguments":d,"state":e,"observed_runtime":f,"resources":g,"logs":h} for a,b,d,e,f,g,h in jobs])
 resources=[("database","same PostgreSQL/database; separate mlb and nhl schemas","SHARED_RESOURCE_BOUNDED_RISK","connection/lock pressure possible; no shared league tables found"),("CPU/memory","same host and venv","SHARED_RESOURCE_BOUNDED_RISK","MLB refresh and nonempty NHL history/feature preparation can both be expensive"),("disk","backend/mlb + artifacts/analysis/mlb versus backend/nhl + artifacts/operational/nhl","NO_SHARED_RESOURCE","paths, logs, locks and run IDs are league-scoped"),("network","separate official league APIs; shared host network","SHARED_RESOURCE_LOW_RISK","NHL morning does not use Odds API or market credentials"),("environment","same venv and backend/.env","SHARED_RESOURCE_LOW_RISK","separate processes; secrets read-only; absolute paths hardened")]
 c(f"mlb_nhl_shared_resource_audit_{D}.csv",[{"domain":a,"finding":b,"classification":d,"risk":e} for a,b,d,e in resources])
 risks=[("MLB 08:15 grade vs NHL 08:00 nonempty","SHOULD_NOT_RUN_CONCURRENTLY","unknown preseason NHL duration; avoidable"),("MLB 08:30 daily vs NHL 08:00 nonempty","SHOULD_NOT_RUN_CONCURRENTLY","large MLB job uses DB/CPU/network"),("MLB 03:30 prewarm vs NHL 07:30","SHARED_RESOURCE_LOW_RISK","observed prewarm normally finished by ~04:30; monitor anomalies"),("MLB polling jobs vs NHL","SHARED_RESOURCE_LOW_RISK","short, league-isolated"),("PostgreSQL schemas","SHARED_RESOURCE_BOUNDED_RISK","same server/pool but separate league tables; watch connection/lock errors")]
 c(f"mlb_nhl_concurrency_risk_audit_{D}.csv",[{"overlap":a,"classification":b,"evidence":d} for a,b,d in risks])
 timing=[("03:30","MLB BvP prewarm","typically ends 04:00-04:30; some anomalous logs","no expected 07:30 overlap"),("05:30","MLB daily refresh","typically completes well before 07:30","low"),("07:30","NHL morning","selected final cadence","staggered"),("08:15","MLB DH grade","45-minute separation","bounded monitor"),("08:30","MLB daily refresh","60-minute separation","bounded monitor")]
 c(f"mlb_nhl_launchagent_timing_audit_{D}.csv",[{"local_time":a,"job":b,"runtime_evidence":d,"overlap_status":e} for a,b,d,e in timing])
 c(f"mlb_nhl_concurrency_validation_{D}.csv",[{"test":"parallel MLB --check and exact NHL morning","mlb_exit":1,"nhl_exit":0,"elapsed_seconds":1,"db_or_connection_errors":0,"output_contamination":0,"interpretation":"MLB exit was its pre-existing missing rollover readiness artifact, not contention","status":"PASS_WITH_BOUNDED_LIMITS"},{"test":"installed NHL job MLB artifact list hash","before":"1fd1a33404bd39ef3ced95b488a2027cd115009e05ed33d8afc804d9389b7c1b","after":"1fd1a33404bd39ef3ced95b488a2027cd115009e05ed33d8afc804d9389b7c1b","status":"PASS"}])
 j(f"nhl_morning_activation_timing_decision_{D}.json",{"NHL_MORNING_FINAL_ACTIVATION_TIME":"07:30 local","decision":"STAGGER_NHL","rationale":"08:00 could overlap enabled 08:15 grade and 08:30 resource-heavy refresh; 07:30 provides 45/60 minute separation and follows normal 03:30 prewarm completion","review":"preserve real preseason runtimes before any later timing change"})
 c(f"nhl_morning_launchagent_installation_audit_{D}.csv",[{"item":"template/install","expected":str(R/"backend/nhl/launchagents/com.proppadia.nhl.morning-orchestration.plist"),"observed":"/Users/jerrystrain/Library/LaunchAgents/com.proppadia.nhl.morning-orchestration.plist","status":"PASS"},{"item":"label","expected":"com.proppadia.nhl.morning-orchestration","observed":"loaded gui/501","status":"PASS"},{"item":"cadence","expected":"07:30","observed":"Hour=7 Minute=30","status":"PASS"},{"item":"enabled","expected":"true","observed":"launchctl enabled","status":"PASS"},{"item":"secrets","expected":"none in plist","observed":"backend/.env runtime reference only","status":"PASS"}])
 c(f"nhl_morning_launchagent_runtime_validation_{D}.csv",[{"invocation":"launchctl kickstart -k gui/501/com.proppadia.nhl.morning-orchestration","run_id":"20260810T210101.702000Z_5f7c7c93","exit_code":0,"result":"VALID_EMPTY_SLATE","games":0,"blocking_failure":"none","launchctl_runs":1,"logs":"stdout health path; stderr empty","unauthorized_downstream":"none","status":"PASS"}])
 isolation=[("outputs","backend/nhl + artifacts/operational/nhl/morning","backend/mlb + artifacts/analysis/mlb","PASS"),("locks","artifacts/operational/nhl/morning/locks/<date>.lock","artifacts/ops/locks/mlb-*.lock","PASS"),("logs","nhl/morning/launchagent.*.log","artifacts/ops/mlb_*.log","PASS"),("run identity","NHL morning date/run UUID","MLB local_daily tags","PASS"),("database","nhl schema","mlb schema","PASS_WITH_SHARED_SERVER_LIMIT")]
 c(f"nhl_morning_cross_league_isolation_audit_{D}.csv",[{"domain":a,"nhl":b,"mlb":d,"status":e} for a,b,d,e in isolation])
 rec=f"""# NHL morning LaunchAgent recovery commands\n\nStatus:\n```bash\nlaunchctl print gui/$(id -u)/com.proppadia.nhl.morning-orchestration\nlaunchctl print-disabled gui/$(id -u) | grep com.proppadia.nhl.morning-orchestration\n```\n\nManual dated run:\n```bash\n.venv/bin/python backend/nhl/scripts/run_nhl_morning_orchestration.py --slate-date YYYY-MM-DD --env-file backend/.env\n```\n\nKick installed job once:\n```bash\nlaunchctl kickstart -k gui/$(id -u)/com.proppadia.nhl.morning-orchestration\n```\n\nDisable and unload:\n```bash\nlaunchctl disable gui/$(id -u)/com.proppadia.nhl.morning-orchestration\nlaunchctl bootout gui/$(id -u)/com.proppadia.nhl.morning-orchestration\n```\n\nRe-enable and load:\n```bash\nlaunchctl enable gui/$(id -u)/com.proppadia.nhl.morning-orchestration\nlaunchctl bootstrap gui/$(id -u) "$HOME/Library/LaunchAgents/com.proppadia.nhl.morning-orchestration.plist"\n```\n""";(O/f"nhl_morning_launchagent_recovery_commands_{D}.md").write_text(rec)
 policy="""# NHL/MLB concurrency operating policy\n\nMLB and NHL can generally run concurrently for short, league-isolated reads and API polling. They share a host, venv, PostgreSQL server/pool, and network, so large MLB refreshes and a nonempty NHL history/feature run should be staggered. NHL runs at 07:30, ahead of MLB 08:15/08:30 jobs. Watch for PostgreSQL connection exhaustion, lock waits, timeouts, sustained CPU/memory pressure, and stage-duration growth. Each league has separate schemas, files, locks, health, logs, and run identities; one league failure does not authorize or block the other. During preseason preserve overlap windows and stage runtimes, and do not change cadence automatically from one slow run.\n""";(O/f"nhl_morning_concurrency_operating_policy_{D}.md").write_text(policy)
 dec={"MLB_NHL_LAUNCHAGENT_CONCURRENCY_RISK":"SHARED_RESOURCE_BOUNDED_RISK","MLB_NHL_DATABASE_CONCURRENCY_READINESS":"READY_WITH_STAGGERING","MLB_NHL_FILESYSTEM_ISOLATION":"READY","MLB_NHL_API_CONCURRENCY_READINESS":"READY","MLB_NHL_MORNING_TIMING_OVERLAP_STATUS":"STAGGERED","NHL_MORNING_FINAL_ACTIVATION_TIME":"07:30 local","NHL_MORNING_LAUNCHAGENT_INSTALLED":"YES","NHL_MORNING_LAUNCHAGENT_LOADED":"YES","NHL_MORNING_LAUNCHAGENT_ENABLED":"YES","NHL_MORNING_INSTALLED_JOB_RUNTIME_VALIDATION":"PASS_VALID_EMPTY_SLATE","NHL_MORNING_CROSS_LEAGUE_ISOLATION":"READY","NHL_SEASON_2026_LOCAL_MORNING_AUTOMATION_READINESS":"READY_WITH_PRESEASON_MONITORING"};j(f"nhl_morning_launchagent_activation_decision_{D}.json",dec)
 report=f"""# NHL morning LaunchAgent activation\n\nThe authorized `com.proppadia.nhl.morning-orchestration` LaunchAgent is installed, loaded, enabled, and scheduled for 07:30 local. The time was staggered from the provisional 08:00 because enabled MLB jobs start at 08:15 and 08:30; MLB's 03:30 prewarm normally ends well before 07:30. Shared host, database server/pool, venv, and network create bounded capacity risk, while schemas, outputs, locks, health records, logs, and run identities are isolated.\n\nA bounded parallel test produced NHL exit 0 with no contention errors; the MLB check's exit 1 was its own pre-existing missing readiness artifact. The installed launchd kickstart then exited 0 and created `VALID_EMPTY_SLATE` run `20260810T210101.702000Z_5f7c7c93`; monitored MLB artifact identity was unchanged. No market, prediction, candidate, upload, MIDDAY, or FINAL_PREGAME work ran. Preserve runtime/overlap/DB evidence during first real preseason runs.\n""";(O/f"nhl_morning_launchagent_activation_report_{D}.md").write_text(report)
 j(f"nhl_morning_launchagent_activation_package_identity_{D}.json",{"package":"nhl_season_2026_morning_launchagent_activation","version":"1.0.0","canonical_season":2026,"as_of_date":D,"generated_at_utc":"2026-08-10T21:05:00Z","parent_manifest_sha256":"4747e2a28c937ca1b3438789d8563cd406cb090cb547042c52364cdc240cb3dd","installed_plist_sha256":sh(Path.home()/"Library/LaunchAgents/com.proppadia.nhl.morning-orchestration.plist"),"artifact_count_excluding_manifest":14})
 fs=sorted(O.iterdir());(O/"SHA256SUMS").write_text("".join(f"{sh(p)}  {p.name}\n" for p in fs));print(O)
if __name__=="__main__":main()
