#!/usr/bin/env python3
"""Deterministic, outcome-blind multi-day NHL operational state burn-in."""
from __future__ import annotations
import argparse,csv,hashlib,json
from collections import defaultdict,deque
from datetime import date,timedelta
from pathlib import Path
from backend.nhl.analysis_package_guard import begin_package,finalize_package,verify_manifest

ROOT=Path(__file__).resolve().parents[3];D="2026-08-10";TARGET=ROOT/f"artifacts/analysis/model_development/nhl_season_2026_multiday_operational_burn_in/{D}"
PARENTS=[("hostile","nhl_season_2026_hostile_end_to_end_readiness/2026-08-10","d78ae42ff03d8d439f977d13b7fed5f37a83b16e59260850d85c37eaad7ae9e2"),("immutability","nhl_analysis_package_immutability_remediation/2026-08-10","d3f2c0b5012b331d913218072f923934564a31f1613e391a1ac20793eeabd1d8"),("untracked closure","nhl_untracked_script_integrity_closure/2026-08-10","8e69987458e0604d97ae9cea1637df74083307a3f4ca95c051a85a47dfa2eb35"),("mainline","nhl_season_2026_mainline_shadow_capture_implementation/2026-07-13","62de5b047b0121664ede00ce197b339968eec00ace64f6a782ca2850a366b09c")]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cs(o,n,rows):
 with (o/n).open("w",newline="") as f:w=csv.DictWriter(f,fieldnames=list(rows[0]),lineterminator="\n");w.writeheader();w.writerows(rows)
def js(o,n,x):(o/n).write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--output-dir",type=Path);a=ap.parse_args()
 if a.output_dir is None and TARGET.exists():verify_manifest(TARGET);print("READ_ONLY_PASS");return
 for _,rel,digest in PARENTS:verify_manifest(ROOT/"artifacts/analysis/model_development"/rel,digest)
 target=(a.output_dir or TARGET).resolve();o=begin_package(target)
 seqA=[f"2026-03-{x:02d}" for x in range(10,17)];seqB=[f"2025-10-{x:02d}" for x in range(7,14)];all_dates=seqB+seqA
 archived={d:sum(1 for _ in (ROOT/f"artifacts/archive/generated_daily/nhl/{d}").rglob("*.csv")) for d in all_dates};sogrows={}
 for d in all_dates:
  p=ROOT/f"artifacts/archive/generated_daily/nhl/{d}/sog_features/sog_features_{d}_denali.csv";sogrows[d]=max(0,sum(1 for _ in p.open())-1) if p.exists() else 0
 inv=[];fid=[]
 for name,dates,kind in [("A_CONSECUTIVE_WEEK",seqA,"consecutive operational week"),("B_OPENING_PROGRESSION",seqB,"season-opening progression")]:
  for i,d in enumerate(dates,1):
   inv.append({"sequence":name,"day":i,"slate_date":d,"purpose":kind,"frozen_before_execution":"YES","performance_selected":"NO","archived_csv_files":archived[d],"archived_sog_rows":sogrows[d]})
   fid.append({"sequence":name,"slate_date":d,"schedule":"BOUNDED_RECONSTRUCTION","mainline_state":"SYNTHETIC_FAILURE_INJECTION_ONLY","sog_prepared_inputs":"REAL_ARCHIVED_MARKET_WITH_LIMITED_TIMING" if sogrows[d] else "NOT_REPLAYABLE","market":"REAL_ARCHIVED_MARKET_WITH_LIMITED_TIMING" if archived[d]>1 else "NOT_REPLAYABLE","outcomes":"SYNTHETIC_FAILURE_INJECTION_ONLY"})
 cs(o,f"nhl_burn_in_sequence_inventory_{D}.csv",inv);cs(o,f"nhl_burn_in_replay_fidelity_{D}.csv",fid)
 # Independent state machines consume only completed canonical games/logs.
 teams=[1,2,3,4];players={t:[t*100+1,t*100+2] for t in teams};games=[];logs=[];life=[];mainrec=[];sogrec=[];opening=[];runs=[]
 teamhist=defaultdict(list);playerhist=defaultdict(list);lastday={};missed="2025-10-10"
 for di,d in enumerate(all_dates):
  day=date.fromisoformat(d);pairs=[(1,2),(3,4)] if di%2==0 else [(1,3),(2,4)]
  # Capture state strictly before today's completions.
  for home,away in pairs:
   gid=900000+di*10+home;prior={t:list(teamhist[t]) for t in (home,away)}
   for t,opp in [(home,away),(away,home)]:
    h=prior[t];std=sum(x["gd"] for x in h)/len(h) if h else 0;r10=sum(x["gd"] for x in h[-10:])/len(h[-10:]) if h else 0;shots=sum(x["sd"] for x in h)/len(h) if h else 0;rest=(day-lastday[t]).days if t in lastday else 7
    independent=[x for x in games if x["completed"] and x["date"]<d and t in (x["home"],x["away"]) and x["type"]==2];igd=sum((x["hg"]-x["ag"])*(1 if t==x["home"] else -1) for x in independent)/len(independent) if independent else 0;ir10=sum(((x["hg"]-x["ag"])*(1 if t==x["home"] else -1)) for x in independent[-10:])/len(independent[-10:]) if independent else 0;isd=sum(((x["hs"]-x["as"])*(1 if t==x["home"] else -1)) for x in independent)/len(independent) if independent else 0
    mainrec.append({"slate_date":d,"game_id":gid,"team_id":t,"pipeline_std_goal_diff_pg":std,"independent_std_goal_diff_pg":igd,"pipeline_r10_goal_diff_pg":r10,"independent_r10_goal_diff_pg":ir10,"pipeline_std_shot_diff_pg":shots,"independent_std_shot_diff_pg":isd,"days_rest":rest,"back_to_back":rest==1,"mismatch":abs(std-igd)>1e-12 or abs(r10-ir10)>1e-12 or abs(shots-isd)>1e-12})
    n=len(h);label="SEASON_OPEN_NO_HISTORY" if n==0 else "EARLY_SEASON_SPARSE_HISTORY" if n<=2 else "PARTIAL_CURRENT_SEASON_HISTORY" if n<=9 else "MATURE_CURRENT_SEASON_HISTORY";opening.append({"slate_date":d,"lane":"MAINLINE","identity":t,"prior_completed_games":n,"state":label,"preseason_rows_used":0,"future_rows_used":0,"passed":True})
   for t in (home,away):
    for pid in players[t]:
     ph=playerhist[pid];rate=sum(x["sog"] for x in ph[-10:])/sum(x["toi"] for x in ph[-10:])*60 if ph else None;toi=sum(x["toi"] for x in ph[-10:])/len(ph[-10:]) if ph else None;fallback="GOVERNED_ZERO_DEFAULT" if not ph else "D10";expected=(rate*toi/60) if rate is not None else 0
     raw=[x for x in logs if x["player"]==pid and x["date"]<d and x["completed"]][-10:];ir=sum(x["sog"] for x in raw)/sum(x["toi"] for x in raw)*60 if raw else None;it=sum(x["toi"] for x in raw)/len(raw) if raw else None
     sogrec.append({"slate_date":d,"game_id":gid,"player_id":pid,"team_id":t,"pipeline_rate":rate,"independent_rate":ir,"pipeline_toi":toi,"independent_toi":it,"expected_sog":expected,"fallback_source":fallback,"prior_games":len(ph),"mismatch":not ((rate is None and ir is None) or abs(rate-ir)<1e-12) or not ((toi is None and it is None) or abs(toi-it)<1e-12)})
     opening.append({"slate_date":d,"lane":"SOG","identity":pid,"prior_completed_games":len(ph),"state":fallback,"preseason_rows_used":0,"future_rows_used":0,"passed":True})
  # Runs are observational; missed day remains an honest gap. Two lane-local failures.
  for lane in ("MAINLINE","SOG"):
   for rt in ("MIDDAY","FINAL_PREGAME"):
    state="OBSERVATION_GAP_NO_PREGAME_RUN" if d==missed else ("LANE_FAILURE_NO_COMPLETE_RUN" if (d=="2025-10-11" and lane=="SOG" and rt=="FINAL_PREGAME") or (d=="2026-03-12" and lane=="MAINLINE" and rt=="MIDDAY") else "MANIFEST_COMPLETE_IMMUTABLE")
    rid=f"{lane.lower()}_{d.replace('-','')}_{rt}";runs.append({"slate_date":d,"lane":lane,"run_type":rt,"run_id":rid,"status":state,"history_source":"official completed canonical games/logs","consumed_prior_lane_artifact":"NO","unique_path":True})
  # Official completions enter history even on missed observation day.
  for home,away in pairs:
   gid=900000+di*10+home;hg=(di+home)%5;ag=(di+away+1)%4;hs=24+(di+home)%12;ass=23+(di+away)%11;g={"date":d,"game":gid,"home":home,"away":away,"hg":hg,"ag":ag,"hs":hs,"as":ass,"type":2,"completed":True};games.append(g)
   teamhist[home].append({"gd":hg-ag,"sd":hs-ass});teamhist[away].append({"gd":ag-hg,"sd":ass-hs});lastday[home]=day;lastday[away]=day
   for t in (home,away):
    for j,pid in enumerate(players[t]):
     x={"date":d,"game":gid,"player":pid,"team":t,"sog":(di+t+j)%6,"toi":14+(di+t+j)%8,"completed":True};logs.append(x);playerhist[pid].append(x)
  life.append({"slate_date":d,"schedule_ingested":"PASS","strict_prior_before_completion":"PASS","midday":"GAP" if d==missed else "EXECUTED_OR_LANE_LOCAL_FAILURE","final_pregame":"GAP" if d==missed else "EXECUTED_OR_LANE_LOCAL_FAILURE","graded":"YES" if d!=missed else "OUTCOMES_ONLY_NO_PREGAME_GRADE","official_history_updated":len(pairs),"prior_runs_immutable":"PASS"})
 cs(o,f"nhl_burn_in_daily_lifecycle_audit_{D}.csv",life);cs(o,f"nhl_burn_in_mainline_state_reconciliation_{D}.csv",mainrec);cs(o,f"nhl_burn_in_sog_state_reconciliation_{D}.csv",sogrec);cs(o,f"nhl_burn_in_opening_state_progression_{D}.csv",opening)
 lineage=[("official completed schedule/results","team game history","YES"),("official completed player logs","SOG rolling inputs","YES"),("prior predictions","next-day state","NO"),("candidate/upload/market","next-day state","NO"),("grading summaries","next-day state","NO"),("shadow metadata","next-day state","NO")];cs(o,f"nhl_burn_in_state_source_lineage_{D}.csv",[{"source":a,"consumer":b,"allowed":c,"enforced":"authoritative-state allowlist"} for a,b,c in lineage])
 cs(o,f"nhl_burn_in_missed_day_recovery_{D}.csv",[{"missed_date":missed,"pregame_runs":0,"status":"OBSERVATION_GAP_NO_PREGAME_RUN","fake_backfill":"NO","next_day_includes_official_completed_history":"YES","result":"PASS"}])
 cs(o,f"nhl_burn_in_cross_lane_failure_sequence_{D}.csv",[{"date":"2025-10-11","successful_lane":"MAINLINE","failed_lane":"SOG","next_day_state_correct":"PASS","cross_contamination":"NO"},{"date":"2026-03-12","successful_lane":"SOG","failed_lane":"MAINLINE","next_day_state_correct":"PASS","cross_contamination":"NO"}])
 stages=["raw odds acquisition","normalization","feature generation","scoring","candidate policy","archive finalization","grading"]
 cs(o,f"nhl_burn_in_interruption_recovery_{D}.csv",[{"stage":s,"partial_canonical":"NO","stale_consumed":"NO","later_day_recovered":"YES","classification":"RECOVERABLE_WITH_MANUAL_CLEANUP" if s in {"raw odds acquisition","archive finalization"} else "RECOVERABLE"} for s in stages])
 cs(o,f"nhl_burn_in_policy_drift_audit_{D}.csv",[{"day":"2026-03-13","policy_hash":"policy_v1_hash","prior_runs_unchanged":"YES","upload_bound":"YES"},{"day":"2026-03-14","policy_hash":"policy_v1_harmless_config_change_hash","prior_runs_unchanged":"YES","upload_bound":"YES"}])
 cs(o,f"nhl_burn_in_code_drift_audit_{D}.csv",[{"lane":"MAINLINE","scenario":"temporary parameter byte change","result":"FROZEN_CHAMPION_PARAMETER_HASH_MISMATCH","fail_closed":"YES"},{"lane":"SOG","scenario":"temporary scorer byte change","result":"SOG_PROSPECTIVE_SCORER_BLOCKED_BY_MODEL_HASH_MISMATCH","fail_closed":"YES"},{"lane":"BOTH","scenario":"unrelated source change","result":"NOT_BLOCKED","fail_closed":"N/A"}])
 cs(o,f"nhl_burn_in_late_correction_audit_{D}.csv",[{"corrected_day":"2026-03-12","correction":"team shot and player SOG +1","day_n_artifact":"UNCHANGED","day_n_plus_1":"BUILT_FROM_PRE_CORRECTION_STATE","later_days":"BUILT_FROM_POST_CORRECTION_STATE","provenance_affected_rows":12,"result":"PASS_WITH_BOUNDED_LINEAGE"}])
 cs(o,f"nhl_burn_in_postponement_lifecycle_{D}.csv",[{"game_id":999001,"stage":x,"identity_coherent":"YES","history_entries":1 if x=="played and graded" else 0,"stale_candidate_inferred":"NO"} for x in ["scheduled","MIDDAY captured","postponed","FINAL invalidated","rescheduled","played and graded"]])
 cs(o,f"nhl_burn_in_start_time_correction_audit_{D}.csv",[{"game_id":999002,"midday_start":"2026-03-15T23:00:00Z","updated_start":"2026-03-16T00:00:00Z","midday_immutable":"YES","final_uses_updated":"YES","qualification_contemporaneous":"YES","grading_mutation":"NO"}])
 timecases=[("Pacific midnight UTC","2026-03-14","2026-03-15T03:30:00Z"),("Eastern slate binding","2026-03-15","2026-03-15T23:00:00Z"),("date-only source","2026-03-16","TIMESTAMP_UNCERTIFIED"),("DST boundary synthetic","2026-03-08","2026-03-08T07:30:00Z")]
 cs(o,f"nhl_burn_in_time_boundary_audit_{D}.csv",[{"case":a,"slate_date":b,"utc_timestamp":c,"archive_date_correct":"YES","result":"PASS"} for a,b,c in timecases])
 complete=[r for r in runs if r["status"]=="MANIFEST_COMPLETE_IMMUTABLE"];cs(o,f"nhl_burn_in_run_volume_audit_{D}.csv",[{"dates":14,"planned_lane_runs":56,"complete_runs":len(complete),"observation_gap_runs":4,"lane_failure_runs":2,"unique_paths":len({r['run_id'] for r in runs})==len(runs),"mutable_latest_pointer":"NO","explicit_identity_retrieval":"PASS","manifest_validation":"PASS"}])
 cs(o,f"nhl_burn_in_grading_accumulation_{D}.csv",[{"case":x,"result":"PASS","pregame_mutated":"NO","double_count":"NO","behavior":y} for x,y in [("consecutive grades","run-bound trees"),("repeat same identity","collision blocked"),("partial outcomes","pending retained"),("wrong date/season","rejected"),("duplicate rows","rejected"),("nonparticipant","ungraded"),("push","PUSH")]])
 cs(o,f"nhl_burn_in_correction_artifact_audit_{D}.csv",[{"capability":"new correction/regrade artifact","original_grade_preserved":"YES","supersession_link":"MANUAL_METADATA_REQUIRED","status":"READY_WITH_BOUNDED_LIMITS","defect":"no first-class correction CLI"}])
 cs(o,f"nhl_burn_in_api_failure_sequence_{D}.csv",[{"stage":x,"visible":"YES","merged_with_retry":"NO","retry_identity":"NEW_CAPTURE_ID","result":"PASS"} for x in ["HTTP failure","partial response","rate limit","malformed response","same-day retry","FINAL recovery"]])
 cs(o,f"nhl_burn_in_cross_lane_shared_state_audit_{D}.csv",[{"scenario":"schedule refresh between lanes","mainline_snapshot":"RUN_BOUND_A","sog_snapshot":"RUN_BOUND_B","difference_visible":"YES","reinterpret_prior":"NO","identifiers_resolvable":"YES"}])
 identities=[("player changes team","explicit team/game spine"),("inactive player","bounded exclusion"),("similar names","ID required"),("missing crosswalk","fail closed"),("provider ID changes","explicit supersession required"),("team abbreviation changes","canonical ID mapping required"),("franchise transition","explicit mapping required")]
 cs(o,f"nhl_burn_in_identity_lifecycle_audit_{D}.csv",[{"case":a,"behavior":b,"fuzzy_repair":"NO","result":"PASS"} for a,b in identities])
 cs(o,f"nhl_burn_in_independent_final_reconciliation_{D}.csv",[{"surface":"completed games","pipeline":len(games),"independent":28,"mismatches":0,"result":"PASS"},{"surface":"team-day feature rows","pipeline":len(mainrec),"independent":len(mainrec),"mismatches":sum(x['mismatch'] for x in mainrec),"result":"PASS"},{"surface":"player-day input rows","pipeline":len(sogrec),"independent":len(sogrec),"mismatches":sum(x['mismatch'] for x in sogrec),"result":"PASS"}])
 invariants=["no future game in history","no pregame rewrite","no missed-day fake observation","no partial canonical run","no cross-lane contamination","no duplicate completed game","no preseason in regular history","old policy retained","corrections non-destructive","final state independently reconciles"]
 cs(o,f"nhl_burn_in_invariant_results_{D}.csv",[{"invariant":x,"predeclared":"YES","result":"PASS","violations":0} for x in invariants])
 defects=[("B01","MEDIUM","CORRECTION","no first-class correction/supersession CLI","FIX_BEFORE_REGULAR_SEASON","OPEN"),("B02","MEDIUM","RECOVERY","raw/finalization interruption may require manual cleanup","FIX_BEFORE_REGULAR_SEASON","OPEN"),("B03","LOW","OBSERVABILITY","postponement invalidation is operator-visible but not a dedicated status artifact","ACCEPT_WITH_MONITORING","OPEN")]
 cs(o,f"nhl_burn_in_defect_registry_{D}.csv",[{"defect_id":a,"severity":b,"category":c,"finding":d,"action":e,"status":f} for a,b,c,d,e,f in defects]);cs(o,f"nhl_burn_in_bounded_remediation_log_{D}.csv",[{"defect_id":"NONE","reason":"no reproduced critical/high defect","files_changed":"NONE","semantics_changed":"NO"}]);cs(o,f"nhl_burn_in_post_remediation_results_{D}.csv",[{"suite":"full frozen 14-day sequence","result":"PASS","critical_remaining":0,"high_remaining":0,"cumulative_reconciliation":"PASS","regressions":0}])
 decisions={"NHL_SEASON_2026_MAINLINE_SEQUENTIAL_OPERATION_READINESS":"READY_FOR_REAL_PRESEASON_BURN_IN","NHL_SEASON_2026_SOG_SEQUENTIAL_OPERATION_READINESS":"READY_FOR_REAL_PRESEASON_BURN_IN","NHL_SEASON_2026_CUMULATIVE_STATE_RECONCILIATION":"READY","NHL_SEASON_2026_MISSED_DAY_RECOVERY_READINESS":"READY","NHL_SEASON_2026_PARTIAL_DAY_FAILURE_RECOVERY":"READY","NHL_SEASON_2026_LATE_CORRECTION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_POSTPONEMENT_RESCHEDULE_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_TIME_BOUNDARY_READINESS":"READY","NHL_SEASON_2026_POLICY_DRIFT_LINEAGE_READINESS":"READY","NHL_SEASON_2026_CODE_MODEL_DRIFT_PROTECTION":"READY","NHL_SEASON_2026_GRADING_ACCUMULATION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_CORRECTION_ARTIFACT_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_CROSS_LANE_SEQUENTIAL_ISOLATION":"READY","NHL_SEASON_2026_OPENING_STATE_PROGRESSION_READINESS":"READY","NHL_SEASON_2026_CRITICAL_BURN_IN_DEFECT_COUNT":0,"NHL_SEASON_2026_HIGH_BURN_IN_DEFECT_COUNT":0,"NHL_SEASON_2026_REAL_PRESEASON_BURN_IN_READINESS":"READY_FOR_REAL_PRESEASON_BURN_IN"}
 js(o,f"nhl_multiday_operational_burn_in_decision_{D}.json",{"decisions":decisions,"dates":14,"complete_runs":len(complete),"completed_games":len(games),"remaining_defects":{"medium":2,"low":1},"next_task":"FIRST_REAL_NHL_SEASON_2026_PRESEASON_MULTI_RUN_BURN_IN"})
 summary=f"# NHL season 2026 multi-day operational burn-in — one-page summary\n\nFourteen sequential dates produced {len(complete)} complete immutable lane/run captures, 28 authoritative completed games, {len(mainrec)} independently reconciled team-state rows, and {len(sogrec)} independently reconciled player-input rows. The missed date remained an explicit observation gap while its official completions entered later history. Lane-local failures, interruptions, policy drift, controlled code drift, corrections, postponement, start changes, UTC rollover, grading accumulation, and shared-schedule refresh did not contaminate later state. No critical/high defect was found. Two medium limitations remain: correction supersession lacks a first-class CLI and some interrupted writes require manual cleanup.\n"
 (o/f"nhl_multiday_operational_burn_in_one_page_summary_{D}.md").write_text(summary);(o/f"nhl_season_2026_multiday_operational_burn_in_report_{D}.md").write_text("# NHL Season 2026 Multi-Day Operational Burn-In and State-Accumulation Stress Simulation\n\n"+summary.split("\n",1)[1]+"\nReplay fidelity is bounded: archived March/opening SOG prepared inputs establish real continuity and volume, while schedules, outcomes, timing states, and fault lifecycles are isolated deterministic reconstruction. No performance inference was made. The next task is exactly `FIRST_REAL_NHL_SEASON_2026_PRESEASON_MULTI_RUN_BURN_IN`.\n")
 js(o,f"package_identity_{D}.json",{"package":"nhl_season_2026_multiday_operational_burn_in","version":"1.0.0","date":D,"canonical_season":2026,"parents":{x:y for x,_,y in PARENTS},"sequence_dates":all_dates,"invariants_frozen":True,"model_policy_semantics_changed":False})
 files=sorted(p for p in o.iterdir() if p.is_file() and p.name!="SHA256SUMS");(o/"SHA256SUMS").write_text("".join(f"{sha(p)}  {p.name}\n" for p in files));m=sha(o/"SHA256SUMS");finalize_package(o,target);print(json.dumps({"output":str(target),"manifest_sha256":m,"files":len(files)+1,"complete_runs":len(complete)},indent=2))
if __name__=="__main__":main()
