#!/usr/bin/env python3
"""Freeze the NHL moneyline champion-challenger experiment specification; never fit."""
from __future__ import annotations
import argparse, hashlib, json, subprocess
from pathlib import Path
import pandas as pd

DATE="2026-07-13"; CHAMPION="NHL_MONEYLINE_TEAM_SCHEDULE_LOGIT_CONTROL_V1"; CHAMP_HASH="83beb11588f7e7e31919f23be2dea51ff49863954fc9be750509b30a0eff2cda"
AUX_SCHEDULE_MANIFEST_HASH="783784e6320b47f90b6dc5f18bb7adc5d359067948836a2c9cabdecdd0842507"
PARENTS={"population":("nhl_full_game_moneyline_population_certification","0ce4a3b673e77af434985670f2bcec779eda561210e5ebc0becbe546a4f14326"),"features":("nhl_moneyline_team_goalie_feature_spine","c1841f802a90aa1e772059695cc7e8e1c512c9f63730ab54bd4cf0576bf92780"),"baseline":("nhl_moneyline_simple_baseline_process_validation","aeae5fcd8553c91ab1e2af86d27e4bab7dc28d8c05fcd7871cfd72accab1a65c"),"certification":("nhl_moneyline_frozen_baseline_certification","8bb36073fee4f055f399c651f942b8de6eb1bb3b75b96b6112dd9d4af4224cf5")}
CONTROL=["diff_std_goal_diff_pg","diff_r10_goal_diff_pg","diff_std_shot_diff_pg","diff_days_rest","home_back_to_back","away_back_to_back"]
NEW=["diff_games_prior_5d","home_consecutive_road_games_prior","away_consecutive_road_games_prior"]
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def js(o,p): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+"\n")
def csv(d,p): d.to_csv(p,index=False,lineterminator="\n",float_format="%.15g")
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[3]); ap.add_argument('--output-dir',type=Path); a=ap.parse_args(); root=a.repo_root.resolve(); base=root/'artifacts/analysis/model_development'; out=(a.output_dir or base/f'nhl_moneyline_champion_challenger_specification/{DATE}').resolve(); out.mkdir(parents=True,exist_ok=True)
 pp={k:base/s/DATE for k,(s,h) in PARENTS.items()}; before={str(f):sha(f) for p in pp.values() for f in p.iterdir() if f.is_file()}
 for k,p in pp.items(): assert sha(p/'SHA256SUMS')==PARENTS[k][1]; subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=p,check=True,capture_output=True)
 schedule_parent=base/f'nhl_season_2024_utah_game_date_remediation/{DATE}'; assert sha(schedule_parent/'SHA256SUMS')==AUX_SCHEDULE_MANIFEST_HASH; subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=schedule_parent,check=True,capture_output=True)
 bp=pp['baseline']; pred=bp/f'nhl_moneyline_simple_baseline_control_predictions_{DATE}.csv'; assert sha(pred)==CHAMP_HASH
 part=pd.read_csv(bp/f'nhl_moneyline_simple_baseline_population_partition_{DATE}.csv'); spine=pd.read_csv(pp['features']/f'nhl_moneyline_team_feature_spine_{DATE}.csv'); sched=pd.read_csv(base/f'nhl_season_2024_utah_game_date_remediation/{DATE}/nhl_season_2024_schedule_rebuild_{DATE}.csv')
 keys=['canonical_season','game_id']; assert len(part)==len(spine)==2798 and part.groupby('split').size().to_dict()=={'fit':701,'validation':699,'holdout':1398}; assert part[keys].sort_values(keys).reset_index(drop=True).equals(spine[keys].sort_values(keys).reset_index(drop=True))
 # Coverage proof for the proposed derived fields, using the certified repaired season 2024 schedule chain.
 f=spine[keys+['home_games_prior_5d','away_games_prior_5d','home_consecutive_road_games_prior','away_consecutive_road_games_prior']].copy(); s=sched.set_index(keys); mask=f.canonical_season.eq(2024); idx=pd.MultiIndex.from_frame(f.loc[mask,keys])
 for c in ['home_games_prior_5d','away_games_prior_5d','home_consecutive_road_games_prior','away_consecutive_road_games_prior']: f.loc[mask,c]=s.loc[idx,c].to_numpy()
 f['diff_games_prior_5d']=f.home_games_prior_5d-f.away_games_prior_5d; assert f[NEW].notna().all().all()

 inv=pd.DataFrame([
 ["RICHER_TEAM_STRENGTH_DECOMPOSITION","Separate GF/GA and SF/SA at season and prior windows","home/away std_gf_pg, std_ga_pg, std_sf_pg, std_sa_pg, r5/r10 GF/GA/SF/SA","Certified team feature spine","CERTIFIED_STRICT_PRIOR","READY",2798,0,"HIGH_OVERLAP","High: linear decompositions substantially reconstruct the champion differentials","High","High","Limited novelty; correlated feature sprawl"],
 ["COMPRESSED_WORKLOAD_AND_ROAD_SEQUENCE_CONTEXT","Cumulative schedule load and travel sequence add fatigue/context beyond one-day rest","diff_games_prior_5d; home/away_consecutive_road_games_prior","Certified team spine plus repaired season 2024 schedule chain","CERTIFIED_STRICT_PRIOR", "READY",2798,0,"MODERATE_OVERLAP","Moderate: related to rest/B2B but represents five-day density and road persistence","Low","High","Schedule effects may be weak; road streak is a proxy, not distance traveled"],
 ["STABLE_RECENT_FORM_DIVERGENCE","Prior-5 versus prior-10 divergence represents acceleration/deceleration","derived r5-minus-r10 GF/GA or goal differential","Certified team feature spine","CERTIFIED_STRICT_PRIOR","READY_WITH_BOUNDED_LIMITS",2798,"early-season imputation required","HIGH_OVERLAP","High: overlaps prior-10 goal differential and dominant team strength","Medium","High","No outcome-driven window choice allowed; noisy early season"],
 ["OPPONENT_ADJUSTED_STRENGTH_NORMALIZATION","Correct raw strength for opponents faced","No certified opponent-adjusted fields currently exist","Would require deterministic construction from certified outcomes","NOT_YET_CERTIFIED","BLOCKED",0,"not constructed","LOW_OVERLAP","Potentially low and genuinely novel","High","Medium","New lineage/timing certification required before specification"],
 ["HISTORICALLY_CERTIFIED_SPECIAL_TEAMS","Power-play and penalty-kill context adds matchup-specific information","No fixed-spine certified historical fields","No qualifying parent source","NOT_CERTIFIED","BLOCKED",0,"unavailable","LOW_OVERLAP","Low if certified","High","Medium","Coverage, grain, and timing unresolved"],
 ["GOALIE_AND_LINEUP_CONTEXT","Pregame personnel strength adds direct matchup context","actual starter, lineup, injury/scratch state","No strict-prior replayable historical authority","HISTORICALLY_BLOCKED","PROSPECTIVE_ONLY",0,"unavailable","LOW_OVERLAP","Lowest overlap and high prospective value","High","High","Oracle contamination historically; requires timestamped prospective collection"],
 ],columns=['family','hypothesis','exact_fields','source','strict_prior_status','historical_readiness','fixed_population_coverage','missingness','control_overlap_class','relationship_to_control','engineering_complexity','interpretability','major_risks'])
 inv['temporal_stability_evidence']='Not outcome-tested in this specification; lineage coverage only'
 inv['season_2026_collectability']=['READY_FROM_DAILY_TEAM_RESULTS','READY_FROM_DAILY_SCHEDULE','READY_FROM_DAILY_TEAM_RESULTS','CONSTRUCTIBLE_AFTER_CERTIFICATION','REQUIRES_NEW_SOURCE','PROSPECTIVE_TIMESTAMPED_COLLECTION_REQUIRED']
 csv(inv,out/f'nhl_moneyline_challenger_candidate_family_inventory_{DATE}.csv')
 overlap=pd.DataFrame([
 ['diff_games_prior_5d','diff_days_rest; home_back_to_back; away_back_to_back','MODERATE_OVERLAP','Cumulative games in the prior five calendar days is not determined by yesterday-only status.','Retain one density window; exclude 3-day and 7-day variants.'],
 ['home_consecutive_road_games_prior','home_back_to_back','LOW_OVERLAP','Road-sequence persistence is location context, not elapsed rest.','No travel distance or postgame information.'],
 ['away_consecutive_road_games_prior','away_back_to_back','LOW_OVERLAP','Road-sequence persistence is location context, not elapsed rest.','No travel distance or postgame information.'],
 ],columns=['challenger_field','closest_control_fields','overlap_class','novel_information_rationale','anti_sprawl_boundary']); csv(overlap,out/f'nhl_moneyline_challenger_overlap_audit_{DATE}.csv')

 hypothesis={"selected_family":"COMPRESSED_WORKLOAD_AND_ROAD_SEQUENCE_CONTEXT","challenger_name":"NHL_MONEYLINE_SCHEDULE_LOAD_CONTEXT_LOGIT_CHALLENGER_V1","form":"ADDITIVE_CHALLENGER","hypothesis":"Five-day workload imbalance and home/away road-sequence persistence contain strict-prior fatigue and location-context information beyond the champion's team-strength, rest-differential, and back-to-back fields.","why_selected":"It is the highest-readiness family with genuine but bounded novelty, exact repaired-schedule coverage, simple interpretation, and no dependence on historically unavailable personnel data.","why_not_algorithm_change":"The information hypothesis is testable with the champion's same linear probabilistic instrument; changing learner would confound information with flexibility.","champion_source":{"name":CHAMPION,"stored_prediction_sha256":CHAMP_HASH},"execution_boundary":"CHALLENGER_EXECUTION_NOT_AUTHORIZED_BY_THIS_PACKAGE"}; js(hypothesis,out/f'nhl_moneyline_selected_challenger_hypothesis_{DATE}.json')
 manifest=[]
 definitions={"diff_std_goal_diff_pg":"Home minus away season-to-date goal differential rate","diff_r10_goal_diff_pg":"Home minus away prior-10 goal differential rate","diff_std_shot_diff_pg":"Home minus away season-to-date shot differential rate","diff_days_rest":"Home minus away days rest","home_back_to_back":"Home played previous calendar day","away_back_to_back":"Away played previous calendar day","diff_games_prior_5d":"Home games in prior five calendar days minus away games in prior five calendar days","home_consecutive_road_games_prior":"Home team's consecutive road games immediately before game","away_consecutive_road_games_prior":"Away team's consecutive road games immediately before game"}
 for i,x in enumerate(CONTROL+NEW,1): manifest.append([i,x,'FROZEN_CONTROL' if x in CONTROL else 'ADDITIVE_NEW_FAMILY',definitions[x],'CERTIFIED_STRICT_PRIOR','FIT_ONLY_MEDIAN_IMPUTATION',2798,0 if x in NEW else int(spine[x].isna().sum()),'parent value' if x in CONTROL else ('home_games_prior_5d - away_games_prior_5d' if x=='diff_games_prior_5d' else 'direct certified schedule-chain value')])
 fm=pd.DataFrame(manifest,columns=['feature_order','feature_name','role','definition','timing_status','missingness_policy','population_rows','raw_missing_rows_before_policy','construction']); csv(fm,out/f'nhl_moneyline_challenger_feature_manifest_{DATE}.csv')
 population={"identity":keys,"rows":2798,"canonical_seasons":[2023,2024],"target":"home_win_target","fit_rows":701,"validation_rows":699,"holdout_rows":1398,"membership_source":f'nhl_moneyline_simple_baseline_population_partition_{DATE}.csv',"membership_source_sha256":sha(bp/f'nhl_moneyline_simple_baseline_population_partition_{DATE}.csv'),"row_retention":"All champion rows must be scored; selective dropping prohibited.","challenger_missingness":"Fit-only median imputation using the same preprocessing policy; selected new fields have 2,798/2,798 repaired-spine coverage."}; js(population,out/f'nhl_moneyline_challenger_population_contract_{DATE}.json')
 temporal={"split_source_sha256":population['membership_source_sha256'],"fit":{"canonical_season":2023,"dates":"2023-10-10 through 2024-01-18","rows":701},"validation":{"canonical_season":2023,"dates":"2024-01-19 through 2024-06-24","rows":699},"holdout":{"canonical_season":2024,"dates":"2024-10-04 through 2025-06-17","rows":1398},"random_split":False,"immutable":True,"champion_probabilities":"Stored artifact only; no champion refit."}; js(temporal,out/f'nhl_moneyline_challenger_temporal_protocol_{DATE}.json')
 metrics={"primary_order":["brier_score","log_loss","roc_auc"],"secondary":["accuracy_at_0.5","ECE_fixed_deciles","weighted_absolute_calibration_gap","mean_probability","observed_home_win_rate","correctness"],"comparison":"Paired challenger minus or champion minus challenger on identical game rows as directionally documented.","brier_improvement":"champion_brier - challenger_brier; positive favors challenger","log_loss_improvement":"champion_log_loss - challenger_log_loss; positive favors challenger","roc_auc_change":"challenger_auc - champion_auc","calibration":"Identical fixed [0.0,0.1,...,1.0] buckets; no recalibration","excluded":["odds","ROI","threshold optimization"]}; js(metrics,out/f'nhl_moneyline_challenger_metric_contract_{DATE}.json')
 success={"overall_rule":"ALL_REQUIRED_GATES_MUST_PASS; no metric shopping or post-result tuning.","validation":{"brier_improvement":"> 0","log_loss_improvement":"> 0","ECE_degradation":"challenger_ECE - champion_ECE <= 0.010"},"holdout":{"brier_improvement":"> 0","log_loss_improvement":"> 0","roc_auc_change":">= -0.005","ECE_degradation":"<= 0.010"},"combined_out_of_time":{"brier_improvement":"> 0","log_loss_improvement":"> 0","paired_date_bootstrap_positive_fraction":"at least 0.80 for each proper-score improvement"},"stability":{"leave_one_month_out":"at least 75% retain positive Brier and log-loss improvement; no exclusion has both improvements < -0.002","leave_one_team_out":"at least 75% retain positive Brier and log-loss improvement; no exclusion has both improvements < -0.002","probability_margin_bands":"at least 3 of 5 have nonnegative Brier improvement and aggregate excluding the best band remains positive","missingness":"fully observed combined out-of-time Brier and log-loss improvements both positive"},"failure_policy":"Any required failure produces NO_FURTHER_RESEARCH_PROMOTION; diagnose construction defects only, never tune within this execution."}; js(success,out/f'nhl_moneyline_challenger_success_criteria_{DATE}.json')
 uncertainty={"method":"paired calendar-date cluster bootstrap","population":"combined validation plus holdout","resampling_unit":"game_date; all games on a sampled date remain paired","resamples":5000,"seed":20260713,"interval":"two-sided percentile 95%","statistics":["champion_brier - challenger_brier","champion_log_loss - challenger_log_loss","challenger_roc_auc - champion_roc_auc"],"report":["point estimate","2.5th percentile","97.5th percentile","fraction above zero"],"missing_or_single_class_auc_resample":"record NA for AUC only; never discard proper-score resample","interpretation":"Uncertainty describes robustness and cannot override failed deterministic gates."}; js(uncertainty,out/f'nhl_moneyline_challenger_uncertainty_protocol_{DATE}.json')
 slices=pd.DataFrame([
 ['validation','Frozen split','699','Primary gate'],['holdout','Frozen split','1398','Primary gate'],['combined_out_of_time','Validation plus holdout','2097','Primary synthesis'],['calendar_month','YYYY-MM from frozen game date','all fixed months','Concentration check'],['team','Each franchise as home and away','all teams','Identity/concentration check'],['probability_margin_band','Champion |p-0.5|: <.025, .025-.05, .05-.10, .10-.15, >=.15','five fixed bands','Confidence-region check'],['missingness_state','FULLY_OBSERVED versus MINIMUM_HISTORY_LIMITED_IMPUTED','two frozen states','Imputation stability'],
 ],columns=['slice','fixed_definition','expected_membership','purpose']); csv(slices,out/f'nhl_moneyline_challenger_stability_slices_{DATE}.csv')
 failure=pd.DataFrame([
 ['CHALLENGER_WINS_CLEANLY','All required gates pass','Potential new schedule-context information; request separate promotion-grade research authorization','Do not promote or deploy'],['APPROXIMATE_TIE','Proper-score differences near zero or bootstrap support below 0.80','Treat family as duplicative or too weak','Do not tune'],['CHALLENGER_LOSES','Validation or holdout proper-score gates fail','Reject/defer family absent a proven construction defect','Do not replace champion'],['MIXED_VALIDATION_HOLDOUT','Direction differs between validation and holdout','Classify unstable','No promotion'],['COVERAGE_OR_TIMING_FAILURE','Row alignment, strict-prior, or coverage assertion fails','Invalidate execution and return to data remediation','Do not interpret performance'],
 ],columns=['outcome','frozen_condition','interpretation','prohibited_response']); csv(failure,out/f'nhl_moneyline_challenger_failure_interpretation_{DATE}.csv')
 bridge=pd.DataFrame([
 ['selected_schedule_context','Official daily NHL schedule and completed game results',"Before each game's scheduled start; use only games completed previously",'Daily refresh plus immutable pregame snapshot','canonical_season; game_id; team_id; game_date','100% schedule coverage','Reschedules, postponed games, date/time corrections, franchise identity transitions'],['prospective_goalie_lineup_candidate','Timestamped official/team starting-goalie and lineup status','Snapshot must predate scheduled start and record source timestamp','Event-driven plus scheduled pregame snapshots','canonical_season; game_id; team_id; player_id; captured_at_utc','Unknown until collection contract is proven','Late starter changes, source revisions, scratches, oracle contamination'],
 ],columns=['family','required_daily_sources','timing_requirement','collection_cadence','identity_keys','expected_coverage','operational_risks']); csv(bridge,out/f'nhl_moneyline_season_2026_challenger_operational_bridge_{DATE}.csv')
 decisions={"NHL_MONEYLINE_CHAMPION_IDENTITY_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_FAMILY_INVENTORY_COMPLETE":"READY","NHL_MONEYLINE_CHALLENGER_INFORMATION_NOVELTY_ASSESSED":"READY_WITH_BOUNDED_LIMITS","NHL_MONEYLINE_HISTORICAL_CHALLENGER_SELECTED":"COMPRESSED_WORKLOAD_AND_ROAD_SEQUENCE_CONTEXT","NHL_MONEYLINE_CHALLENGER_FEATURE_MANIFEST_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_POPULATION_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_TEMPORAL_PROTOCOL_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_METRICS_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_SUCCESS_CRITERIA_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_UNCERTAINTY_PROTOCOL_FROZEN":"READY","NHL_MONEYLINE_CHALLENGER_SPECIFICATION_READINESS":"READY","NHL_MONEYLINE_CHALLENGER_EXECUTION_READINESS":"NOT_READY","NHL_MONEYLINE_MODEL_PROMOTION_READINESS":"NOT_READY","NHL_SEASON_2026_MAINLINE_OPERATIONAL_READINESS":"NOT_READY"}
 decision={"selected_challenger":hypothesis['challenger_name'],"decisions":decisions,"unlocked":["One separately authorized NHL full-game moneyline frozen champion-challenger execution of this exact specification"],"still_blocked":["challenger fitting or probability generation in this task","odds acquisition","ROI analysis","model promotion","production deployment","season 2026 operational restart"],"execution_boundary":"CHALLENGER_EXECUTION_NOT_AUTHORIZED_BY_THIS_PACKAGE"}; js(decision,out/f'nhl_moneyline_champion_challenger_specification_decision_{DATE}.json')
 text=f"""# NHL Moneyline Champion–Challenger Experiment Specification\n\n## Decision\n\nSelect exactly one additive challenger: **compressed workload and road-sequence context**, named `NHL_MONEYLINE_SCHEDULE_LOAD_CONTEXT_LOGIT_CHALLENGER_V1`. It retains the six champion fields and adds only `diff_games_prior_5d`, `home_consecutive_road_games_prior`, and `away_consecutive_road_games_prior`.\n\nThis family is `MODERATE_OVERLAP` overall: cumulative workload relates to rest and back-to-back status, but is not determined by them; road-sequence persistence is new location context. It avoids duplicating the dominant shot-differential signal. Richer team strength and recent form were not selected because overlap is high; opponent adjustment and special teams lack certified construction; goalie/lineup context remains prospective only.\n\n## Frozen execution contract\n\n- Champion: `{CHAMPION}`; stored prediction SHA256 `{CHAMP_HASH}`.\n- Challenger instrument: unchanged fit-only median imputation, fit-only standardization, L2 logistic regression (`C=1.0`, `liblinear`, seed `20260713`).\n- Population: exact 2,798 champion identities; fit 701, validation 699, holdout 1,398.\n- Primary metrics: Brier score, log loss, ROC AUC; accuracy is secondary.\n- Uncertainty: 5,000 paired calendar-date cluster bootstrap resamples, seed `20260713`, percentile 95% intervals.\n- Stability slices are frozen before execution: validation, holdout, combined out-of-time, calendar month, team, champion probability-margin band, and missingness state.\n\nThe required success gates are encoded exactly in the package. A tie, loss, mixed temporal result, or lineage failure cannot trigger tuning inside the experiment.\n\n## Season 2026 bridge and boundary\n\nThe selected fields are reproducible from daily official schedule/results data with pregame snapshots keyed by canonical season, game, team, and date. Goalie/lineup context remains a separate prospective candidate requiring timestamped collection.\n\n`CHALLENGER_EXECUTION_NOT_AUTHORIZED_BY_THIS_PACKAGE`\n"""
 (out/f'nhl_moneyline_champion_challenger_one_page_summary_{DATE}.md').write_text(text); (out/f'nhl_moneyline_champion_challenger_specification_report_{DATE}.md').write_text(text+'\n## Required decisions\n\n'+'\n'.join(f'- `{k}` = `{v}`' for k,v in decisions.items())+'\n')
 assert before=={str(f):sha(f) for p in pp.values() for f in p.iterdir() if f.is_file()}
 pkg={"package_name":"nhl_moneyline_champion_challenger_specification","version":"1.0.0","as_of_date":DATE,"generated_by":str(Path(__file__).relative_to(root)),"champion":CHAMPION,"selected_challenger":hypothesis['challenger_name'],"challenger_fit_count":0,"challenger_prediction_rows":0,"parent_manifest_sha256":{k:h for k,(_,h) in PARENTS.items()},"auxiliary_schedule_manifest_sha256":AUX_SCHEDULE_MANIFEST_HASH,"source_mutation_check":"PASS","execution_boundary":"CHALLENGER_EXECUTION_NOT_AUTHORIZED_BY_THIS_PACKAGE"}; js(pkg,out/f'package_identity_{DATE}.json')
 prohibited=[x for x in out.iterdir() if 'prediction' in x.name.lower() or 'coefficient' in x.name.lower()]; assert not prohibited
 files=sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'); (out/'SHA256SUMS').write_text(''.join(f'{sha(x)}  {x.name}\n' for x in files)); print(json.dumps({"output_dir":str(out),"selected_family":hypothesis['selected_family'],"feature_rows":len(fm),"manifest_sha256":sha(out/'SHA256SUMS'),"execution_authorized":False},indent=2))
if __name__=='__main__': main()
