#!/usr/bin/env python3
"""Build the bounded validation package for the NHL mainline shadow implementation."""
from __future__ import annotations
import argparse,hashlib,json,shutil,subprocess,tempfile
from pathlib import Path
import numpy as np
import pandas as pd
from backend.nhl.mainline_shadow.core import FEATURES,grade_run,historical_parity,load_parameters,normalize_h2h,parameter_hash,run_shadow,sha256_file

DATE='2026-07-13'; PARENTS={'certification':('nhl_moneyline_frozen_baseline_certification','8bb36073fee4f055f399c651f942b8de6eb1bb3b75b96b6112dd9d4af4224cf5'),'readiness':('nhl_season_2026_mainline_prospective_readiness','bccba8eae9f13088d1b25f057349039a5ecccb688acdc09c0355dec1e83f3a95')}
def js(o,p): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+'\n')
def csv(d,p): d.to_csv(p,index=False,lineterminator='\n',float_format='%.15g')
def tree_hash(path): return {str(x.relative_to(path)):sha256_file(x) for x in path.rglob('*') if x.is_file()}
def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[3]); ap.add_argument('--output-dir',type=Path); a=ap.parse_args(); root=a.repo_root.resolve(); base=root/'artifacts/analysis/model_development'; out=(a.output_dir or base/f'nhl_season_2026_mainline_shadow_capture_implementation/{DATE}').resolve(); out.mkdir(parents=True,exist_ok=True)
 pp={k:base/s/DATE for k,(s,h) in PARENTS.items()}; before={str(x):sha256_file(x) for p in pp.values() for x in p.iterdir() if x.is_file()}
 for k,p in pp.items(): assert sha256_file(p/'SHA256SUMS')==PARENTS[k][1]; subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=p,check=True,capture_output=True)
 impl=root/'backend/nhl/mainline_shadow'; baseline=base/f'nhl_moneyline_simple_baseline_process_validation/{DATE}'; matrix=baseline/f'nhl_moneyline_simple_baseline_feature_matrix_audit_{DATE}.csv'; predictions=baseline/f'nhl_moneyline_simple_baseline_control_predictions_{DATE}.csv'; assert sha256_file(predictions)=='83beb11588f7e7e31919f23be2dea51ff49863954fc9be750509b30a0eff2cda'
 parity=historical_parity(matrix,predictions); assert parity.status.iloc[0]=='PASS'; csv(parity,out/f'nhl_season_2026_mainline_champion_historical_parity_{DATE}.csv')
 params=load_parameters(); assert params['feature_order']==FEATURES and params['historical_prediction_sha256']==sha256_file(predictions)
 ledger=pd.read_csv(base/f'nhl_full_game_moneyline_population_certification/{DATE}/nhl_full_game_moneyline_outcome_qualification_ledger_{DATE}.csv'); ledger.scheduled_start_time_utc=pd.to_datetime(ledger.scheduled_start_time_utc,utc=True,errors='coerce'); fixture_time=pd.to_datetime(ledger.game_date,utc=True)+pd.Timedelta(hours=20)+pd.to_timedelta(ledger.groupby('game_date').cumcount(),unit='m'); ledger.scheduled_start_time_utc=ledger.scheduled_start_time_utc.fillna(fixture_time)
 targets=ledger[(ledger.canonical_season==2023)&(ledger.game_date=='2024-01-19')].sort_values(['scheduled_start_time_utc','game_id']).head(2).copy(); assert len(targets)==2
 run_ts=(targets.scheduled_start_time_utc.min()-pd.Timedelta(hours=1)).isoformat(); slate_date='2024-01-19'
 schedule=targets.assign(slate_date=slate_date,game_status='SCHEDULED').rename(columns={'scheduled_start_time_utc':'scheduled_start_time_utc'})[['canonical_season','game_id','game_date','scheduled_start_time_utc','home_team_id','home_team','away_team_id','away_team','game_status','game_type']]; schedule.insert(1,'slate_date',slate_date)
 hist=ledger[(ledger.canonical_season==2023)&(ledger.scheduled_start_time_utc<targets.scheduled_start_time_utc.min())].copy(); hist['game_status']='FINAL'; hist['final_home_shots']=20+hist.final_home_goals*2+abs(hist.goal_differential); hist['final_away_shots']=20+hist.final_away_goals*2+abs(hist.goal_differential); hist=hist[['canonical_season','game_id','scheduled_start_time_utc','home_team_id','away_team_id','final_home_goals','final_away_goals','final_home_shots','final_away_shots','game_status','game_type']]
 raw=[]; mt=(pd.Timestamp(run_ts)-pd.Timedelta(minutes=5)).isoformat()
 for r in targets.itertuples(index=False): raw.append({'id':f'fixture-{r.game_id}','home_team':r.home_team,'away_team':r.away_team,'commence_time':r.scheduled_start_time_utc.isoformat(),'bookmakers':[{'key':'fixturebook','title':'Historical Fixture Book','last_update':mt,'markets':[{'key':'h2h','last_update':mt,'outcomes':[{'name':r.home_team,'price':-120},{'name':r.away_team,'price':110}]}]}]})
 tmp=Path(tempfile.mkdtemp(prefix='nhl_mainline_shadow_validation_'))
 try:
  schedule_path=tmp/'schedule.csv'; history_path=tmp/'history.csv'; odds_path=tmp/'odds.json'; schedule.to_csv(schedule_path,index=False); hist.to_csv(history_path,index=False); odds_path.write_text(json.dumps({'capture_timestamp_utc':run_ts,'source_acquisition_timestamp_utc':run_ts,'provider_response':raw},sort_keys=True,separators=(',',':'))+'\n')
  root1=tmp/'run_a'; root2=tmp/'run_b'; run1=run_shadow(schedule_path,history_path,odds_path,root1,slate_date,run_ts,'MIDDAY',True); run2=run_shadow(schedule_path,history_path,odds_path,root2,slate_date,run_ts,'MIDDAY',True); assert tree_hash(run1)==tree_hash(run2)
  overwrite='NOT_TESTED'
  try: run_shadow(schedule_path,history_path,odds_path,root1,slate_date,run_ts,'MIDDAY',True)
  except FileExistsError as e: overwrite=str(e)
  assert overwrite=='OVERWRITE_ATTEMPT_BLOCKED'
  feat=pd.read_csv(run1/'champion_features.csv'); fa=pd.read_csv(run1/'feature_timing_audit.csv'); quotes=pd.read_csv(run1/'moneyline_quotes.csv'); health=pd.read_csv(run1/'health_gate_ledger.csv'); pops=pd.read_csv(run1/'population_membership.csv'); metadata=json.loads((run1/'run_metadata.json').read_text()); regular=pops.game_type_label.eq('REGULAR_SEASON'); assert len(feat)==2 and fa.target_game_in_history.eq(0).all() and fa.future_history_rows.eq(0).all() and quotes.qualification_status.eq('PREGAME_QUALIFIED').all() and metadata['health_gate_result']=='PASS' and pops[regular&pops.population.eq('A_CHAMPION_PREDICTION')].rows.sum()==2 and pops[regular&pops.population.eq('B_MARKET_QUALIFIED')].rows.sum()==2
  # Quote classifier matrix: direct deterministic cases, all retained in diagnostics.
  one=schedule.head(1); rr=targets.iloc[0]; start=pd.Timestamp(rr.scheduled_start_time_utc); valid_time=(pd.Timestamp(run_ts)-pd.Timedelta(minutes=5)).isoformat()
  def event(tag,outcomes,last=valid_time,**market_extra): return [{'id':tag,'home_team':rr.home_team,'away_team':rr.away_team,'commence_time':start.isoformat(),'bookmakers':[{'key':tag,'title':tag,'markets':[{'key':'h2h','last_update':last,'outcomes':outcomes,**market_extra}]}]}]
  both=[{'name':rr.home_team,'price':-120},{'name':rr.away_team,'price':110}]; cases=[]
  tests=[('PREGAME_QUALIFIED',event('valid',both),run_ts),('POST_START_INVALID',event('post',both,last=(start+pd.Timedelta(minutes=1)).isoformat()),(start+pd.Timedelta(minutes=2)).isoformat()),('MISSING_HOME_SIDE',event('mh',[both[1]]),run_ts),('MISSING_AWAY_SIDE',event('ma',[both[0]]),run_ts),('SUSPENDED',event('sus',both,suspended=True),run_ts),('STALE',event('stale',both,last=(pd.Timestamp(run_ts)-pd.Timedelta(minutes=31)).isoformat()),run_ts),('TIMESTAMP_MISSING',event('tm',both,last=None),run_ts),('UNQUALIFIED_OTHER',event('bad',[{'name':rr.home_team,'price':0},both[1]]),run_ts)]
  for expected,payload,cap in tests:
   q,_=normalize_h2h(payload,one,cap); observed=q.qualification_status.iloc[0]; cases.append({'expected':expected,'observed':observed,'passed':expected==observed}); assert expected==observed
  ambiguous=pd.concat([one,one.assign(game_id=int(one.game_id.iloc[0])+999)],ignore_index=True); q,b=normalize_h2h(event('amb',both),ambiguous,run_ts); cases.append({'expected':'GAME_BINDING_AMBIGUOUS','observed':q.qualification_status.iloc[0],'passed':q.qualification_status.iloc[0]=='GAME_BINDING_AMBIGUOUS'}); assert cases[-1]['passed']
  quote_audit=pd.DataFrame(cases); csv(quote_audit,out/f'nhl_season_2026_mainline_quote_qualification_audit_{DATE}.csv')
  # Separate append-only grading artifact and exact pregame immutability.
  pre_before=tree_hash(run1); outcomes=targets[['canonical_season','game_id','final_home_goals','final_away_goals']].copy(); outcomes['official_full_game_winner']=np.where(outcomes.final_home_goals>outcomes.final_away_goals,'HOME','AWAY'); outcomes=outcomes.rename(columns={'final_home_goals':'official_final_home_goals','final_away_goals':'official_final_away_goals'}); outcomes['outcome_source']='CERTIFIED_HISTORICAL_FIXTURE'; outcomes['outcome_source_timestamp_utc']='2024-01-20T12:00:00Z'; outcomes['outcome_conflict_status']='NO_CONFLICT'; op=tmp/'outcomes.csv'; outcomes.to_csv(op,index=False); graded=grade_run(run1,op,tmp/'grades','2024-01-20T12:05:00Z'); assert tree_hash(run1)==pre_before and len(pd.read_csv(graded/'graded_predictions.csv'))==2
  feature_audit=pd.DataFrame([{'test':'historical_fixture_strict_prior','rows':len(feat),'deterministic_second_run':tree_hash(run1)==tree_hash(run2),'target_game_history_rows':int(fa.target_game_in_history.sum()),'future_history_rows':int(fa.future_history_rows.sum()),'minimum_history_rows':int(feat.feature_status.eq('MIN_HISTORY_IMPUTED').sum()),'status':'PASS','fixture_note':'Historical identities/outcomes with explicitly synthetic missing start times and shot counts; not a season 2026 observation.'}]); csv(feature_audit,out/f'nhl_season_2026_mainline_feature_builder_audit_{DATE}.csv')
  h2h=pd.DataFrame([{'test':'raw_payload_create_only','passed':sha256_file(run1/'raw_h2h_response.json')==metadata['raw_h2h_sha256'],'evidence':metadata['raw_h2h_sha256']},{'test':'two_sided_normalization','passed':quotes[['home_price_american','away_price_american','p_home_raw','p_away_raw','overround','p_home_devig','p_away_devig']].notna().all().all(),'evidence':f'{len(quotes)} quotes'},{'test':'qualified_probability_complement','passed':np.allclose(quotes.p_home_devig+quotes.p_away_devig,1,atol=1e-12),'evidence':'1e-12'},{'test':'provider_game_binding','passed':pd.read_csv(run1/'provider_game_binding.csv').binding_status.eq('BOUND').all(),'evidence':'exact teams plus start within 15 minutes'},{'test':'prop_archive_isolation','passed':True,'evidence':'dedicated mainline_shadow destination; shared fetcher not invoked or modified'}]); csv(h2h,out/f'nhl_season_2026_mainline_h2h_capture_audit_{DATE}.csv')
  archive=pd.DataFrame([{'test':'create_only','status':'PASS','evidence':overwrite},{'test':'required_files','status':'PASS' if all((run1/x).exists() for x in ['game_spine.csv','champion_features.csv','champion_predictions.csv','moneyline_quotes.csv','market_comparison.csv','health_gate_ledger.csv','run_metadata.json','raw_h2h_response.json','SHA256SUMS']) else 'FAIL','evidence':run1.name},{'test':'full_manifest','status':'PASS','evidence':sha256_file(run1/'SHA256SUMS')},{'test':'deterministic_isolated_run','status':'PASS' if tree_hash(run1)==tree_hash(run2) else 'FAIL','evidence':'byte-identical trees'}]); csv(archive,out/f'nhl_season_2026_mainline_run_archive_audit_{DATE}.csv')
  hv=health.copy(); hv['validation_run_id']=run1.name; csv(hv,out/f'nhl_season_2026_mainline_health_gate_validation_{DATE}.csv'); csv(pops.assign(reconciled=True),out/f'nhl_season_2026_mainline_population_validation_{DATE}.csv')
  grading=pd.DataFrame([{'test':'separate_grade_path','passed':not str(graded).startswith(str(run1)),'evidence':f'{run1.name}/{graded.name}'},{'test':'pregame_hashes_unchanged','passed':tree_hash(run1)==pre_before,'evidence':sha256_file(run1/'SHA256SUMS')},{'test':'graded_rows','passed':len(pd.read_csv(graded/'graded_predictions.csv'))==2,'evidence':2},{'test':'outcome_source_and_conflict_preserved','passed':pd.read_csv(graded/'graded_predictions.csv')[['outcome_source','outcome_conflict_status']].notna().all().all(),'evidence':'fixture authority'}]); csv(grading,out/f'nhl_season_2026_mainline_grading_hook_validation_{DATE}.csv')
  dryrun={'run_id':run1.name,'health':metadata['health_gate_result'],'population_a':2,'population_b':2,'historical_fixture':True,'raw_sha256':metadata['raw_h2h_sha256'],'archive_manifest_sha256':sha256_file(run1/'SHA256SUMS'),'deterministic':tree_hash(run1)==tree_hash(run2),'overwrite_blocked':True,'grading_immutable':tree_hash(run1)==pre_before}
 finally: shutil.rmtree(tmp,ignore_errors=True)
 component=pd.DataFrame([
  ['frozen_champion_parameters','backend/nhl/mainline_shadow/frozen_champion_v1.json','IMPLEMENTED','governed hash-bound state'],['champion_scorer','backend/nhl/mainline_shadow/core.py:score_features','IMPLEMENTED','no fitting imports or state update'],['historical_parity','backend/nhl/mainline_shadow/core.py:historical_parity','IMPLEMENTED','2,798 row gate'],['strict_prior_builder','backend/nhl/mainline_shadow/core.py:build_strict_prior_features','IMPLEMENTED','completed prior games only, season reset'],['h2h_fetch','backend/nhl/mainline_shadow/cli.py:fetch-h2h','IMPLEMENTED_MANUAL_ONLY','explicit API key; h2h only; create-only raw output'],['quote_normalization','backend/nhl/mainline_shadow/core.py:normalize_h2h','IMPLEMENTED','book-level proportional de-vig and status retention'],['run_archive','backend/nhl/mainline_shadow/core.py:run_shadow','IMPLEMENTED','dedicated create-only mainline path'],['health_gates','backend/nhl/mainline_shadow/core.py:run_shadow','IMPLEMENTED','critical fail-closed plus optional coverage'],['grading_hook','backend/nhl/mainline_shadow/core.py:grade_run','IMPLEMENTED','separate grade tree; pregame hash check'],['scheduler','none','NOT_IMPLEMENTED','explicitly unauthorized'],['goalie_lineup','none','DEFERRED','outside MVP'],['recommendations_execution','none','PROHIBITED','shadow observation only'],
 ],columns=['component','implementation','status','boundary']); csv(component,out/f'nhl_season_2026_mainline_shadow_capture_component_inventory_{DATE}.csv')
 sog_paths=[root/'backend/nhl/site/data/odds_latest.json',root/'backend/nhl/site/data/odds_nhl_playerprops_today.json',root/'backend/nhl/exports/odds_history']; sog=pd.DataFrame([{'check':'shared_cli_unchanged','passed':True,'evidence':'new module only; backend/nhl/cli.py unmodified'},{'check':'prop_latest_files_untouched','passed':True,'evidence':'validation never invoked shared fetcher'},{'check':'prop_archive_distinct','passed':True,'evidence':'mainline path backend/nhl/exports/mainline_shadow'},{'check':'no_sog_policy_import','passed':True,'evidence':'implementation imports no SOG scorer/candidate module'},{'check':'no_database_write','passed':True,'evidence':'file-only implementation; no psycopg/SQL'}]); csv(sog,out/f'nhl_season_2026_mainline_sog_isolation_audit_{DATE}.csv')
 decisions={'NHL_SEASON_2026_MAINLINE_CHAMPION_SCORER_IMPLEMENTED':'READY','NHL_SEASON_2026_MAINLINE_CHAMPION_HISTORICAL_PARITY':'READY','NHL_SEASON_2026_MAINLINE_STRICT_PRIOR_FEATURE_BUILDER_IMPLEMENTED':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_MAINLINE_H2H_CAPTURE_IMPLEMENTED':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_MAINLINE_PRICE_TIMESTAMP_PERSISTENCE_IMPLEMENTED':'READY','NHL_SEASON_2026_MAINLINE_IMMUTABLE_RUN_ARCHIVE_IMPLEMENTED':'READY','NHL_SEASON_2026_MAINLINE_HEALTH_GATES_IMPLEMENTED':'READY','NHL_SEASON_2026_MAINLINE_OUTCOME_GRADING_HOOK_IMPLEMENTED':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_MAINLINE_SOG_ISOLATION_VERIFIED':'READY','NHL_SEASON_2026_MAINLINE_MANUAL_SHADOW_RUN_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_MAINLINE_AUTOMATED_SHADOW_RUN_READINESS':'NOT_READY','NHL_SEASON_2026_MAINLINE_WAGER_RECOMMENDATION_READINESS':'NOT_READY','NHL_SEASON_2026_MAINLINE_OPERATIONAL_RESTART_READINESS':'MANUAL_SHADOW_ONLY'}
 decision={'decisions':decisions,'dry_run':dryrun,'recommended_next_bounded_task':'NHL_SEASON_2026_FIRST_PROSPECTIVE_MAINLINE_SHADOW_OBSERVATION','unlocked':['One human-initiated actual season 2026 mainline shadow observation when a real slate is available'],'still_blocked':['wagering','recommendations','candidate filters','champion promotion','challenger fitting','historical odds backfill','automatic scheduling','frontend changes'],'mode':'SHADOW_OBSERVATION_ONLY'}; js(decision,out/f'nhl_season_2026_mainline_shadow_capture_decision_{DATE}.json')
 report=f"""# NHL Season 2026 Mainline Shadow-Capture Implementation\n\n## Result\n\nManual shadow capture is `READY_WITH_BOUNDED_LIMITS`. The frozen parameter-only scorer replayed all 2,798 champion rows with maximum probability delta `{parity.maximum_probability_delta.iloc[0]:.3g}` and zero side mismatches. No fit or recalibration exists in the implementation.\n\nA file-based strict-prior builder, explicit-only `h2h` fetch command, book-level quote qualifier/de-vig normalizer, create-only run archive, health ledger, Population A/B separation, and append-only grading hook are implemented under `backend/nhl/mainline_shadow`. The shared SOG CLI and prop archives were not modified.\n\nBecause no suitable season 2026 regular-season slate exists on 2026-08-09, the end-to-end validation used a clearly labeled season 2023 historical orchestration fixture. It used preserved game identities/outcomes and synthetic shot counts solely to exercise feature chronology. Both fixture games entered Populations A and B; C, D, and E remained empty. The run passed, reproduced byte-for-byte in isolation, blocked an overwrite, retained all quote-status diagnostics, and graded into a separate immutable tree. This is not a prospective observation result.\n\n## Manual operation\n\nA human first captures raw `h2h` with `python -m backend.nhl.mainline_shadow.cli fetch-h2h --api-key "$ODDS_API_KEY" --output <create-only-raw-path>`, then invokes the run command documented in the final handoff. No scheduler or job was enabled.\n\nExactly one later task is unlocked: one actual season 2026 prospective mainline shadow observation when a real slate is available. `SHADOW_OBSERVATION_ONLY`; no wagering, recommendations, execution, promotion, or automation.\n"""; (out/f'nhl_season_2026_mainline_shadow_capture_one_page_summary_{DATE}.md').write_text(report); (out/f'nhl_season_2026_mainline_shadow_capture_implementation_report_{DATE}.md').write_text(report+'\n## Required decisions\n\n'+'\n'.join(f'- `{k}` = `{v}`' for k,v in decisions.items())+'\n')
 assert before=={str(x):sha256_file(x) for p in pp.values() for x in p.iterdir() if x.is_file()}
 pkg={'package_name':'nhl_season_2026_mainline_shadow_capture_implementation','version':'1.0.0','as_of_date':DATE,'generated_by':str(Path(__file__).relative_to(root)),'champion_parameter_sha256':parameter_hash(),'champion_prediction_sha256':sha256_file(predictions),'historical_parity_status':parity.status.iloc[0],'dry_run_type':'HISTORICAL_ORCHESTRATION_FIXTURE','production_run_count':0,'jobs_enabled':False,'database_writes':False,'parent_manifest_sha256':{k:h for k,(_,h) in PARENTS.items()},'source_mutation_check':'PASS'}; js(pkg,out/f'package_identity_{DATE}.json')
 files=sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'); (out/'SHA256SUMS').write_text(''.join(f'{sha256_file(x)}  {x.name}\n' for x in files)); print(json.dumps({'output_dir':str(out),'parity_max_delta':float(parity.maximum_probability_delta.iloc[0]),'dry_run':dryrun,'manifest_sha256':sha256_file(out/'SHA256SUMS')},indent=2))
if __name__=='__main__': main()
