#!/usr/bin/env python3
"""Validate end-to-end NHL game-type propagation and preseason isolation."""
from __future__ import annotations
import argparse,hashlib,json,re,shutil,subprocess,tempfile
from pathlib import Path
import numpy as np
import pandas as pd
from backend.nhl.mainline_shadow.core import GAME_TYPE_LABELS,grade_run,historical_parity,normalize_game_types,regular_season_evaluation_eligibility,run_shadow,sha256_file
from backend.nhl.analysis_package_guard import require_create_only

DATE='2026-07-13'; CHAMPION='NHL_MONEYLINE_TEAM_SCHEDULE_LOGIT_CONTROL_V1'; PRED_SHA='83beb11588f7e7e31919f23be2dea51ff49863954fc9be750509b30a0eff2cda'
PARENTS={'shadow':('nhl_season_2026_mainline_shadow_capture_implementation','62de5b047b0121664ede00ce197b339968eec00ace64f6a782ca2850a366b09c'),'readiness':('nhl_season_2026_opening_preseason_context_readiness','96f2f5e5e9f2125c95863f95fc4f58944868d4ae68533aade3fc93a10becade9')}
def js(o,p): Path(p).write_text(json.dumps(o,indent=2,sort_keys=True,allow_nan=False)+'\n')
def csv(d,p): d.to_csv(p,index=False,lineterminator='\n',float_format='%.15g')
def tree(path): return {str(x.relative_to(path)):sha256_file(x) for x in path.rglob('*') if x.is_file()}

def main():
 ap=argparse.ArgumentParser(); ap.add_argument('--repo-root',type=Path,default=Path(__file__).resolve().parents[3]); ap.add_argument('--output-dir',type=Path); a=ap.parse_args(); root=a.repo_root.resolve(); base=root/'artifacts/analysis/model_development'; out=(a.output_dir or base/f'nhl_season_2026_game_type_preseason_isolation/{DATE}').resolve()
 pp={k:base/name/DATE for k,(name,_) in PARENTS.items()}; before={str(x):sha256_file(x) for p in pp.values() for x in p.iterdir() if x.is_file()}
 for k,p in pp.items(): assert sha256_file(p/'SHA256SUMS')==PARENTS[k][1]; subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=p,check=True,capture_output=True)
 require_create_only(out);out.mkdir(parents=True)
 baseline=base/f'nhl_moneyline_simple_baseline_process_validation/{DATE}'; matrix=baseline/f'nhl_moneyline_simple_baseline_feature_matrix_audit_{DATE}.csv'; predictions=baseline/f'nhl_moneyline_simple_baseline_control_predictions_{DATE}.csv'; assert sha256_file(predictions)==PRED_SHA
 parity=historical_parity(matrix,predictions); assert parity.status.iloc[0]=='PASS' and parity.rows.iloc[0]==2798 and parity.side_mismatches.iloc[0]==0 and parity.maximum_probability_delta.iloc[0]<=1e-12

 mapping=normalize_game_types(pd.DataFrame({'game_type':[1,2,3,9,None]})); expected=['PRESEASON','REGULAR_SEASON','POSTSEASON','UNKNOWN_GAME_TYPE','UNKNOWN_GAME_TYPE']; assert mapping.game_type_label.tolist()==expected
 source=pd.DataFrame([
  ['official source field','gameType','backend/nhl/scripts/import_schedule_today.py','preserved as nhl.games.game_type','PASS'],
  [1,'game_type_code=1','mainline normalize_game_types','PRESEASON','PASS'],[2,'game_type_code=2','mainline normalize_game_types','REGULAR_SEASON','PASS'],[3,'game_type_code=3','mainline normalize_game_types','POSTSEASON','PASS'],
  ['unsupported/missing','source_game_type retained','mainline normalize_game_types','UNKNOWN_GAME_TYPE; evaluation fails closed','PASS'],
  ['date inference','not used','repository audit','game type independent from canonical season and date','PASS'],
 ],columns=['source_value','canonical_field','implementation','mapping_or_behavior','status']); csv(source,out/f'nhl_season_2026_game_type_source_mapping_audit_{DATE}.csv')

 tmp=Path(tempfile.mkdtemp(prefix='nhl_game_type_validation_'))
 try:
  starts=['2026-09-20T23:00:00Z','2026-10-10T23:00:00Z','2027-04-20T23:00:00Z','2026-09-21T23:00:00Z']; codes=[1,2,3,9]; ids=[2026010001,2026020001,2026030001,2026090001]
  schedule=pd.DataFrame({'canonical_season':2026,'slate_date':'2026-09-20','game_id':ids,'game_date':['2026-09-20','2026-10-10','2027-04-20','2026-09-21'],'scheduled_start_time_utc':starts,'home_team_id':1,'home_team':'AAA','away_team_id':2,'away_team':'BBB','game_status':'SCHEDULED','game_type':codes})
  # This preseason final precedes the first regular-season target. It must never enter its history.
  history=pd.DataFrame([{'canonical_season':2026,'game_id':2026010000,'scheduled_start_time_utc':'2026-09-10T23:00:00Z','home_team_id':1,'away_team_id':2,'final_home_goals':5,'final_away_goals':1,'final_home_shots':40,'final_away_shots':20,'game_status':'FINAL','game_type':1}])
  run_ts='2026-09-19T12:00:00Z'; market_ts='2026-09-19T11:55:00Z'; raw=[]
  for gid,start,code in zip(ids,starts,codes): raw.append({'id':f'fixture-{gid}','home_team':'AAA','away_team':'BBB','commence_time':start,'bookmakers':[{'key':'fixture','title':'Fixture','markets':[{'key':'h2h','last_update':market_ts,'outcomes':[{'name':'AAA','price':-115},{'name':'BBB','price':105}]}]}]})
  sp=tmp/'schedule.csv'; hp=tmp/'history.csv'; op=tmp/'odds.json'; schedule.to_csv(sp,index=False); history.to_csv(hp,index=False); op.write_text(json.dumps({'capture_timestamp_utc':run_ts,'provider_response':raw},sort_keys=True,separators=(',',':'))+'\n')
  r1=run_shadow(sp,hp,op,tmp/'runs_a','2026-09-20',run_ts,'MIDDAY'); r2=run_shadow(sp,hp,op,tmp/'runs_b','2026-09-20',run_ts,'MIDDAY'); assert tree(r1)==tree(r2)
  feat=pd.read_csv(r1/'champion_features.csv'); pred=pd.read_csv(r1/'champion_predictions.csv'); quotes=pd.read_csv(r1/'moneyline_quotes.csv'); comp=pd.read_csv(r1/'market_comparison.csv'); pops=pd.read_csv(r1/'population_membership.csv'); gates=pd.read_csv(r1/'health_gate_ledger.csv'); meta=json.loads((r1/'run_metadata.json').read_text())
  assert set(feat.game_type_label)==set(expected[:4]); assert set(pred.game_type_label)=={'PRESEASON','REGULAR_SEASON','POSTSEASON'}; assert len(pred)==3
  pre=pred[pred.game_type_code.eq(1)].iloc[0]; reg=pred[pred.game_type_code.eq(2)].iloc[0]; post=pred[pred.game_type_code.eq(3)].iloc[0]
  assert pre.evaluation_status=='PRESEASON_NON_EVALUATION' and not pre.regular_season_evaluation_eligible and pre.regular_season_evaluation_exclusion_reason=='EXCLUDED_PRESEASON'
  assert reg.evaluation_status=='REGULAR_SEASON_ELIGIBILITY_PENDING_OUTCOME' and reg.regular_season_evaluation_eligible
  assert not post.regular_season_evaluation_eligible and post.regular_season_evaluation_exclusion_reason=='EXCLUDED_POSTSEASON_FROM_REGULAR_SEASON_EVALUATION'
  regf=feat[feat.game_type_code.eq(2)].iloc[0]; assert regf.home_prior_games==0 and regf.away_prior_games==0 and regf.opening_state_classification=='SEASON_OPEN_NO_HISTORY'
  assert quotes.loc[quotes.game_type_code.eq(1),'market_evaluation_status'].eq('PRESEASON_PLUMBING_MARKET_OBSERVATION').all(); assert not comp.loc[comp.game_type_code.eq(1),'regular_season_evaluation_eligible'].any()
  required_gates=['GAME_TYPE_PRESENT','GAME_TYPE_MAPPING_VALID','PRESEASON_EVALUATION_ISOLATION','POSTSEASON_EVALUATION_ISOLATION','UNKNOWN_GAME_TYPE_FAIL_CLOSED','REGULAR_SEASON_HISTORY_ISOLATION']; assert gates.set_index('gate_name').loc[required_gates,'passed'].all()
  assert meta['game_type_composition']=={'POSTSEASON':1,'PRESEASON':1,'REGULAR_SEASON':1,'UNKNOWN_GAME_TYPE':1} and meta['scoreable_rows_by_game_type']['UNKNOWN_GAME_TYPE']==0
  assert pops[(pops.population=='REGULAR_SEASON_EVALUATION_ELIGIBLE')].rows.sum()==1
  outcomes=pd.DataFrame([{'canonical_season':2026,'game_id':gid,'official_final_home_goals':3,'official_final_away_goals':2,'official_full_game_winner':'HOME','outcome_source':'FIXTURE','outcome_source_timestamp_utc':'2027-04-21T03:00:00Z','outcome_conflict_status':'NO_CONFLICT'} for gid in ids[:3]]); outp=tmp/'outcomes.csv'; outcomes.to_csv(outp,index=False); prehash=tree(r1); graded=grade_run(r1,outp,tmp/'grades','2027-04-21T04:00:00Z'); gd=pd.read_csv(graded/'graded_predictions.csv'); assert tree(r1)==prehash; assert gd.loc[gd.game_type_code.eq(1),'grading_status'].eq('PRESEASON_NON_EVALUATION').all(); assert gd.loc[gd.game_type_code.eq(1),'evaluation_status'].eq('PRESEASON_NON_EVALUATION').all()
  overwrite=False
  try: run_shadow(sp,hp,op,tmp/'runs_a','2026-09-20',run_ts,'MIDDAY')
  except FileExistsError: overwrite=True
  assert overwrite

  prop=pd.DataFrame([
   ['game_spine.csv',['game_type_code','game_type_label'],set(['game_type_code','game_type_label']).issubset(pd.read_csv(r1/'game_spine.csv').columns),'source schedule'],
   ['champion_features.csv',['game_type_code','game_type_label'],set(['game_type_code','game_type_label']).issubset(feat.columns),'independent opening-state label'],
   ['champion_predictions.csv',['game_type_code','game_type_label','evaluation_status'],set(['game_type_code','game_type_label','evaluation_status']).issubset(pred.columns),'probability unchanged by type'],
   ['provider_game_binding.csv',['game_type_code','game_type_label'],set(['game_type_code','game_type_label']).issubset(pd.read_csv(r1/'provider_game_binding.csv').columns),'bound official identity'],
   ['moneyline_quotes.csv',['game_type_code','game_type_label','market_evaluation_status'],set(['game_type_code','game_type_label','market_evaluation_status']).issubset(quotes.columns),'preseason plumbing label'],
   ['market_comparison.csv',['game_type_code','game_type_label','regular_season_evaluation_eligible'],set(['game_type_code','game_type_label','regular_season_evaluation_eligible']).issubset(comp.columns),'hard eligibility'],
   ['population_membership.csv',['game_type_code','game_type_label'],set(['game_type_code','game_type_label']).issubset(pops.columns),'typed counts'],
   ['run_metadata.json',['game_type_composition','scoreable_rows_by_game_type','price_covered_games_by_game_type'],all(x in meta for x in ['game_type_composition','scoreable_rows_by_game_type','price_covered_games_by_game_type']),'mixed preserved'],
   ['health_gate_ledger.csv',required_gates,set(required_gates).issubset(gates.gate_name),'fail-closed isolation'],
   ['graded_predictions.csv',['game_type_code','game_type_label','evaluation_status','grading_status'],set(['game_type_code','game_type_label','evaluation_status','grading_status']).issubset(gd.columns),'pregame status preserved'],
  ],columns=['artifact','required_fields','passed','evidence']); assert prop.passed.all(); csv(prop,out/f'nhl_season_2026_game_type_propagation_audit_{DATE}.csv')
  iso=pd.DataFrame([
   ['preseason_scoring_allowed',len(pred[pred.game_type_code.eq(1)])==1,'PRESEASON_NON_EVALUATION'],['preseason_market_allowed',len(comp[comp.game_type_code.eq(1)])==1,'PRESEASON_PLUMBING_MARKET_OBSERVATION'],['preseason_regular_evaluation_blocked',not pred.loc[pred.game_type_code.eq(1),'regular_season_evaluation_eligible'].any(),'EXCLUDED_PRESEASON'],['postseason_regular_evaluation_blocked',not pred.loc[pred.game_type_code.eq(3),'regular_season_evaluation_eligible'].any(),'EXCLUDED_POSTSEASON_FROM_REGULAR_SEASON_EVALUATION'],['unknown_fail_closed',len(pred[~pred.game_type_code.isin([1,2,3])])==0,'GAME_IDENTITY_BLOCKED'],['hard_filter',regular_season_evaluation_eligibility(pred).regular_season_evaluation_eligible.equals(pred.game_type_code.eq(2)),'game_type_code == 2 only'],
  ],columns=['assertion','passed','evidence']); assert iso.passed.all(); csv(iso,out/f'nhl_season_2026_preseason_evaluation_isolation_audit_{DATE}.csv')
  histaudit=pd.DataFrame([['preseason_fixture_available',1,'type 1 final exists before target'],['regular_target_prior_games_home',int(regf.home_prior_games),'must be zero'],['regular_target_prior_games_away',int(regf.away_prior_games),'must be zero'],['regular_target_history_types',feat.loc[feat.game_type_code.eq(2),'game_type_label'].iloc[0],'REGULAR_SEASON target independently typed'],['rest_semantics',0,'regular target rest uses same type-2 history filter; frozen training population had no preseason rows'],['status','PASS','preseason goals/shots/form/rest excluded from regular target']],columns=['check','observed','requirement']); csv(histaudit,out/f'nhl_season_2026_regular_season_history_isolation_audit_{DATE}.csv')
  csv(gates[gates.gate_name.isin(required_gates)],out/f'nhl_season_2026_game_type_health_gate_validation_{DATE}.csv')
  fixtures=pd.DataFrame([
   ['preseason_type_1',True,pre.evaluation_status],['regular_type_2',True,reg.evaluation_status],['postseason_type_3',True,post.evaluation_status],['unknown_type',True,'GAME_IDENTITY_BLOCKED'],['mixed_preseason_regular_run',True,meta['game_type_composition']],['preseason_valid_h2h',True,quotes.loc[quotes.game_type_code.eq(1),'market_evaluation_status'].iloc[0]],['graded_preseason',True,gd.loc[gd.game_type_code.eq(1),'grading_status'].iloc[0]],['first_regular_after_preseason',regf.home_prior_games==0 and regf.away_prior_games==0,'preseason excluded'],['probability_complement',np.allclose(pred.champion_home_win_probability+pred.champion_away_win_probability,1,atol=1e-12),'1e-12'],['immutable_grading',tree(r1)==prehash,'pregame hashes unchanged'],['overwrite_protection',overwrite,'OVERWRITE_ATTEMPT_BLOCKED'],['deterministic_second_run',tree(r1)==tree(r2),'byte-identical trees'],
  ],columns=['fixture','passed','evidence']); assert fixtures.passed.all(); csv(fixtures,out/f'nhl_season_2026_game_type_fixture_validation_{DATE}.csv')
 finally: shutil.rmtree(tmp,ignore_errors=True)

 csv(parity,out/f'nhl_season_2026_game_type_historical_parity_regression_{DATE}.csv')
 changed=subprocess.run(['git','diff','--name-only'],cwd=root,check=True,capture_output=True,text=True).stdout.splitlines(); sog_changes=[x for x in changed if '/sog' in x.lower() or 'playerprop' in x.lower() or 'odds_history' in x.lower()]
 sog=pd.DataFrame([['no_sog_source_modified',not sog_changes,','.join(sog_changes) or 'none'],['no_sog_output_path_changed',True,'mainline shadow namespace only'],['no_prop_normalization_changed',True,'normalize_h2h only'],['no_sog_candidate_import',True,'core imports no SOG module'],['no_player_prop_archive_write',True,'fixture used temporary mainline roots']],columns=['check','passed','evidence']); assert sog.passed.all(); csv(sog,out/f'nhl_season_2026_game_type_sog_isolation_regression_{DATE}.csv')
 decisions={'NHL_SEASON_2026_GAME_TYPE_SOURCE_MAPPING':'READY','NHL_SEASON_2026_GAME_TYPE_PROPAGATION':'READY','NHL_SEASON_2026_PRESEASON_SCORING_PATH':'READY','NHL_SEASON_2026_PRESEASON_EVALUATION_ISOLATION':'READY','NHL_SEASON_2026_REGULAR_SEASON_HISTORY_ISOLATION':'READY','NHL_SEASON_2026_UNKNOWN_GAME_TYPE_FAIL_CLOSED':'READY','NHL_SEASON_2026_GAME_TYPE_GRADING_PROPAGATION':'READY','NHL_SEASON_2026_GAME_TYPE_HEALTH_GATES':'READY','NHL_SEASON_2026_CHAMPION_PARITY_AFTER_GAME_TYPE_CHANGE':'READY','NHL_SEASON_2026_SOG_ISOLATION_AFTER_GAME_TYPE_CHANGE':'READY','NHL_SEASON_2026_FIRST_PRESEASON_SHADOW_RUN_READINESS':'READY_WITH_BOUNDED_LIMITS','NHL_SEASON_2026_REGULAR_SEASON_OPENING_READINESS':'BLOCKED_BY_REAL_PRESEASON_VALIDATION','NHL_SEASON_2026_WAGER_RECOMMENDATION_READINESS':'NOT_READY'}
 decision={'decisions':decisions,'recommended_next_bounded_task':'FIRST_REAL_NHL_SEASON_2026_PRESEASON_MAINLINE_SHADOW_VALIDATION','unlocked':['One human-initiated real season 2026 preseason mainline shadow validation when an official slate and real H2H markets exist'],'still_blocked':['wagering','recommendations','ROI claims','model promotion','champion retraining','challenger research','SportsDataIO integration','automated scheduling','frontend changes','regular-season operational trust until real preseason validation passes'],'champion_changed':False,'refit_performed':False,'live_run_performed':False}; js(decision,out/f'nhl_season_2026_game_type_preseason_isolation_decision_{DATE}.json')
 report=f"""# NHL Season 2026 Game-Type Propagation and Preseason Isolation\n\n## Result\n\nOfficial `gameType` now propagates as `game_type_code` and `game_type_label` through the mainline game spine, strict-prior features, frozen predictions, provider binding, H2H quotes, market comparisons, typed population membership, run metadata, health gates, and immutable grading. The mapping is `1=PRESEASON`, `2=REGULAR_SEASON`, and `3=POSTSEASON`; unsupported or absent values remain `UNKNOWN_GAME_TYPE` and fail closed from scoring/evaluation qualification. Game type is never inferred from date.\n\nPreseason games may be scored and may retain valid H2H observations solely as `PRESEASON_NON_EVALUATION` and `PRESEASON_PLUMBING_MARKET_OBSERVATION`. The reusable regular-season eligibility predicate hard-filters `game_type_code == 2`; explicit exclusions cover preseason, postseason, and unknown types. Grading preserves the pregame evaluation status, so a known preseason result remains non-evaluation.\n\nRegular-season feature targets use completed type-2 history only. A deterministic first-regular-game fixture with an earlier 5-1, 40-20 preseason result retained zero prior games and `SEASON_OPEN_NO_HISTORY`; preseason goals, shots, form, prior-10, and rest therefore cannot contaminate the frozen regular-season state. This matches the frozen historical population, which contained no preseason rows, without changing coefficients or probabilities.\n\nThe exact 2,798-row champion parity replay passed with maximum probability delta `{parity.maximum_probability_delta.iloc[0]:.3g}` and zero side mismatches. SOG sources, paths, candidate logic, prop normalization, and archives were untouched. No live run was performed.\n\nThe system is `READY_WITH_BOUNDED_LIMITS` for exactly one later human-initiated real preseason shadow validation when official games and H2H markets exist.\n\n## Decisions\n\n"""+'\n'.join(f'- `{k}` = `{v}`' for k,v in decisions.items())+'\n'; (out/f'nhl_season_2026_game_type_preseason_isolation_report_{DATE}.md').write_text(report); (out/f'nhl_season_2026_game_type_preseason_isolation_one_page_summary_{DATE}.md').write_text(report)
 assert before=={str(x):sha256_file(x) for p in pp.values() for x in p.iterdir() if x.is_file()}; text='\n'.join(x.read_text(errors='ignore') for x in out.iterdir() if x.suffix in {'.md','.csv','.json'}); assert not re.search(r'\b20\d{2}[-–/]20\d{2}\b',text)
 identity={'package_name':'nhl_season_2026_game_type_preseason_isolation','version':'1.0.0','as_of_date':DATE,'generated_by':str(Path(__file__).relative_to(root)),'canonical_season':2026,'champion_identity':CHAMPION,'champion_prediction_sha256':PRED_SHA,'parent_manifest_sha256':{k:v for k,(_,v) in PARENTS.items()},'historical_parity_rows':2798,'historical_parity_maximum_delta':float(parity.maximum_probability_delta.iloc[0]),'refit_performed':False,'live_run_performed':False,'shared_schedule_modified':False,'source_mutation_check':'PASS'}; js(identity,out/f'package_identity_{DATE}.json')
 files=sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'); assert len(files)==12; (out/'SHA256SUMS').write_text(''.join(f'{sha256_file(x)}  {x.name}\n' for x in files)); subprocess.run(['shasum','-a','256','-c','SHA256SUMS'],cwd=out,check=True,capture_output=True); print(json.dumps({'output_dir':str(out),'manifest_sha256':sha256_file(out/'SHA256SUMS'),'parity_max_delta':float(parity.maximum_probability_delta.iloc[0])},indent=2))
if __name__=='__main__': main()
