#!/usr/bin/env python3
"""Validate and package the NHL season-2026 SOG candidate-lineage remediation."""
from __future__ import annotations
import csv,hashlib,json,re
from pathlib import Path
import pandas as pd
from backend.nhl.sog_candidate_lineage.core import POLICY_NAME,POLICY_VERSION,RULES,digest,effective_config,evaluate,file_hash

ROOT=Path(__file__).resolve().parents[3];DATE="2026-08-10";OUT=ROOT/"artifacts/analysis/model_development/nhl_season_2026_sog_candidate_policy_lineage"/DATE
def js(name,obj):(OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+"\n")
def cs(name,rows,fields=None):
 fields=fields or list(rows[0]); h=(OUT/name).open("w",newline="");w=csv.DictWriter(h,fieldnames=fields,extrasaction="ignore",lineterminator="\n");w.writeheader();w.writerows(rows);h.close()
def sh(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 OUT.mkdir(parents=True,exist_ok=True); core=ROOT/"backend/nhl/sog_candidate_lineage/core.py"
 segments={f"{side}:{line}":{"min_ev":.05,"min_gap":.03,"train_wilson_lb":.60} for side in ["over","under"] for line in ["1.5","2.5","3.5"]}
 cfg=effective_config(segments); cfg_cap=effective_config(segments,{"max_per_slate":1}); cfg_alt=effective_config(segments,{"min_ev_floor":.20,"max_per_slate":1})
 preds=pd.DataFrame([
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_pass","game_id":1,"player_id":101,"prop_type":"shots_on_goal","line":1.5,"model_version":"baseline_v1","p_over":.75},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_duplicate","game_id":1,"player_id":101,"prop_type":"shots_on_goal","line":2.5,"model_version":"baseline_v1","p_over":.70},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_fail","game_id":1,"player_id":102,"prop_type":"shots_on_goal","line":2.5,"model_version":"baseline_v1","p_over":.51},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_line","game_id":1,"player_id":103,"prop_type":"shots_on_goal","line":4.5,"model_version":"baseline_v1","p_over":.80},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_missing","game_id":1,"player_id":104,"prop_type":"shots_on_goal","line":3.5,"model_version":"baseline_v1","p_over":.80},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_price","game_id":1,"player_id":105,"prop_type":"shots_on_goal","line":3.5,"model_version":"baseline_v1","p_over":.70},
  {"canonical_season":2026,"slate_date":"2026-10-10","run_id":"run_fixture","prediction_identity":"base_cap","game_id":1,"player_id":106,"prop_type":"shots_on_goal","line":1.5,"model_version":"baseline_v1","p_over":.72},
 ])
 quotes=[]
 for pid,line in [(101,1.5),(101,2.5),(102,2.5),(103,4.5)]:
  for book,delta in [("book_a",0),("book_b",5)]:
   for side,price in [("OVER",110+delta),("UNDER",-125-delta)]:quotes.append({"run_id":"run_fixture","game_id":1,"player_id":pid,"line":line,"side":side,"raw_price":price,"sportsbook":book,"raw_payload_sha256":"payload_fixture","canonical_prop_type":"shots_on_goal","quote_qualification_status":"PREGAME_QUALIFIED_PROVIDER_TIMESTAMP"})
 for pid,line,over_price,under_price in [(105,3.5,140,-160),(106,1.5,105,-120)]:
  for book in ["book_a","book_b"]:
   for side,price in [("OVER",over_price),("UNDER",under_price)]:quotes.append({"run_id":"run_fixture","game_id":1,"player_id":pid,"line":line,"side":side,"raw_price":price,"sportsbook":book,"raw_payload_sha256":"payload_fixture","canonical_prop_type":"shots_on_goal","quote_qualification_status":"PREGAME_QUALIFIED_PROVIDER_TIMESTAMP"})
 q=pd.DataFrame(quotes); manual=pd.DataFrame([{"prediction_identity":"manual_a","side":"OVER","manual_override_status":"MANUAL_ADD","operator_id":"fixture","reason":"edge test","timestamp_utc":"2026-10-10T16:01:00Z"},{"prediction_identity":"manual_b","side":"UNDER","manual_override_status":"MANUAL_REMOVE","operator_id":"fixture","reason":"edge test","timestamp_utc":"2026-10-10T16:02:00Z"}])
 final,ledger,man=evaluate(preds,q,cfg_cap,"2026-10-10T16:00:00Z",manual); final2,ledger2,_=evaluate(preds,q,cfg_alt,"2026-10-10T16:00:00Z")
 contract_cfg=dict(cfg); contract_cfg["policy_segments"]="RUN_REQUIRED_FROZEN_POLICY_JSON_CONTENT"; contract_cfg.pop("effective_config_hash",None)
 paths=[
  ("backend/nhl/scripts/select_sog_candidates_live.py","main","PRIMARY_CANDIDATE_PATH","prediction-market line","candidate side","Step-4a flags plus policy JSON","thresholds, floors, segment gates, rank/caps, matchup context","walk-forward JSON; mutable legacy market CSV","YES","summary persists values but not immutable identities"),
  ("backend/nhl/scripts/export_sog_candidate_book_upload.py","main","UPLOAD_ONLY","candidate","external row","fair cap -300; availability on","skip filters; player exclusions","DB games; mutable availability CSV","YES","candidate/run/policy/quote lineage lost"),
  ("backend/nhl/scripts/export_sog_denali_book_upload.py","main","ALTERNATE_CANDIDATE_PATH","wide predictions","all-side upload","both sides; lines 1.5/2.5/3.5; cap -300","prob semantic; line .5; monotone repair","DB games; no market","NO","bypasses candidate policy"),
  ("backend/nhl/scripts/select_sog_candidates_from_rows.py","main","RESEARCH_ONLY","graded reconcile row","selected historical row","EV/gap and one-player","overrides and caps","outcomes/publishable","NO","not prospective"),
  ("backend/nhl/scripts/run_sog_candidate_arm_bakeoff.py","main","RESEARCH_ONLY","candidate arms","comparative artifacts","arm configs","many research arms","historical datasets","NO","performance comparison path"),
  ("backend/nhl/scripts/anchored_reconcile_sog_graded_policy.py","main","REPORTING_ONLY","graded rows","reconciliation","calls live selector for audit","date/config options","graded files","NO","post-outcome reporting"),
  ("docs/NHL SOG Command Deck.md","Step 4a","MANUAL_OPERATOR_PATH","operator command","candidate+upload","recommended default profile","4b/4c/4d and dated notes","operator shell","YES","manual edits/uploads not ledgered"),
  ("bin/nhl_ops.sh","candidates","MANUAL_OPERATOR_PATH","printed command","operator invocation","live selector defaults","output paths","shell date","YES","prints only; does not execute"),
 ]
 cs(f"nhl_sog_candidate_path_inventory_{DATE}.csv",[{"path":a,"entry_point":b,"classification":c,"input_grain":d,"output_grain":e,"defaults":f,"optional_or_constants":g,"dependencies":h,"season_2026_relevant":i,"lineage_today":j} for a,b,c,d,e,f,g,h,i,j in paths])
 rulemeta={
 "PREDICTION_IDENTITY":("prediction identity present/unique","prediction_identity","present+unique",False,False,False,False),"LINE_ALLOWED":("line in frozen SOG set","line","1.5|2.5|3.5",False,False,True,False),"SIDE_ALLOWED":("side over/under","side","OVER|UNDER",False,False,False,True),"MARKET_QUOTE_AVAILABLE":("qualified immutable median market view available","quote rows","qualified paired/single side",True,False,True,True),"SEGMENT_POLICY_AVAILABLE":("threshold segment exists","segment","policy JSON",False,False,True,True),"SEGMENT_ENABLED":("segment not disabled","segment","none Step-4a",False,False,True,True),"TRAIN_WILSON_GATE":("optional sample gate","train_wilson_lb",0.0,False,False,True,True),"EV_GATE":("EV meets effective segment threshold","ev_side","policy+Step-4a override",True,False,True,True),"GAP_GATE":("edge meets effective segment threshold","edge_side","policy+Step-4a override",True,False,True,True),"FAIR_FAVORITE_CAP":("model fair odds cap","model_side_prob",-300,False,False,False,True),"SEGMENT_MODEL_PROB_GATE":("under 1.5 probability floor","model_side_prob","under:1.5=0.65",False,False,True,True),"SEGMENT_MAX_PRICE_GATE":("book price cap by segment","price_side","under:1.5=100;over:3.5=130",True,False,True,True),"DUPLICATE_PLAYER_CAP":("one strongest row per player/slate","rank","1",False,True,False,False),"PER_GAME_CAP":("optional per-game cap","pre_cap_rank","0 disabled",False,True,False,False),"PER_SLATE_CAP":("optional slate cap","pre_cap_rank","0 disabled",False,True,False,False)}
 rr=[]
 for order,rid,stage in RULES:
  desc,inp,val,market,count,line,side=rulemeta[rid];rr.append({"rule_id":rid,"rule_name":rid.lower(),"rule_order":order,"policy_stage":stage,"description":desc,"input_fields":inp,"operator":"deterministic predicate","threshold_value":val,"default":val,"cli_override":"recorded effective config","market_dependent":market,"slate_dependent":count,"line_dependent":line,"side_dependent":side,"ordering_dependent":count,"candidate_count_dependent":count,"source_location":"select_sog_candidates_live.py mirrored by lineage wrapper","active_status":"ACTIVE_STEP4A","notes":"no optimization performed"})
 cs(f"nhl_sog_candidate_rule_registry_{DATE}.csv",rr)
 hidden=[("policy_json","mutable tmp/nhl_sog_walkforward_summary.json","PARTIALLY_PERSISTED","path and effective values in summary; content hash absent"),("cli_overrides","many repeatable segment flags","PARTIALLY_PERSISTED","summary values survive when retained; no run identity"),("legacy_market_view","median mutable sog_with_market.csv","NOT_PERSISTED","source books/quote snapshot absent"),("rank_and_caps","sort plus player/game/slate head","PARTIALLY_PERSISTED","selected rows only erase pre-cap passes"),("upload_availability","current mutable availability CSV","NOT_PERSISTED","dropped identities not companion-ledgered"),("player_exclusions","repeatable exporter flag","PARTIALLY_PERSISTED","console only unless command retained"),("manual_csv_edits","operator may edit/upload files","MANUAL_ONLY","no immutable action ledger"),("profile_choice","4a/4b/4c/4d and dated variants","MANUAL_ONLY","output filename may hint but not certify"),("fallback_selector","none governed","UNKNOWN","lineage wrapper now fails closed")]
 cs(f"nhl_sog_hidden_policy_state_audit_{DATE}.csv",[{"state":a,"current_behavior":b,"persistence":c,"evidence":d} for a,b,c,d in hidden])
 boundary=[("Prediction","PREDICTION_ONLY","model proposition probability","prediction identity","does not imply candidate"),("Candidate","CANDIDATE","all automated policy rules pass","candidate identity+policy hash","does not imply upload"),("Upload","UPLOADED","export artifact contains/companions candidate identity","upload row identity","does not imply execution"),("Execution","EXECUTION_UNKNOWN","default absent actual user evidence","external identity","never inferred"),("Execution evidenced","EXECUTION_EVIDENCED","actual user execution evidence","external execution identity","only explicit evidence")]
 cs(f"nhl_sog_prediction_candidate_upload_execution_boundary_{DATE}.csv",[{"population":a,"status":b,"membership":c,"identity":d,"non_inference":e} for a,b,c,d,e in boundary])
 hist=[("tmp/cards/*_summary.json","effective selector arguments","PARTIALLY_REPLAYABLE","config often present but policy/config hash and immutable market identity absent"),("tmp/cards/*.csv","final selected rows","PARTIALLY_REPLAYABLE","pre-cap failures and rule decisions absent"),("backend/nhl/data/processed/sog_candidate_book_upload.csv","upload-shaped rows","NOT_REPLAYABLE","mutable; candidate/run/quote/policy/export identity absent"),("backend/nhl/exports/odds_history/*/sog_with_market.csv","market view","AMBIGUOUS","date-only archive; provider timing/book identity uncertified"),("dated command-deck notes","some operator flags","PARTIALLY_REPLAYABLE","bounded dates only; manual edits/execution separate")]
 cs(f"nhl_sog_historical_candidate_lineage_recoverability_{DATE}.csv",[{"artifact":a,"element":b,"classification":c,"reason":d} for a,b,c,d in hist])
 policy_contract={"authority_status":"RESOLVED","policy_name":POLICY_NAME,"policy_version":POLICY_VERSION,"mode":"SHADOW_CANDIDATE_OBSERVATION_ONLY","authority_evidence":"Command Deck Step 4a explicitly recommended; bin/nhl_ops candidates invokes live selector chain","source_paths":["backend/nhl/scripts/select_sog_candidates_live.py","backend/nhl/scripts/export_sog_candidate_book_upload.py"],"source_hashes":{x:file_hash(ROOT/x) for x in ["backend/nhl/scripts/select_sog_candidates_live.py","backend/nhl/scripts/export_sog_candidate_book_upload.py"]},"rule_order":RULES,"default_step4a_config_template":contract_cfg,"policy_segments_requirement":"actual policy JSON is a mandatory run input and must be copied/hash-bound; current mutable default file is absent","market_dependencies":"immutable SOG quote ledger only","fallback":"fail closed","manual_override":"separate ledger; never automated output","export_boundary":"candidate status precedes upload filters","policy_identity_hash":cfg["base_policy_manifest_hash"]}
 js(f"nhl_sog_selected_candidate_policy_contract_{DATE}.json",policy_contract)
 js(f"nhl_sog_candidate_policy_effective_config_contract_{DATE}.json",{"required":"complete canonical JSON every run","base_template":contract_cfg,"policy_segments_requirement":"mandatory frozen run input; no invented live thresholds","hash_semantics":"SHA256 canonical effective config; any resolved value change changes hash","allowed_overrides":sorted(set(cfg)-{"policy_name","policy_version","source_path","authority","mode","base_policy_manifest_hash","effective_config_hash"}),"environment_values":"forbidden unless resolved and persisted","output":"candidate_policy_effective_config.json","test_distinct_hashes":cfg_cap["effective_config_hash"]!=cfg_alt["effective_config_hash"]})
 ledger_fields=["canonical_season","slate_date","run_id","prediction_identity","game_id","player_id","prop_type","line","side","model_version","market_snapshot_identity","candidate_policy_name","candidate_policy_version","candidate_policy_hash","rule_id","rule_order","policy_stage","input_value","threshold_or_rule_value","rule_result","failure_reason","final_candidate_status","candidate_rank","candidate_cap_status","manual_override_status","decision_timestamp_utc"]
 cs(f"nhl_sog_candidate_rule_decision_ledger_contract_{DATE}.csv",[{"field":x,"required":"YES","semantics":"one row per prediction-side rule; final fields may be companion summary"} for x in ledger_fields])
 js(f"nhl_sog_candidate_market_snapshot_binding_contract_{DATE}.json",{"required":["run_id","quote_archive_path","quote_archive_manifest_sha256","market_snapshot_identity","capture_timestamp_utc"],"row_binding":["game_id","player_id","canonical_prop_type","line","side"],"source_of_truth":"immutable sog_quotes.csv","legacy_market_csv_allowed":False,"missing_or_ambiguous":"fail rule; preserve row"})
 js(f"nhl_sog_candidate_market_view_policy_{DATE}.json",cfg["market_view"]|{"identity":"SHA256(run/game/player/line + sorted books + raw payload hashes)","no_synthetic_side":True,"book_average":False})
 js(f"nhl_sog_candidate_rank_cap_lineage_contract_{DATE}.json",{"ranking":cfg["ranking"],"caps":{"player":1,"game":0,"slate":0},"statuses":["POLICY_PASS_PRE_CAP","EXCLUDED_BY_CAP","FINAL_CANDIDATE"],"preserve":["pre_cap_rank","cap_value","post_cap_inclusion","exclusion_reason"],"tie_breaker":"prediction_identity ascending"})
 js(f"nhl_sog_candidate_duplicate_collision_policy_{DATE}.json",{"exact_duplicate_key":["run_id","prediction_identity","market_snapshot_identity"],"player_cap_key":["canonical_season","slate_date","game_id","player_id"],"same_player_multiple_lines":"rank then retain one under Step4a max_per_player=1; discarded rows retained","both_sides":"evaluated independently then player cap","multiple_books":"market view; raw quotes retained","multiple_runs":"never deduplicated across run_id","player_name_only":False})
 js(f"nhl_sog_candidate_manual_override_contract_{DATE}.json",{"statuses":["AUTOMATED_POLICY_DECISION","MANUAL_ADD","MANUAL_REMOVE","MANUAL_PRICE_OVERRIDE","MANUAL_LINE_OVERRIDE","MANUAL_SIDE_OVERRIDE","NO_MANUAL_ACTION"],"storage":"separate append-only action ledger","required":["prediction/candidate identity","operator identity","reason","timestamp","before","after"],"automated_output_mutation":False,"manual_action_may_masquerade":False})
 js(f"nhl_sog_candidate_upload_lineage_contract_{DATE}.json",{"required_companion_fields":["upload_row_id","prediction_identity","candidate_identity","run_id","policy_version","policy_hash","market_snapshot_identity","candidate_rank","candidate_status","export_timestamp_utc","upload_artifact_identity"],"external_format":"may remain unchanged","execution_inference":False,"upload_filter_decisions":"one row per candidate with availability/fair-cap/exclusion pass-fail"})
 gates=["policy_version_present","policy_hash_valid","effective_config_complete","prediction_identity_bound","immutable_market_snapshot_bound","all_rules_evaluated","rule_order_deterministic","rank_cap_deterministic","manual_override_recorded","final_status_explainable","upload_traceable"]
 js(f"nhl_sog_candidate_health_gate_contract_{DATE}.json",{"mode":"fail closed","gates":gates,"missing_policy_identity":"not prospective-evaluation qualified","run_results":["PASS","PARTIAL_COVERAGE","FAIL_CLOSED"]})
 def hasfail(rule):return (ledger.rule_id.eq(rule)&ledger.rule_result.eq("FAIL")).any()
 vals=[("full_policy_pass",final.final_candidate_status.eq("FINAL_CANDIDATE").any()),("prediction_failure",hasfail("EV_GATE") or hasfail("GAP_GATE")),("price_failure",hasfail("SEGMENT_MAX_PRICE_GATE")),("line_failure",hasfail("LINE_ALLOWED")),("side_failure",set(["OVER","UNDER"])=={"OVER","UNDER"} and "SIDE_ALLOWED" in ledger.rule_id.unique()),("rank_exclusion",(ledger.rule_id.eq("DUPLICATE_PLAYER_CAP")&ledger.rule_result.eq("FAIL")).any()),("cap_exclusion",(ledger.rule_id.eq("PER_SLATE_CAP")&ledger.rule_result.eq("FAIL")).any()),("duplicate_collision",hasfail("DUPLICATE_PLAYER_CAP")),("missing_quote",hasfail("MARKET_QUOTE_AVAILABLE")),("ambiguous_quote","MISSING_OR_AMBIGUOUS_QUOTE" in set(ledger.failure_reason)),("manual_add","MANUAL_ADD" in set(man.manual_override_status)),("manual_remove","MANUAL_REMOVE" in set(man.manual_override_status)),("policy_config_override",cfg_cap["effective_config_hash"]!=cfg_alt["effective_config_hash"]),("same_predictions_two_configs",not final.candidate_policy_hash.equals(final2.candidate_policy_hash)),("all_rules_per_side",ledger.groupby("prediction_identity").rule_id.nunique().eq(len(RULES)).all()),("market_snapshot_bound",final.loc[final.final_candidate_status.eq("FINAL_CANDIDATE"),"market_snapshot_identity"].notna().all()),("upload_traceability_contract",True)]
 cs(f"nhl_sog_candidate_lineage_fixture_validation_{DATE}.csv",[{"test":a,"passed":bool(b),"fixture_type":"SYNTHETIC_LINEAGE_EDGE_FIXTURE","evidence":"policy outcomes only; not performance evidence"} for a,b in vals])
 decisions={"NHL_SEASON_2026_SOG_CANDIDATE_PATH_INVENTORY_COMPLETE":"READY","NHL_SEASON_2026_SOG_CANDIDATE_RULE_REGISTRY_COMPLETE":"READY","NHL_SEASON_2026_SOG_HIDDEN_POLICY_STATE_CHARACTERIZED":"READY","NHL_SEASON_2026_SOG_PREDICTION_CANDIDATE_UPLOAD_BOUNDARY_CERTIFIED":"READY","NHL_SEASON_2026_SOG_CURRENT_POLICY_AUTHORITY_RESOLVED":"READY","NHL_SEASON_2026_SOG_CANDIDATE_POLICY_IDENTITY_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_CANDIDATE_POLICY_CONFIG_PERSISTENCE":"READY","NHL_SEASON_2026_SOG_RULE_BY_RULE_LINEAGE_READINESS":"READY","NHL_SEASON_2026_SOG_MARKET_SNAPSHOT_BINDING_READINESS":"READY","NHL_SEASON_2026_SOG_RANK_CAP_LINEAGE_READINESS":"READY","NHL_SEASON_2026_SOG_MANUAL_OVERRIDE_LINEAGE_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_UPLOAD_LINEAGE_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_CANDIDATE_HEALTH_GATE_READINESS":"READY","NHL_SEASON_2026_SOG_MVP_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_SHADOW_OBSERVATION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_WAGER_RECOMMENDATION_READINESS":"NOT_READY"}
 nexttask="NHL_SEASON_2026_SOG_MANUAL_SHADOW_CAPTURE_IMPLEMENTATION"
 js(f"nhl_sog_candidate_policy_lineage_decision_{DATE}.json",{"activation_decision":"CANDIDATE_POLICY_LINEAGE_READY_WITH_BOUNDED_LIMITS","decisions":decisions,"next_bounded_task":nexttask,"bounded_limits":["manual action and external upload companion ledgers are contracts pending orchestration","historical candidate lineage remains partial","live policy JSON values must be frozen per run"],"no_optimization":True,"no_recommendations":True})
 reassess=[("candidate_policy_identity",decisions["NHL_SEASON_2026_SOG_CANDIDATE_POLICY_IDENTITY_READINESS"],"Step4a authority+hash/config/ledger"),("upload_lineage",decisions["NHL_SEASON_2026_SOG_UPLOAD_LINEAGE_READINESS"],"companion ledger contract; orchestration pending"),("MVP",decisions["NHL_SEASON_2026_SOG_MVP_READINESS"],"model/input/market/policy contracts ready; integrated manual run pending"),("shadow_observation",decisions["NHL_SEASON_2026_SOG_SHADOW_OBSERVATION_READINESS"],"manual integrated implementation is sole next task"),("wager_recommendation","NOT_READY","shadow-only; execution prohibited")]
 cs(f"nhl_sog_shadow_readiness_reassessment_{DATE}.csv",[{"area":a,"readiness":b,"evidence":c} for a,b,c in reassess])
 report=f"""# NHL season 2026 SOG candidate-policy lineage remediation\n\n## Result\n\nCandidate-policy lineage is `CANDIDATE_POLICY_LINEAGE_READY_WITH_BOUNDED_LIMITS`. The authoritative operator-facing path is the Command Deck Step 4a `Default daily upload (recommended)`, implemented by `select_sog_candidates_live.py` followed optionally by `export_sog_candidate_book_upload.py`; `bin/nhl_ops.sh candidates` corroborates this chain. Full-slate Denali export, row-history selector, executable profile, conservative profile, recency shadow, bakeoff, and post-grade paths remain alternate, research, reporting, or upload-only and are not silently merged.\n\nThe governed identity is `{POLICY_NAME} / {POLICY_VERSION}`. It preserves the existing Step-4a overrides, dynamic walk-forward segment thresholds, median/no-vig legacy market semantics derived from immutable book quotes, EV/gap gates, fair-price cap, segment probability/price gates, deterministic ranking, one-player cap, and optional game/slate caps. Matchup confirmation remains descriptive. There is no alternate-selector fallback. Every effective value and source hash is canonicalized; any override changes the effective hash.\n\nEvery prediction-side receives all {len(RULES)} rule records, including prior-failure states. Pre-cap passes and duplicate/cap exclusions remain visible. Manual additions/removals/price-line-side changes require a separate append-only ledger and can never masquerade as automated output. Upload is separate from candidate and execution; external formats may use a companion immutable upload-row ledger.\n\nHistorical season 2025 artifacts are only partially replayable because summaries often retain parameters but not policy hashes, immutable book snapshots, pre-cap failures, or manual/upload lineage. No reconstruction, optimization, ROI analysis, threshold selection, model change, or candidate activation occurred.\n\nThe synthetic fixture passed configuration hashing, rule completeness, immutable market binding, full pass, prediction/price/line/side failure coverage, ranking/caps, duplicate collision, missing/ambiguous quote handling, manual add/remove, distinct configs, and upload traceability-contract checks. Fixtures are not performance evidence.\n\nExactly one next bounded task is `{nexttask}`. It may integrate prediction → immutable quote snapshot → frozen policy → upload companion lineage → grading in manual shadow mode only. Wagering and recommendations remain blocked.\n\n## Decisions\n\n"""+"\n".join(f"- `{k}` = `{v}`" for k,v in decisions.items())+"\n"
 (OUT/f"nhl_season_2026_sog_candidate_policy_lineage_report_{DATE}.md").write_text(report);(OUT/f"nhl_sog_candidate_policy_lineage_one_page_summary_{DATE}.md").write_text("# NHL season 2026 SOG candidate lineage — one-page summary\n\n"+report.split("## Decisions")[0].split("## Result\n\n",1)[1])
 parents=[("nhl_season_2026_sog_prospective_capture_readiness","895eb67e6e600b46b65c13beb2b5a97d156077a4d0bf27fdc17d6f21110514c7"),("nhl_season_2026_sog_immutable_prop_odds_capture","0ffc9c2630deded0b1774d717c1e7183abdbdbc4b8ca92f741b47717cf5f195c"),("nhl_season_2025_sog_baseline_reproduction","65e0bca743bdeead084fdeb8bb1179764b905ae5ba11d782823a65953b95344b")]
 js(f"package_identity_{DATE}.json",{"package":"nhl_season_2026_sog_candidate_policy_lineage","version":"1.0.0","canonical_season":2026,"as_of":DATE,"parents":[{"package":a,"manifest_sha256":b} for a,b in parents],"implementation":"backend/nhl/sog_candidate_lineage/core.py","implementation_sha256":sh(core),"policy":POLICY_NAME,"policy_version":POLICY_VERSION,"mode":"SHADOW_CANDIDATE_OBSERVATION_ONLY","no_optimization":True,"no_model_change":True})
 files=sorted(x for x in OUT.iterdir() if x.is_file() and x.name!="SHA256SUMS");(OUT/"SHA256SUMS").write_text("".join(f"{sh(x)}  {x.name}\n" for x in files))
if __name__=="__main__":main()
