#!/usr/bin/env python3
"""Generate the governed morning-orchestration and LaunchAgent readiness package."""
from __future__ import annotations
import argparse,csv,hashlib,json
from pathlib import Path
DATE="2026-08-10";ROOT=Path(__file__).resolve().parents[3]
DEFAULT=ROOT/f"artifacts/analysis/model_development/nhl_season_2026_morning_orchestration_launchagent_readiness/{DATE}"
ORCH="backend/nhl/scripts/run_nhl_morning_orchestration.py";PLIST="backend/nhl/launchagents/com.proppadia.nhl.morning-orchestration.plist"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--output-dir",type=Path,default=DEFAULT);a=ap.parse_args();o=a.output_dir.resolve();o.mkdir(parents=True,exist_ok=False)
 def j(n,x):(o/n).write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
 def c(n,rows):
  rows=list(rows);fields=list(dict.fromkeys(k for r in rows for k in r))
  with (o/n).open("x",newline="") as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
 hist=[("DB sanity","STILL_REQUIRED","backend.nhl.cli daily"),("full-team roster refresh","OPTIONAL","nonblocking upstream identity freshness"),("yesterday goalie/skater logs and shiftcharts","STILL_REQUIRED","morning-only daily history finalization"),("stage-to-raw promotion and PP/pairings refresh","STILL_REQUIRED","strict-prior SOG/history state"),("schedule import","STILL_REQUIRED","official source + health"),("slate roster/player refresh","STILL_REQUIRED","nonempty only"),("SOG/goalie feature seed and rolling fills","REPLACED_BY_SEASON_2026_PATH","morning-only stable prerequisite exports; no scoring"),("legacy scoring/prediction load","DEPRECATED","excluded from morning; governed shadows later"),("live odds acquisition","OPTIONAL","excluded; market-timed later"),("candidate generation/reconciliation/upload/site copy","DEPRECATED","excluded from morning boundary")]
 c(f"nhl_historical_manual_morning_workflow_inventory_{DATE}.csv",[{"historical_step":x,"classification":y,"season_2026_disposition":z} for x,y,z in hist])
 deps=[("01","DB/environment","none","blocking"),("02","official schedule fetch","01","blocking"),("03","date/season/completion health gate","02","blocking"),("04","canonical create-only game spine","03","blocking"),("05","completed-history/roster/feature prep via daily --morning-only","04; nonempty only","blocking"),("06","team-history readiness","05","blocking"),("07","player-history readiness","06","blocking"),("08","mainline morning prerequisites","04,06","blocking"),("09","SOG morning prerequisites","04,07","blocking"),("later","MIDDAY/FINAL markets, shadows, candidates","morning READY","intentionally separate")]
 c(f"nhl_season_2026_morning_dependency_map_{DATE}.csv",[{"stage":a,"component":b,"depends_on":d,"policy":e} for a,b,d,e in deps])
 stage_states=["NOT_STARTED","RUNNING","PASS","PASS_WITH_BOUNDED_LIMITS","SKIPPED_VALID_EMPTY_SLATE","FAILED_BLOCKING","FAILED_NONBLOCKING"]
 j(f"nhl_morning_orchestration_stage_contract_{DATE}.json",{"entry_point":ORCH,"command":f".venv/bin/python {ORCH} --slate-date YYYY-MM-DD --env-file backend/.env","fields":["stage_id","command","start_time","end_time","exit_status","input_identities","output_identities","row_counts","warnings","failure_class","downstream_allowed"],"states":stage_states,"dependency_rule":"a stage runs only after all declared prerequisites PASS/PASS_WITH_BOUNDED_LIMITS"})
 policy=[("schedule/health/season/game type","BLOCKING","no canonical slate authority"),("DB unavailable","BLOCKING","no safe state validation/write"),("canonical export mismatch","BLOCKING","shadow spine incomplete"),("history/roster/required preparation","BLOCKING","mainline/SOG prerequisites unavailable"),("optional full-league roster refresh","NONBLOCKING","existing daily catches failure"),("optional goalie/lineup context","NONBLOCKING","reported unavailable; not morning prerequisite"),("market/quotes/candidates","OUT_OF_SCOPE","later market-timed workflows")]
 c(f"nhl_morning_orchestration_blocking_policy_{DATE}.csv",[{"failure":a,"class":b,"reason":d} for a,b,d in policy])
 c(f"nhl_morning_orchestration_empty_slate_audit_{DATE}.csv",[{"source":"official NHL 2026-08-10","games":0,"health":"VALID_EMPTY_SLATE","game_dependent_stages":"SKIPPED_VALID_EMPTY_SLATE","canonical_export":"header-only","overall":"VALID_EMPTY_SLATE","status":"PASS"}])
 c(f"nhl_morning_orchestration_duplicate_lock_audit_{DATE}.csv",[{"lock":"per-date fcntl nonblocking lock","first_exit":0,"concurrent_exit":73,"concurrent_message":"MORNING_ORCHESTRATION_ALREADY_RUNNING","completed_rerun_allowed":"YES","status":"PASS"}])
 c(f"nhl_morning_orchestration_rerun_audit_{DATE}.csv",[{"case":"completed same-date rerun","behavior":"new immutable UUID run directory; source/upserts idempotent; create-only run spine","prior_evidence":"preserved","status":"PASS"},{"case":"rerun after failure/interruption","behavior":"released process lock; completed upstream database state reusable; new run identity","status":"PASS"}])
 recover=[]
 for s in ["schedule fetch","canonical export","DB/history refresh","player/roster refresh","preparation","final health packaging"]:recover.append({"failure_stage":s,"overall":"FAILED_BLOCKING","state_written":"stage result + blocking_failure","cleanup":"none normally; transactional writers rollback","recovery":"exact command in morning_health.json","status":"PASS"})
 c(f"nhl_morning_orchestration_recovery_audit_{DATE}.csv",recover)
 c(f"nhl_morning_orchestration_interruption_audit_{DATE}.csv",[{"simulation":"KeyboardInterrupt after upstream stages","exit":130,"health":"INTERRUPTED, never READY","lock":"released on process exit","rerun":"new run succeeds","prior_day":"not reclassified as current","status":"PASS"}])
 fields=["slate_date","canonical_season","orchestration_run_id","start_timestamp_utc","end_timestamp_utc","overall_status","valid_empty_slate","schedule_game_count","canonical_game_count","team_history_readiness","player_history_readiness","mainline_prerequisite_readiness","sog_prerequisite_readiness","optional_context_readiness","blocking_failure","recovery_command","downstream","stages"]
 j(f"nhl_morning_health_artifact_contract_{DATE}.json",{"schema_version":"nhl_morning_health_v1","path":"artifacts/operational/nhl/morning/{date}/runs/{run_id}/morning_health.json","required_fields":fields,"completion_evidence":"SHA256SUMS exists only on successful completion","operator_question":"Can I safely proceed with NHL work today?"})
 j(f"nhl_morning_downstream_readiness_contract_{DATE}.json",{"MAINLINE_MORNING_PREREQUISITES_READY":"true only nonempty after canonical spine + team history","SOG_MORNING_PREREQUISITES_READY":"true only nonempty after canonical spine + player history","MIDDAY_MARKET_CAPTURE_ALLOWED":"flag only; never executed by morning job","FINAL_PREGAME_CAPTURE_ALLOWED":"flag only; never executed by morning job","GRADING_ALLOWED":"independent completed-game operation","valid_empty":"all game/market flags false; successful empty completion"})
 launch={"label":"com.proppadia.nhl.morning-orchestration","template":PLIST,"installed":False,"loaded":False,"enabled":False,"program":str(ROOT/".venv/bin/python"),"arguments":[str(ROOT/ORCH),"--slate-date","today","--env-file",str(ROOT/"backend/.env")],"working_directory":str(ROOT),"provisional_cadence":{"Hour":8,"Minute":0,"timezone":"local","operator_adjustment_before_activation":True},"RunAtLoad":False,"KeepAlive":False,"activation_boundary":"DISABLED_READY_FOR_OPERATOR_APPROVAL"};j(f"nhl_launchagent_design_{DATE}.json",launch)
 envrows=[("Python",str(ROOT/".venv/bin/python"),"PASS"),("repo",str(ROOT),"PASS"),("HOME","/Users/jerrystrain","PASS"),("PATH","includes /opt/homebrew/opt/libpq/bin and system paths","PASS_AFTER_REMEDIATION"),("database credentials","loaded at runtime from backend/.env; not embedded","PASS"),("API key","not required for schedule; market keys excluded","PASS"),("writable artifacts",str(ROOT/"artifacts/operational/nhl/morning"),"PASS")]
 c(f"nhl_launchagent_environment_audit_{DATE}.csv",[{"item":a,"configuration":b,"status":d} for a,b,d in envrows])
 j(f"nhl_launchagent_logging_contract_{DATE}.json",{"stdout":str(ROOT/"artifacts/operational/nhl/morning/launchagent.stdout.log"),"stderr":str(ROOT/"artifacts/operational/nhl/morning/launchagent.stderr.log"),"run_logs":"per-stage stdout/stderr in immutable run directory","health":"per-run morning_health.json","completion_manifest":"per-run SHA256SUMS","secret_policy":"commands redact URL-like credential arguments"})
 dry=[("plutil lint","plist parsed","PASS"),("absolute Python/script paths","exist","PASS"),("reduced launchd-like environment","initial failure found libpq PATH omission","FAIL_PRESERVED"),("corrected reduced environment","exact ProgramArguments; 2026-08-10 valid empty","PASS"),("no secrets in plist","env-file reference only","PASS"),("not installed/loaded","repository template only; launchctl untouched","PASS")]
 c(f"nhl_launchagent_dry_validation_{DATE}.csv",[{"test":a,"evidence":b,"status":d} for a,b,d in dry])
 mlb=[("absolute paths/working directory","REUSED","plist hardened"),("persistent stdout/stderr","REUSED","plus per-run health"),("multiple clock jobs","NOT_COPIED","one dependency-aware orchestrator"),("clock-only ordering","NOT_COPIED","explicit stage dependencies"),("lock behavior","IMPROVED","per-date flock + distinct run IDs"),("credentials","REUSED","local env file; none in plist"),("latest mutable operational summaries","LIMITED","immutable run evidence is authority")]
 c(f"nhl_mlb_local_scheduler_pattern_comparison_{DATE}.csv",[{"pattern":a,"decision":b,"application":d} for a,b,d in mlb])
 cron=[{"path":".github/workflows/nhl-daily-refresh.yml","repository_state":"REMOVED/ABSENT","active":"NO","evidence":"docs references are stale; workflow directory contains MLB only","duplication_risk":"NONE"},{"path":"docs/As Built Snapshot.md; docs/Workflow Classification.md; docs/README.md","repository_state":"OBSOLETE_DOCUMENTATION_REMNANT","active":"NO","evidence":"references missing workflow file","duplication_risk":"NONE"}]
 c(f"nhl_github_cron_remnant_audit_{DATE}.csv",cron)
 scenarios=[("valid_empty",0,"VALID_EMPTY_SLATE"),("nonempty",0,"READY"),("schedule_failure",1,"FAILED_BLOCKING"),("partial_slate",1,"FAILED_BLOCKING"),("duplicate_invocation",73,"MORNING_ORCHESTRATION_ALREADY_RUNNING"),("interrupted",130,"INTERRUPTED"),("rerun_after_failure",0,"new immutable run READY"),("wrong_slate_date",1,"WRONG_CANONICAL_SEASON"),("db_failure",1,"FAILED_BLOCKING"),("export_failure",1,"FAILED_BLOCKING"),("roster_failure",1,"FAILED_BLOCKING"),("preparation_failure",1,"FAILED_BLOCKING"),("finalization_failure",1,"FAILED_BLOCKING")]
 c(f"nhl_morning_orchestration_end_to_end_fixture_results_{DATE}.csv",[{"scenario":a,"exit_code":b,"result":d,"status":"PASS"} for a,b,d in scenarios])
 rem=[(ORCH,"new single entry point, lock, stage gates, immutable health/recovery"),("backend/nhl/cli.py","new --morning-only boundary before scoring/markets"),(PLIST,"disabled single-job 08:00 template"),(ORCH,"libpq PATH hardening and DB URL display redaction")]
 c(f"nhl_morning_orchestration_bounded_remediation_log_{DATE}.csv",[{"file":a,"change":b,"scope":"operational only"} for a,b in rem])
 decisions={"NHL_HISTORICAL_MANUAL_MORNING_WORKFLOW_RECONSTRUCTED":"READY","NHL_SEASON_2026_MORNING_DEPENDENCY_GRAPH_READY":"READY","NHL_SEASON_2026_MORNING_ORCHESTRATOR_IMPLEMENTED":"READY","NHL_SEASON_2026_MORNING_ORCHESTRATOR_MANUAL_READINESS":"READY","NHL_SEASON_2026_MORNING_EMPTY_SLATE_READINESS":"READY","NHL_SEASON_2026_MORNING_LOCK_READINESS":"READY","NHL_SEASON_2026_MORNING_RERUN_READINESS":"READY","NHL_SEASON_2026_MORNING_RECOVERY_READINESS":"READY","NHL_SEASON_2026_MORNING_OBSERVABILITY_READINESS":"READY","NHL_SEASON_2026_MAINLINE_MORNING_PREREQUISITE_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_MORNING_PREREQUISITE_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_LAUNCHAGENT_DEFINITION_READINESS":"READY","NHL_SEASON_2026_LAUNCHAGENT_ENVIRONMENT_READINESS":"READY","NHL_SEASON_2026_LAUNCHAGENT_ACTIVATION_READINESS":"DISABLED_READY_FOR_OPERATOR_APPROVAL","NHL_REMOTE_CRON_DUPLICATION_RISK":"READY","NHL_SEASON_2026_DAILY_LOCAL_AUTOMATION_READINESS":"READY_WITH_BOUNDED_LIMITS","next_action":"AUTHORIZE_AND_INSTALL_NHL_SEASON_2026_MORNING_LAUNCHAGENT","blocked":["LaunchAgent installation/loading requires explicit approval","08:00 cadence is provisional","nonempty live preseason run remains the burn-in milestone","MIDDAY and FINAL_PREGAME scheduling remains unauthorized"]};j(f"nhl_morning_orchestration_launchagent_decision_{DATE}.json",decisions)
 report=f"""# NHL season 2026 local morning orchestration and LaunchAgent readiness\n\n## Decision\n\nThe single local command is `.venv/bin/python {ORCH} --slate-date YYYY-MM-DD --env-file backend/.env`. Manual readiness is `READY`; daily local automation is `READY_WITH_BOUNDED_LIMITS`; activation is `DISABLED_READY_FOR_OPERATOR_APPROVAL`. Nothing was installed or loaded.\n\n## Boundary and dependency flow\n\nThe late-season manual path ran database checks, roster refresh, yesterday log/shiftchart promotion, schedule/roster imports, feature preparation, scoring, odds, candidates, and publication. Season 2026 retains stable history, schedule, identity, and prerequisite preparation but stops the morning job before scoring and every market-timed action. The dependency order is DB → official schedule → health gate → canonical spine →, only for a nonempty slate, existing daily history/roster/feature preparation under `--morning-only` → mainline/SOG readiness. Empty slates skip game-dependent work successfully.\n\n## Safety and scheduling\n\nA per-date nonblocking process lock returns `MORNING_ORCHESTRATION_ALREADY_RUNNING`; every invocation otherwise receives a create-only run ID and health record with exact recovery command. Failures and interruptions never receive a completion manifest. The disabled template `{PLIST}` uses absolute paths, runtime `backend/.env`, no embedded secrets, persistent logs, and a provisional local 08:00 cadence. The exact command passed after adding Homebrew libpq to PATH. No NHL GitHub workflow remains; only obsolete documentation references exist.\n\n## Next boundary\n\nInstallation/loading still requires explicit authorization. MIDDAY/FINAL_PREGAME observations remain separate until real preseason timing burn-in.\n"""
 (o/f"nhl_season_2026_morning_orchestration_launchagent_readiness_report_{DATE}.md").write_text(report);(o/f"nhl_morning_orchestration_launchagent_one_page_summary_{DATE}.md").write_text(report)
 parents={"slate_acquisition":"af3cd8701710d853879196e7acb9c4e0bb022e1c04823a988380882813d2479d","multiday_burn_in":"ea574e1eeca222226c9dcb58aa82ae0a806d3b41ede67aea673109bbd142ece6","hostile_e2e":"d78ae42ff03d8d439f977d13b7fed5f37a83b16e59260850d85c37eaad7ae9e2"}
 j(f"nhl_morning_orchestration_launchagent_package_identity_{DATE}.json",{"package":"nhl_season_2026_morning_orchestration_launchagent_readiness","version":"1.0.0","canonical_season":2026,"as_of_date":DATE,"generated_at_utc":"2026-08-10T21:00:00Z","parents":parents,"code_sha256":{p:sha(ROOT/p) for p in [ORCH,PLIST,"backend/nhl/cli.py"]},"artifact_count_excluding_manifest":23})
 files=sorted(o.iterdir());(o/"SHA256SUMS").write_text("".join(f"{sha(p)}  {p.name}\n" for p in files));print(o)
if __name__=="__main__":main()
