#!/usr/bin/env python3
"""Validate NHL live-failure sentinel fixtures and build the governed package."""
from __future__ import annotations
import argparse,csv,copy,hashlib,json,subprocess,tempfile
from pathlib import Path
D="2026-08-10";ROOT=Path(__file__).resolve().parents[3];TARGET=ROOT/f"artifacts/analysis/model_development/nhl_season_2026_mlb_lesson_live_failure_sentinels/{D}";RUN=ROOT/"backend/nhl/scripts/run_nhl_live_failure_sentinel.py"
PARENTS={"morning_activation":"8aefe780a23faaa8e2aac9faf6f071afb6a1b2946223ffa743b83da1ad3d25fb","slate_acquisition":"af3cd8701710d853879196e7acb9c4e0bb022e1c04823a988380882813d2479d","multiday_burn_in":"ea574e1eeca222226c9dcb58aa82ae0a806d3b41ede67aea673109bbd142ece6","independent_crosscheck":"880ac57d2d26a96e3e3d689aa07aa6c5569104267468d794a03a862e3e6068bd"}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--output-dir",type=Path,default=TARGET);a=ap.parse_args();o=a.output_dir;o.mkdir(parents=True,exist_ok=False)
 def j(n,x):(o/n).write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
 def c(n,rows):
  rows=list(rows);fs=list(dict.fromkeys(k for r in rows for k in r))
  with (o/n).open("x",newline="") as f:w=csv.DictWriter(f,fieldnames=fs,lineterminator="\n");w.writeheader();w.writerows(rows)
 # Parent manifests are verified byte-for-byte before fixtures.
 basep=ROOT/"artifacts/analysis/model_development";rels={"morning_activation":"nhl_season_2026_morning_launchagent_activation/2026-08-10","slate_acquisition":"nhl_season_2026_slate_acquisition_pipeline_validation/2026-08-10","multiday_burn_in":"nhl_season_2026_multiday_operational_burn_in/2026-08-10","independent_crosscheck":"nhl_season_2026_independent_calculation_crosscheck/2026-08-10"}
 for k,rel in rels.items():assert sha(basep/rel/"SHA256SUMS")==PARENTS[k]
 fresh={"sentinel_timestamp_utc":"2026-10-10T12:00:00Z","slate_health":{"fetch_timestamp_utc":"2026-10-10T11:00:00Z","completion_status":"READY","downstream_ready":True},"freshness":{k:{"latest_date":"2026-10-09","expected_date":"2026-10-09"} for k in ["team_history","feature_source","player_game_logs","sog_history","toi_history","roster_identity"]},"parents":[{"child":"features","state":"PARENT_PRESENT_AND_CURRENT"}],"market":{"eligible":10,"covered":10,"qualified":10,"identities":["a","b"]},"probabilities":[{"lane":"MAINLINE","identity":"g1","p_home":.6,"p_away":.4,"selected_side":"HOME","home_team":"H","away_team":"A","bound_home_team":"H","bound_away_team":"A"},{"lane":"SOG","identity":"p1","p_over":.55,"p_under":.45,"selected_side":"OVER","line":2.5,"calculation_line":2.5}],"identity":{"qualified_issues":[],"diagnostic_issues":[]},"populations":{"slate_games":2,"scoreable":2,"eligible":10,"predictions":10,"market_qualified":10,"policy_pass_pre_cap":4,"final_candidates":3,"upload_rows":0,"execution_evidenced":0,"graded":0},"outcomes":[],"schedule_changes":[],"runtime":{"duration_minutes":20,"slow_threshold_minutes":90,"overlap_minutes":0,"db_errors":[]},"manual_actions":[],"mutable_inputs":[],"historical_expectation":{"live_sample":30,"minimum_sample":20,"material_shift":False}}
 scenarios={"fresh":({},"GREEN","schedule_freshness:FRESH"),"stale_source":({"slate_health":{"fetch_timestamp_utc":"2026-10-09T11:00:00Z","completion_status":"READY","downstream_ready":True}},"RED","schedule_freshness:STALE_BLOCKING"),"missing_parent":({"parents":[{"child":"features","state":"PARENT_MISSING"}]},"RED","parent:features:PARENT_MISSING"),"low_coverage":({"market":{"eligible":10,"covered":2,"qualified":2,"identities":["a"]}},"YELLOW","market_coverage:MARKET_COVERAGE_LOW"),"no_market":({"market":{"eligible":10,"covered":0,"qualified":0,"identities":[]}},"YELLOW","market_coverage:NO_USABLE_MARKETS"),"orientation_mismatch":({"probabilities":[{"lane":"MAINLINE","identity":"g1","p_home":.6,"p_away":.4,"selected_side":"AWAY","home_team":"H","away_team":"A","bound_home_team":"H","bound_away_team":"A"}]},"RED","orientation:ORIENTATION_MISMATCH"),"ambiguous_player":({"identity":{"qualified_issues":["player:44 ambiguous"],"diagnostic_issues":[]}},"RED","identity_loss:IDENTITY_CRITICAL"),"population_collapse":({"populations":{"eligible":100,"predictions":100,"market_qualified":2,"unexpected_collapse":True}},"YELLOW","population_denominators:POPULATION_COLLAPSE"),"nonparticipant":({"outcomes":[{"identity":"p1","state":"NONPARTICIPANT","settlement":"UNGRADED"}]},"GREEN","outcome_nonparticipant:PASS"),"postponed":({"outcomes":[{"identity":"g1","state":"POSTPONED","settlement":"UNGRADED"}],"schedule_changes":[{"identity":"g1","state":"POSTPONED"}]},"YELLOW","schedule_change:CHANGE_OBSERVED"),"manual_override":({"manual_actions":[{"action":"MANUAL_REMOVE","identity":"p1","operator":"fixture"}]},"YELLOW","manual_intervention:YES"),"mutable_latest":({"mutable_inputs":[{"path":"latest.csv","used":True,"used_for_critical_decision":True,"documented_snapshot_binding":False}]},"RED","mutable_path:MUTABLE_INPUT_USED_UNSAFE"),"runtime_overlap":({"runtime":{"duration_minutes":30,"slow_threshold_minutes":90,"overlap_minutes":15,"db_errors":[]}},"YELLOW","runtime_overlap:BOUNDED_OVERLAP_NO_ERROR"),"historical_shift":({"historical_expectation":{"live_sample":30,"minimum_sample":20,"material_shift":True}},"YELLOW","historical_live_expectation:MATERIAL_DISTRIBUTION_SHIFT"),"post_start":({"market":{"eligible":10,"covered":10,"qualified":10,"identities":["a"],"post_start_quotes":1}},"RED","quote_timing:POST_START_CONTAMINATION"),"misgrade":({"outcomes":[{"identity":"p1","state":"NONPARTICIPANT","settlement":"LOSS"}]},"RED","outcome_nonparticipant:MISGRADING_DETECTED")}
 fixture=[]
 with tempfile.TemporaryDirectory() as td:
  t=Path(td)
  prior=copy.deepcopy(fresh);prior["market"]["identities"]=[];(t/"prior.json").write_text(json.dumps(prior))
  scenarios["late_market"]=({},"YELLOW","late_market:MARKET_CHANGE_OBSERVED")
  for name,(patch,expected,trigger) in scenarios.items():
   x=copy.deepcopy(fresh)
   for k,v in patch.items():x[k]=v
   ip=t/f"{name}.json";ip.write_text(json.dumps(x));cmd=[str(ROOT/".venv/bin/python"),str(RUN),"--phase","FINAL_PREGAME","--slate-date","2026-10-10","--run-id",name,"--input-json",str(ip),"--output-root",str(t/"out")]
   if name=="late_market":cmd.extend(["--prior-run-json",str(t/"prior.json")])
   p=subprocess.run(cmd,text=True,capture_output=True);result=json.loads((t/"out/2026-10-10"/name/"nhl_live_failure_sentinel.json").read_text());states={z["sentinel"]+":"+z["state"] for z in result["sentinels"]};fixture.append({"scenario":name,"expected_overall":expected,"observed_overall":result["overall_status"],"expected_trigger":trigger,"trigger_observed":trigger in states,"exit_code":p.returncode,"status":"PASS" if result["overall_status"]==expected and trigger in states else "FAIL"})
 c(f"nhl_live_failure_sentinel_fixture_validation_{D}.csv",fixture);assert all(x["status"]=="PASS" for x in fixture)
 lessons=[("late/incomplete markets","MLB offerings arrived after early run","mainline H2H coverage","SOG player/line/side coverage","market + late-market","YELLOW unless post-start"),("stale success","exit 0 masked old inputs","schedule/history freshness","logs/TOI/roster freshness","freshness","RED blocking"),("missing parent continuity","derived files survived missing source","team-history parent","logs/quotes/policy/outcomes parents","parent continuity","RED"),("orientation mismatch","labels and probability semantics diverged","HOME/AWAY","OVER/UNDER/line","orientation","RED"),("surface masquerade","research/report looked actionable","shadow label","candidate/upload label","surface audit","RED if undocumented"),("historical mistaken for live","backtest confidence exceeded prospective evidence","distribution only","distribution/fallback/coverage","historical/live","YELLOW"),("identity failure","event/player joins lost","game/team binding","player/team binding","identity","RED qualified"),("denominator drift","quiet population collapse","slate→scoreable→market→grade","eligible→prediction→market→policy→grade","population","YELLOW"),("misgrading","missing/nonparticipant treated as loss","missing/postponed","nonparticipant/push/conflict","outcome","RED"),("schedule change","old schedule state persisted","start/status/teams/type","same shared spine","schedule change","RED identity; YELLOW lifecycle"),("overlapping jobs","long local jobs contended","morning history/features","same","runtime","YELLOW/RED on errors"),("silent manual action","edits lacked lineage","rerun/correction","candidate/upload/regrade","manual ledger","YELLOW visible"),("mutable latest/today","moving files entered governed path","run binding","run binding","mutable path","RED unsafe"),("healthy unusable coverage","machinery passed with no observations","H2H games","quotes/player-lines","coverage usefulness","YELLOW")]
 c(f"nhl_mlb_failure_lesson_mapping_{D}.csv",[{"failure_class":a,"mlb_analogue":b,"mainline_exposure":d,"sog_exposure":e,"detection":f,"blocking_policy":g,"existing_protection":"immutable run/health contracts","remaining_gap":"requires real preseason observations","classification":"ALREADY_HARD_BLOCKED" if g=="RED" else "DETECTED_BUT_NONBLOCKING"} for a,b,d,e,f,g in lessons])
 contracts={
 "source_freshness":{"statuses":["FRESH","STALE_BUT_BOUNDED","STALE_BLOCKING","UNKNOWN"],"sources":["schedule","slate_health","team_history","feature_source","player_game_logs","sog_history","toi_history","roster_identity","quote capture/provider"]},
 "parent_continuity":{"states":["PARENT_PRESENT_AND_CURRENT","PARENT_PRESENT_BUT_STALE","PARENT_MISSING","PARENT_HASH_MISMATCH","PARENT_IDENTITY_AMBIGUOUS"],"bindings":["mainline features→team history","SOG inputs→logs/TOI","candidate→quote snapshot","grading→official outcome"]},
 "market_coverage":{"mainline":["slate games","any H2H","books/game","timestamp-qualified","missing reason"],"sog":["eligible predictions","quoted predictions","books/player-line","qualified","missing lines/sides","ambiguous bindings"]},
 "late_market":{"states":["MARKET_AVAILABLE_EARLY","MARKET_POSTED_LATE","MARKET_DISAPPEARED","LINE_CHANGED","SIDE_CHANGED","NO_MARKET_ALL_DAY"],"comparison":"immutable MIDDAY versus FINAL_PREGAME"},
 "orientation":{"critical":True,"mainline":["probability complement","larger-probability side","bound team labels"],"sog":["probability complement","larger-probability side","calculation line equality"]},
 "population_denominator":{"mainline":["slate","scoreable","market-qualified","graded"],"sog":["eligible","predictions","market-qualified","policy pre-cap","candidates","upload","execution","graded"]},
 "coverage_usefulness":{"states":["PIPELINE_HEALTHY_COVERAGE_NORMAL","PIPELINE_HEALTHY_COVERAGE_LOW","PIPELINE_HEALTHY_NO_USABLE_MARKETS","PIPELINE_FAILED"]},
 "identity_loss":{"shared":["unbound/ambiguous games","team mismatch","provider conflict"],"sog":["unbound/ambiguous player","provider change","trade/team mismatch","name fallback"],"critical_rule":"no issue may enter qualified population"},
 "outcome_nonparticipant":{"states":["missing official outcome","incomplete status","participant","nonparticipant","push","source conflict"],"rules":["nonparticipant != under","postponed != loss","missing != loss"]},
 "schedule_change":{"fields":["start","status","home/away","game type","slate date"],"states":["UNCHANGED","START_CHANGED","POSTPONED","CANCELLED","RESCHEDULED","IDENTITY_CONFLICT"]},
 "runtime_overlap":{"fields":["start","finish","duration","MLB overlap","slowest stage","DB errors"],"states":["NO_OVERLAP","BOUNDED_OVERLAP_NO_ERROR","RESOURCE_CONTENTION_SUSPECTED","RESOURCE_CONTENTION_CONFIRMED"]},
 "manual_intervention":{"append_only_actions":["rerun","candidate add/remove","line/price/side override","upload edit","correction/regrade"],"daily_flag":"MANUAL_INTERVENTION_OCCURRED"},
 "mutable_path":{"states":["RUN_BOUND_ONLY","MUTABLE_INPUT_PRESENT_BUT_NOT_USED","MUTABLE_INPUT_USED_BOUNDED","MUTABLE_INPUT_USED_UNSAFE"]},
 "historical_live_expectation":{"states":["WITHIN_HISTORICAL_RANGE","MATERIAL_DISTRIBUTION_SHIFT","INSUFFICIENT_LIVE_SAMPLE"],"prohibitions":["ROI inference","tiny-sample degradation claim","threshold tuning"]}}
 for k,v in contracts.items():j(f"nhl_{k}_sentinel_contract_{D}.json",v)
 surfaces=[("mainline game_spine/features/predictions","RAW_PREDICTION","run-bound shadow files","PASS"),("mainline market comparison","REPORTING_ONLY","shadow observation","PASS"),("SOG candidate summary","SHADOW_CANDIDATE","candidate status explicit","PASS"),("SOG upload-shaped output","UPLOAD_SHAPED_OUTPUT","does not imply upload/execution","PASS"),("manual ledger","REPORTING_ONLY","operator/action identity","PASS"),("historical fixtures/audits","RESEARCH_ONLY","package-scoped","PASS"),("execution evidence","EXECUTION_EVIDENCED","separate population required","PASS")]
 c(f"nhl_operator_surface_labeling_audit_{D}.csv",[{"surface":a,"class":b,"evidence":d,"status":e} for a,b,d,e in surfaces])
 j(f"nhl_daily_live_failure_sentinel_contract_{D}.json",{"path":"artifacts/operational/nhl/sentinels/{date}/{run_id}","files":["nhl_live_failure_sentinel.json","nhl_live_failure_sentinel.md","SHA256SUMS"],"overall":{"GREEN":"no blocking/bounded sentinel","YELLOW":"bounded issue or low coverage; shadow may continue","RED":"blocking identity/timing/stale-parent/orientation/contamination defect"},"utility":str(RUN.relative_to(ROOT))})
 blockers=[("stale blocking schedule/history","RED",True),("parent missing/hash/identity","RED",True),("orientation mismatch","RED",True),("qualified identity issue","RED",True),("post-start contamination","RED",True),("wrong season/game type/partial slate","RED",True),("unsafe mutable decision input","RED",True),("misgrading nonparticipant/postponed/missing","RED",True),("low/no market coverage","YELLOW",False),("optional context missing","YELLOW",False),("bounded runtime overlap","YELLOW",False),("manual intervention disclosed","YELLOW",False),("insufficient live sample/distribution shift","YELLOW",False)]
 c(f"nhl_live_failure_blocking_policy_{D}.csv",[{"trigger":a,"overall":b,"blocks_downstream":d} for a,b,d in blockers])
 c(f"nhl_morning_sentinel_integration_audit_{D}.csv",[{"integration":"morning orchestrator invokes sentinel after successful stage health","inputs":"slate freshness/completion, canonical parent, population, identity, runtime, manual, mutable","market_sentinels":"NOT_APPLICABLE","red_behavior":"morning finalization blocks","status":"PASS"}])
 j(f"nhl_midday_final_sentinel_integration_contract_{D}.json",{"automation":"NOT_AUTHORIZED","manual_command":f".venv/bin/python {RUN.relative_to(ROOT)} --phase MIDDAY|FINAL_PREGAME --slate-date DATE --run-id ID --input-json immutable_input.json [--prior-run-json midday_sentinel.json]","immutability":"both runs read-only; comparison emits new run-bound sentinel","required_inputs":["immutable schedule","predictions","quotes","bindings","population ledger","manual ledger"]})
 j(f"nhl_grading_sentinel_integration_contract_{D}.json",{"automation":"NOT_AUTHORIZED","phase":"GRADING","required":["official outcomes","participation","game status","push/unresolved conflicts","manual corrections"],"fail_closed":["nonparticipant as loss","postponed as loss","missing as loss"],"semantics_modified":False})
 checklist="# NHL preseason live-failure operator checklist\n\n- [ ] Sources are fresh and parents current.\n- [ ] Slate is complete with correct season/game types.\n- [ ] Game/player identities are clean.\n- [ ] Market coverage and missing reasons are visible.\n- [ ] MIDDAY→FINAL late/disappeared/changed markets are explained.\n- [ ] Probability labels, sides, teams, and lines orient correctly.\n- [ ] Population denominators and attrition are credible.\n- [ ] Manual interventions are explicitly listed.\n- [ ] Runtime overlap/DB errors are reviewed.\n- [ ] No unsafe mutable latest/today input was consumed.\n- [ ] Grading treats nonparticipants, postponements, pushes, and missing outcomes honestly.\n- [ ] GREEN/YELLOW/RED reasons are understood before proceeding.\n";(o/f"nhl_preseason_live_failure_operator_checklist_{D}.md").write_text(checklist)
 decisions={k:"READY" for k in ["NHL_SOURCE_FRESHNESS_SENTINEL_READINESS","NHL_PARENT_CONTINUITY_SENTINEL_READINESS","NHL_MARKET_COVERAGE_SENTINEL_READINESS","NHL_LATE_MARKET_SENTINEL_READINESS","NHL_ORIENTATION_SENTINEL_READINESS","NHL_POPULATION_DENOMINATOR_SENTINEL_READINESS","NHL_COVERAGE_USEFULNESS_SENTINEL_READINESS","NHL_IDENTITY_LOSS_SENTINEL_READINESS","NHL_OUTCOME_NONPARTICIPANT_SENTINEL_READINESS","NHL_SCHEDULE_CHANGE_SENTINEL_READINESS","NHL_RUNTIME_OVERLAP_SENTINEL_READINESS","NHL_MANUAL_INTERVENTION_SENTINEL_READINESS","NHL_MUTABLE_PATH_SENTINEL_READINESS","NHL_HISTORICAL_LIVE_EXPECTATION_SENTINEL_READINESS","NHL_DAILY_LIVE_FAILURE_SENTINEL_READINESS","NHL_PRESEASON_OPERATOR_SENTINEL_READINESS"]};decisions["NHL_MARKET_COVERAGE_SENTINEL_READINESS"]="READY_WITH_BOUNDED_LIMITS";decisions["NHL_LATE_MARKET_SENTINEL_READINESS"]="READY_WITH_BOUNDED_LIMITS";decisions["NHL_HISTORICAL_LIVE_EXPECTATION_SENTINEL_READINESS"]="READY_WITH_BOUNDED_LIMITS";decisions["next_live_milestone"]="FIRST_REAL_NHL_SEASON_2026_PRESEASON_MULTI_RUN_BURN_IN";j(f"nhl_live_failure_sentinel_decision_{D}.json",decisions)
 report="# NHL season 2026 MLB-lesson live-failure sentinels\n\nA single run-bound evaluator now converts authoritative evidence into named freshness, parent, market, orientation, population, identity, outcome, schedule, runtime, manual, mutable-path, and historical/live sentinel states. RED returns a blocking exit; YELLOW preserves bounded shadow operation; GREEN means no triggered blocker or bounded warning. Morning invokes the relevant subset after successful preparation. MIDDAY, FINAL_PREGAME, and grading remain manual contracts consuming immutable run directories. Seventeen fixtures triggered fresh, stale, missing-parent, market, late-market, orientation, identity, denominator, grading, schedule, runtime, manual, mutable, timing, and historical states without model/policy changes. Real market coverage and descriptive ranges remain bounded until preseason.\n";(o/f"nhl_season_2026_mlb_lesson_live_failure_sentinels_report_{D}.md").write_text(report);(o/f"nhl_live_failure_sentinel_one_page_summary_{D}.md").write_text(report)
 j(f"nhl_live_failure_sentinel_package_identity_{D}.json",{"package":"nhl_season_2026_mlb_lesson_live_failure_sentinels","version":"1.0.0","canonical_season":2026,"date":D,"generated_at_utc":"2026-08-10T22:00:00Z","parents":PARENTS,"utility_sha256":sha(RUN),"artifact_count_excluding_manifest":27})
 fs=sorted(o.iterdir());(o/"SHA256SUMS").write_text("".join(f"{sha(p)}  {p.name}\n" for p in fs));print(o)
if __name__=="__main__":main()
