#!/usr/bin/env python3
"""Build the bounded NHL slate acquisition/operations validation package."""
from __future__ import annotations
import csv, hashlib, json, os, subprocess
from datetime import datetime, timezone
from pathlib import Path

DATE="2026-08-10"
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/"artifacts/analysis/model_development/nhl_season_2026_slate_acquisition_pipeline_validation"/DATE
HEALTH=ROOT/"artifacts/operational/nhl/slates"/DATE/"slate_health.json"

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def j(name,obj): (OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+"\n")
def c(name,rows,fields=None):
    rows=list(rows); fields=fields or (list(dict.fromkeys(k for row in rows for k in row)) if rows else ["status"])
    with (OUT/name).open("w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def codehash(rel): return sha(ROOT/rel)

def main():
    OUT.mkdir(parents=True,exist_ok=False)
    health=json.loads(HEALTH.read_text())
    importer="backend/nhl/scripts/import_schedule_today.py"; bridge="backend/nhl/scripts/export_canonical_slate_spine.py"
    cli="backend/nhl/cli.py"
    inventory=[
      {"path":importer,"classification":"CURRENT_OPERATIONAL","role":"official date schedule fetch and transactional nhl.games upsert","invocation":"SLATE_DATE=YYYY-MM-DD .venv/bin/python backend/nhl/scripts/import_schedule_today.py"},
      {"path":cli,"classification":"CURRENT_MANUAL","role":"daily orchestration invokes authoritative importer then health gate","invocation":".venv/bin/python -m backend.nhl.cli daily --with-odds"},
      {"path":"bin/nhl_ops.sh","classification":"CURRENT_MANUAL","role":"command deck prints daily command; does not execute","invocation":"bin/nhl_ops.sh daily"},
      {"path":bridge,"classification":"CURRENT_MANUAL","role":"automated canonical DB to shared shadow game-spine CSV bridge","invocation":".venv/bin/python backend/nhl/scripts/export_canonical_slate_spine.py --slate-date DATE --output FILE"},
      {"path":"backend/nhl/mainline_shadow/cli.py","classification":"SHADOW_ONLY","role":"consumes --schedule-csv","invocation":"python -m backend.nhl.mainline_shadow.cli run"},
      {"path":"backend/nhl/sog_shadow/cli.py","classification":"SHADOW_ONLY","role":"consumes --game-spine-csv","invocation":"python -m backend.nhl.sog_shadow.cli run"},
      {"path":"backend/nhl/scripts/remediate_nhl_season_2024_utah_game_dates.py","classification":"RESEARCH_ONLY","role":"historical schedule reconstruction; not daily acquisition","invocation":"manual"},
    ]
    c(f"nhl_slate_acquisition_path_inventory_{DATE}.csv",inventory)
    c(f"nhl_slate_launchagent_inventory_{DATE}.csv",[{"label":"NONE","plist_path":"NONE","repository_template":"NONE","program":"NONE","arguments":"NONE","cadence":"NONE","run_at_load":"NONE","keep_alive":"NONE","working_directory":"NONE","environment":"NONE","stdout":"NONE","stderr":"NONE","loaded_state":"NOT_INSTALLED_OR_LOADED","purpose":"No NHL LaunchAgent found in repository, ~/Library/LaunchAgents, or launchctl list"}])
    contract={"authority":"NHL official schedule API","fetcher":importer,"function":"fetch_schedule_for_date","command":"SLATE_DATE=<YYYY-MM-DD> .venv/bin/python backend/nhl/scripts/import_schedule_today.py","primary_endpoint":"https://api-web.nhle.com/v1/schedule/{date}","secondary_endpoint":"https://api-web.nhle.com/v1/schedule?date={date}","fallback_endpoint":"https://api.nhle.com/stats/rest/en/schedule?cayenneExp=gameDate=\"{date}\"","date_semantics":"requested ET slate date; returned starts filtered in America/New_York","canonical_store":["nhl.games","nhl.teams","nhl.team_external_ids"],"raw_evidence":"artifacts/operational/nhl/slates/{date}/raw_schedule_response.json","health":"artifacts/operational/nhl/slates/{date}/slate_health.json","transaction":"single database transaction for nonempty slate","unknown_game_type":"fail closed","source_code_sha256":codehash(importer)}
    j(f"nhl_slate_authoritative_fetch_contract_{DATE}.json",contract)
    consumers=[
      {"consumer":"existing daily","input":"nhl.games date-bound rows plus slate_health.json gate","bridge":cli,"classification":"DIRECTLY_CONSUMABLE"},
      {"consumer":"season-2026 mainline shadow","input":"--schedule-csv","bridge":bridge,"classification":"AUTOMATED_BRIDGE_EXISTS"},
      {"consumer":"season-2026 SOG quote capture/shadow","input":"--games-csv / --game-spine-csv","bridge":bridge,"classification":"AUTOMATED_BRIDGE_EXISTS","note":"player inputs remain a separate governed preparation concern"},
    ]; c(f"nhl_slate_downstream_consumer_map_{DATE}.csv",consumers)
    fields=[("canonical season","season","game ID first four digits; date fallback","PASS"),("NHL game ID","game_id","preserved","PASS"),("slate date","game_date","ET requested date","PASS"),("scheduled start UTC","start_time_utc","preserved timestamptz","PASS"),("home team identity","home_team_id/home_team_code","preserved","PASS"),("away team identity","away_team_id/away_team_code","preserved","PASS"),("status","status","mapped scheduled/live/final/postponed/canceled","PASS"),("game type code","game_type","official gameType only","PASS"),("game type label","bridge game_type_label","1 PRESEASON; 2 REGULAR_SEASON; 3 POSTSEASON; else UNKNOWN and acquisition blocks","PASS")]
    c(f"nhl_slate_field_contract_validation_{DATE}.csv",[{"field":a,"canonical_column":b,"behavior":d,"status":e} for a,b,d,e in fields])
    seasons=[{"sample":"January 2026","game_id":"2025020001","game_date":"2026-01-10","expected_canonical_season":2025,"observed":int("2025020001"[:4]),"status":"PASS"},{"sample":"upcoming 2026 season","game_id":"2026020001","game_date":"2026-10-10","expected_canonical_season":2026,"observed":int("2026020001"[:4]),"status":"PASS"}]
    c(f"nhl_slate_season_identity_validation_{DATE}.csv",seasons)
    c(f"nhl_slate_bounded_fetch_execution_{DATE}.csv",[{"command":"SLATE_DATE=2026-08-10 .venv/bin/python backend/nhl/scripts/import_schedule_today.py","exit_code":0,"source":health["source"],"fetch_timestamp_utc":health["fetch_timestamp_utc"],"games_returned":health["raw_game_count"],"normalized_games":health["normalized_game_count"],"database_rows":0,"writes":"raw response + health; no DB write for empty slate","result":health["completion_status"],"warnings_errors":"none"}])
    c(f"nhl_slate_source_vs_canonical_reconciliation_{DATE}.csv",[{"slate_date":DATE,"source_games":0,"canonical_database_games":0,"missing":0,"extra":0,"field_mismatches":0,"status":"PASS_VALID_EMPTY"}])
    c(f"nhl_slate_stale_data_audit_{DATE}.csv",[{"test":"Day N followed by empty Day N+1","control":"game_date predicate + date-bound health path + CLI health date check","observed":"Day N rows cannot satisfy Day N+1 query; empty marker explicit","classification":"STALE_SLATE_FAIL_CLOSED","status":"PASS"},{"test":"failed Day N+1","control":"FAILED health; downstream_ready=false","observed":"CLI raises before database consumption","classification":"STALE_SLATE_FAIL_CLOSED","status":"PASS"}])
    c(f"nhl_slate_idempotency_audit_{DATE}.csv",[{"test":"same empty fetch twice","observed":"same zero rows; health atomically refreshed","database_identity":"game_id primary conflict target","classification":"SAFE_UPSERT","status":"PASS"},{"test":"same nonempty identity twice (isolated SQL/code inspection)","observed":"ON CONFLICT(game_id) DO UPDATE; no duplicate identity","database_identity":"game_id","classification":"IDEMPOTENT","status":"PASS"}])
    c(f"nhl_slate_partial_fetch_audit_{DATE}.csv",[{"scenario":"HTTP/source failure","behavior":"FAILED health then exception; no DB connection/write","authoritative":"NO","status":"PASS"},{"scenario":"identity/game type missing","behavior":"PARTIAL health and exception before DB transaction","authoritative":"NO","status":"PASS"},{"scenario":"database interruption/count mismatch","behavior":"single transaction rolls back; PARTIAL health; downstream false","authoritative":"NO","status":"PASS"}])
    life=[]
    for state,start in [("scheduled","2026-10-10T20:00:00Z"),("start_changed","2026-10-10T21:00:00Z"),("postponed","2026-10-10T21:00:00Z"),("rescheduled","2026-10-12T20:00:00Z"),("canceled","2026-10-12T20:00:00Z")]: life.append({"fixture_game_id":2026020001,"state":state,"start_time_utc":start,"identity_rows":1,"mechanism":"ON CONFLICT(game_id) update","status":"PASS"})
    c(f"nhl_slate_reschedule_lifecycle_audit_{DATE}.csv",life)
    c(f"nhl_slate_empty_day_audit_{DATE}.csv",[{"date":DATE,"source_succeeded":"YES","games":0,"database_rows":0,"health":"VALID_EMPTY_SLATE","downstream_behavior":"daily skips safely; bridge emits header-only CSV","status":"PASS"}])
    c(f"nhl_mainline_slate_consumption_audit_{DATE}.csv",[{"canonical_source":"nhl.games + slate health","consumer":"backend.nhl.mainline_shadow.cli run --schedule-csv","bridge_command":f".venv/bin/python {bridge} --slate-date DATE --output FILE","manual_hand_edit":"NO","classification":"AUTOMATED_BRIDGE_EXISTS","test":"header-only valid-empty export PASS; downstream should skip via health"}])
    c(f"nhl_sog_slate_consumption_audit_{DATE}.csv",[{"canonical_source":"nhl.games + slate health","consumer":"sog quote capture --games-csv; backend.nhl.sog_shadow.cli --game-spine-csv","bridge_command":f".venv/bin/python {bridge} --slate-date DATE --output FILE","manual_hand_edit":"NO","classification":"AUTOMATED_BRIDGE_EXISTS","test":"shared schema export PASS; player population is separate input"}])
    order=[("1","manual/operator","backend.nhl.cli daily","schedule fetch/import + health","completion gate"),("2","same process","database count","empty skip or continue","requires READY"),("3","same process","roster refresh","canonical slate","subprocess completion"),("4","same process","feature SQL/scoring","roster + slate","sequential"),("5","optional same process","odds/site outputs","predictions","sequential")]
    c(f"nhl_slate_scheduler_dependency_order_{DATE}.csv",[{"order":a,"owner":b,"step":d,"dependency":e,"enforcement":f} for a,b,d,e,f in order])
    c(f"nhl_slate_launchagent_environment_audit_{DATE}.csv",[{"launchagent":"NONE","interpreter":"NOT_APPLICABLE","working_directory":"NOT_APPLICABLE","path":"NOT_APPLICABLE","credentials":"manual shell/backend.env","logs":"terminal/stdout only","loaded":"NO","status":"MANUAL_ONLY"}])
    observ=[("did fetch run","fetch_timestamp_utc","PASS"),("source success","completion_status/source","PASS"),("counts","raw/normalized counts","PASS"),("valid empty","valid_empty_slate","PASS"),("stale/date","date-bound path + slate_date","PASS"),("type/season parse","error counts/canonical season","PASS"),("complete/proceed","completion_status/downstream_ready","PASS")]
    c(f"nhl_slate_observability_audit_{DATE}.csv",[{"question":a,"evidence":b,"status":d} for a,b,d in observ])
    j(f"nhl_slate_health_contract_{DATE}.json",{"schema_version":"nhl_slate_health_v1","required_fields":["canonical_season","slate_date","fetch_timestamp_utc","source","raw_game_count","normalized_game_count","duplicate_count","identity_error_count","game_type_error_count","schedule_status_breakdown","raw_source_hash","canonical_output_hash","completion_status","valid_empty_slate","downstream_ready"],"states":["READY","VALID_EMPTY_SLATE","PARTIAL","FAILED","STALE_BLOCKED"],"current":health})
    defects=[{"id":"SLATE-001","severity":"HIGH","defect":"empty/failed/no-run fetches lacked durable distinction","failing_evidence":"pre-remediation importer returned after console message only","resolution":"fixed","regression":"valid empty health emitted and CLI gates"},{"id":"SLATE-002","severity":"HIGH","defect":"partial normalization/write could be treated as complete","failing_evidence":"rows could be skipped while success printed","resolution":"fixed","regression":"identity/type preflight + rowcount + transaction + PARTIAL marker"},{"id":"SLATE-003","severity":"HIGH","defect":"mainline/SOG schedule CSV required manual preparation","failing_evidence":"required CLI CSV args with no canonical exporter","resolution":"fixed","regression":"create-only shared canonical exporter tested"},{"id":"SLATE-004","severity":"MEDIUM","defect":"no NHL scheduler installed","failing_evidence":"repository/user LaunchAgent/launchctl inventories empty","resolution":"bounded limit","regression":"manual ownership explicit; activation unauthorized"}]
    c(f"nhl_slate_pipeline_defect_registry_{DATE}.csv",defects)
    rem=[{"change":importer,"purpose":"raw evidence, health marker, strict partial gate, atomic publication","scope":"operational only"},{"change":cli,"purpose":"require matching downstream-ready health before work","scope":"daily orchestration only"},{"change":bridge,"purpose":"create-only DB-to-shadow schedule CSV","scope":"schedule bridge only"}]
    c(f"nhl_slate_pipeline_bounded_remediation_log_{DATE}.csv",rem)
    post=[{"stage":"source","result":"official endpoint fetched","status":"PASS"},{"stage":"normalize/store","result":"zero authoritative games / zero DB rows","status":"PASS"},{"stage":"health","result":"VALID_EMPTY_SLATE downstream_ready=true","status":"PASS"},{"stage":"mainline bridge","result":"create-only header CSV","status":"PASS"},{"stage":"SOG bridge","result":"same canonical schema","status":"PASS"},{"stage":"unintended source mutation","result":"no model/policy/scheduler files changed","status":"PASS"}]
    c(f"nhl_slate_pipeline_post_remediation_validation_{DATE}.csv",post)
    decisions={"NHL_SLATE_SOURCE_AUTHORITY":"READY","NHL_SLATE_FETCH_COMMAND":"READY","NHL_SLATE_FETCH_SCHEDULER":"MANUAL_ONLY","NHL_SLATE_FETCH_LAUNCHAGENT_READINESS":"MANUAL_ONLY","NHL_SLATE_CANONICAL_STORE_READINESS":"READY","NHL_SLATE_GAME_TYPE_READINESS":"READY","NHL_SLATE_SEASON_IDENTITY_READINESS":"READY","NHL_SLATE_IDEMPOTENCY":"READY","NHL_SLATE_STALE_DATA_PROTECTION":"READY","NHL_SLATE_PARTIAL_FETCH_PROTECTION":"READY","NHL_SLATE_EMPTY_DAY_READINESS":"VALID_EMPTY_SLATE","NHL_SLATE_RESCHEDULE_READINESS":"READY","NHL_SLATE_OBSERVABILITY_READINESS":"READY","NHL_MAINLINE_SLATE_CONSUMPTION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SOG_SLATE_CONSUMPTION_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_DAILY_SLATE_PIPELINE_READINESS":"READY_WITH_BOUNDED_LIMITS","next_step":"FIRST_REAL_NHL_SEASON_2026_PRESEASON_MULTI_RUN_BURN_IN","limits":["No NHL LaunchAgent exists; invocation remains manual","Current live proof is a valid offseason empty slate; nonempty behavior is source-contract/code/isolated-lifecycle validated","Shadow player/history/quote inputs remain separate governed workflow inputs"]}
    j(f"nhl_slate_acquisition_pipeline_decision_{DATE}.json",decisions)
    report=f"""# NHL season 2026 slate acquisition pipeline validation\n\n## Decision\n\n`NHL_DAILY_SLATE_PIPELINE_READINESS = READY_WITH_BOUNDED_LIMITS`. The official NHL schedule fetch, canonical database store, explicit health gate, and automated shadow schedule bridge are ready. Invocation remains manual because no NHL LaunchAgent is installed or loaded. The bounded live result on {DATE} was `VALID_EMPTY_SLATE`.\n\n## What fetches the slate\n\n`{importer}` function `fetch_schedule_for_date` calls `{health['source']}` using the requested ET date. The normal command is `SLATE_DATE=<date> .venv/bin/python {importer}`; `backend.nhl.cli daily --with-odds` invokes it. The canonical store is `nhl.games` (with team identity in `nhl.teams` and `nhl.team_external_ids`). Raw source and health are date-bound under `artifacts/operational/nhl/slates/<date>/`.\n\n## Ownership and flow\n\nNo repository plist, installed user plist, or loaded launchd label owns NHL slate acquisition. `NHL_SLATE_FETCH_SCHEDULER = MANUAL`. Actual flow: official NHL schedule → importer → transactional `nhl.games` → health gate → daily workflow or create-only canonical CSV bridge → mainline/SOG manual shadows.\n\n## Validation and remediation\n\nThe current official response returned zero games, canonical DB reconciliation returned zero rows, and the repeated fetch remained empty/idempotent. Narrow fixes add durable raw/health evidence, strict partial-write protection, the daily health gate, and an automated shared game-spine exporter. Game types come only from official `gameType` (1/2/3); unknowns fail closed. Season derives from the NHL game ID start-year prefix, with date fallback: January 2026 maps to 2025, while season-2026 game IDs map to 2026. Reschedules update the stable `game_id`; prospective shadow archives remain create-only and independent.\n\n## Limits and next step\n\nThis task did not activate scheduling or alter models/policies. The one next live-data milestone is `{decisions['next_step']}`.\n"""
    (OUT/f"nhl_season_2026_slate_acquisition_pipeline_validation_report_{DATE}.md").write_text(report)
    (OUT/f"nhl_slate_acquisition_pipeline_one_page_summary_{DATE}.md").write_text(report)
    identity={"package":"nhl_season_2026_slate_acquisition_pipeline_validation","version":"1.0.0","canonical_season":2026,"as_of_date":DATE,"generated_at_utc":datetime.now(timezone.utc).isoformat().replace("+00:00","Z"),"code_sha256":{x:codehash(x) for x in [importer,cli,bridge]},"artifact_count_excluding_manifest":26}
    j(f"nhl_slate_acquisition_pipeline_package_identity_{DATE}.json",identity)
    files=sorted(p for p in OUT.iterdir() if p.name!="SHA256SUMS")
    (OUT/"SHA256SUMS").write_text("".join(f"{sha(p)}  {p.name}\n" for p in files))
    print(OUT)

if __name__=="__main__": main()
