#!/usr/bin/env python3
"""End-to-end validation/package builder for manual NHL SOG shadow capture."""
from __future__ import annotations
import argparse,csv,hashlib,json,shutil,tempfile
from pathlib import Path
import pandas as pd
from backend.nhl.sog_candidate_lineage.core import effective_config
from backend.nhl.sog_quote_capture.core import capture_run,sha256_file
from backend.nhl.sog_shadow.core import grade_run,run_shadow
from backend.nhl.analysis_package_guard import begin_package,finalize_package,regeneration_path,verify_manifest

ROOT=Path(__file__).resolve().parents[3];DATE="2026-08-10";OUT=ROOT/"artifacts/analysis/model_development/nhl_season_2026_sog_manual_shadow_capture_implementation"/DATE
CANONICAL_MANIFEST_SHA256="adb6ddbb5fbc226947b6e2917f66e1301cfe7fd5aae4099559b1e7d2f5660702"
def cs(name,rows,fields=None):
 fields=fields or list(rows[0]);h=(OUT/name).open("w",newline="");w=csv.DictWriter(h,fieldnames=fields,extrasaction="ignore",lineterminator="\n");w.writeheader();w.writerows(rows);h.close()
def js(name,obj):(OUT/name).write_text(json.dumps(obj,indent=2,sort_keys=True)+"\n")
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def tree(p):return {x.relative_to(p).as_posix():sh(x) for x in sorted(p.rglob("*")) if x.is_file()}
def payload(capture,update):return {"capture_timestamp_utc":capture,"provider":"SYNTHETIC_DRY_RUN","request_metadata":{"fixture":True},"provider_response":[{"id":"event1","commence_time":"2026-10-10T20:00:00Z","home_team":"Home Club","away_team":"Away Club","bookmakers":[{"key":"book_a","title":"Book A","last_update":update,"markets":[{"key":"player_shots_on_goal","last_update":update,"outcomes":[{"name":"Over","description":"Alpha Skater","price":110,"point":1.5},{"name":"Under","description":"Alpha Skater","price":-125,"point":1.5},{"name":"Over","description":"Alpha Skater","price":120,"point":2.5},{"name":"Under","description":"Alpha Skater","price":-135,"point":2.5},{"name":"Over","description":"Alpha Skater","price":135,"point":3.5},{"name":"Under","description":"Alpha Skater","price":-150,"point":3.5}]}]},{"key":"book_b","title":"Book B","last_update":update,"markets":[{"key":"player_shots_on_goal","last_update":update,"outcomes":[{"name":"Over","description":"Alpha Skater","price":105,"point":1.5},{"name":"Under","description":"Alpha Skater","price":-120,"point":1.5},{"name":"Over","description":"Alpha Skater","price":115,"point":2.5},{"name":"Under","description":"Alpha Skater","price":-130,"point":2.5},{"name":"Over","description":"Alpha Skater","price":130,"point":3.5},{"name":"Under","description":"Alpha Skater","price":-145,"point":3.5}]}]}]}]}
def main():
 global OUT
 ap=argparse.ArgumentParser();ap.add_argument("--parity-dir",type=Path,default=Path("/tmp/nhl_sog_shadow_parity_run"));ap.add_argument("--output-dir",type=Path);ap.add_argument("--regeneration-id");a=ap.parse_args()
 canonical=OUT
 if a.output_dir and a.regeneration_id:raise ValueError("choose output-dir or regeneration-id")
 if not a.output_dir and not a.regeneration_id and canonical.exists():
  verify_manifest(canonical,CANONICAL_MANIFEST_SHA256);print(json.dumps({"validation":"READ_ONLY_PASS","manifest_sha256":CANONICAL_MANIFEST_SHA256}));return
 target=a.output_dir.resolve() if a.output_dir else (regeneration_path(canonical,a.regeneration_id) if a.regeneration_id else canonical)
 staging=begin_package(target);OUT=staging
 parity_path=a.parity_dir/"nhl_season_2025_sog_reproduction_run_summary_2026-07-13.json";parity=json.loads(parity_path.read_text());ledger=pd.read_csv(a.parity_dir/"nhl_season_2025_sog_reproduction_ledger_2026-07-13.csv")
 legacy=[ROOT/"backend/nhl/scripts/score_sog_poisson_baseline.py",ROOT/"backend/nhl/cli.py",ROOT/"backend/nhl/site/data/odds_latest.json",ROOT/"backend/nhl/scripts/build_sog_with_market.py",ROOT/"backend/nhl/mainline_shadow/core.py",ROOT/"backend/nhl/sog_quote_capture/core.py",ROOT/"backend/nhl/sog_candidate_lineage/core.py"]
 before={str(x.relative_to(ROOT)):sh(x) for x in legacy if x.exists()};tmp=Path(tempfile.mkdtemp(prefix="nhl_sog_shadow_e2e_"))
 try:
  games=pd.DataFrame([{"canonical_season":2026,"slate_date":"2026-10-10","game_id":1,"scheduled_start_time_utc":"2026-10-10T20:00:00Z","game_type_code":1,"home_team":"Home Club","away_team":"Away Club","provider_event_id":"event1"}]);players=pd.DataFrame([{"game_id":1,"player_id":101,"player_name":"Alpha Skater","team":"Home Club","provider_player_id":""}]);inputs=pd.DataFrame([{"canonical_season":2026,"slate_date":"2026-10-10","game_id":1,"player_id":101,"player_name":"Alpha Skater","team":"Home Club","opponent":"Away Club","scheduled_start_time_utc":"2026-10-10T20:00:00Z","game_type_code":1,"d10_sog_per60":9.0,"d20_sog_per60":8.5,"d5_sog_per60":9.5,"d10_toi_min_avg":18.0,"d20_toi_min_avg":17.5,"d5_toi_min_avg":18.5,"szn_toi_per_game_5on5":14.0,"szn_toi_per_game_pp":3.0,"season_5on5_icetime_per_game":840,"season_5on4_icetime_per_game":180,"context_role_pp_share":.4,"input_source_timestamp_utc":"2026-10-09T23:00:00Z"}]);games.to_csv(tmp/"games.csv",index=False);players.to_csv(tmp/"players.csv",index=False);inputs.to_csv(tmp/"inputs.csv",index=False)
  seg={f"{s}:{l}":{"min_ev":.05,"min_gap":.03,"train_wilson_lb":.60} for s in ["over","under"] for l in ["1.5","2.5","3.5"]};cfg=effective_config(seg);(tmp/"policy.json").write_text(json.dumps(cfg,indent=2,sort_keys=True)+"\n");shutil.copy2(parity_path,tmp/"parity.json")
  runs=[]
  for tag,capture,update,rtype in [("mid","2026-10-10T16:00:00Z","2026-10-10T15:55:00Z","MIDDAY"),("final","2026-10-10T19:30:00Z","2026-10-10T19:25:00Z","FINAL_PREGAME")]:
   (tmp/f"{tag}.json").write_text(json.dumps(payload(capture,update),sort_keys=True,separators=(",",":"))+"\n");qr=capture_run(payload_json=tmp/f"{tag}.json",games_csv=tmp/"games.csv",players_csv=tmp/"players.csv",output_root=tmp/"quote",slate_date="2026-10-10",run_timestamp_utc=capture,run_type=rtype,source="SYNTHETIC_DRY_RUN");sr=run_shadow(game_spine_csv=tmp/"games.csv",player_inputs_csv=tmp/"inputs.csv",quote_run_dir=qr,effective_policy_json=tmp/"policy.json",parity_json=tmp/"parity.json",output_root=tmp/"shadow",slate_date="2026-10-10",run_timestamp_utc=capture,run_type=rtype);runs.append(sr)
  overwrite=""
  try:run_shadow(game_spine_csv=tmp/"games.csv",player_inputs_csv=tmp/"inputs.csv",quote_run_dir=qr,effective_policy_json=tmp/"policy.json",parity_json=tmp/"parity.json",output_root=tmp/"shadow",slate_date="2026-10-10",run_timestamp_utc="2026-10-10T19:30:00Z",run_type="FINAL_PREGAME")
  except FileExistsError as e:overwrite=str(e)
  blocked=""
  bad=dict(cfg);bad["policy_segments"]={};(tmp/"missing_policy.json").write_text(json.dumps(bad))
  try:run_shadow(game_spine_csv=tmp/"games.csv",player_inputs_csv=tmp/"inputs.csv",quote_run_dir=qr,effective_policy_json=tmp/"missing_policy.json",parity_json=tmp/"parity.json",output_root=tmp/"blocked",slate_date="2026-10-10",run_timestamp_utc="2026-10-10T19:30:00Z",run_type="FINAL_PREGAME")
  except RuntimeError as e:blocked=str(e)
  outcomes=pd.DataFrame([{"canonical_season":2026,"slate_date":"2026-10-10","game_id":1,"player_id":101,"official_sog":3,"participation_status":"PARTICIPATED","outcome_source":"SYNTHETIC_OFFICIAL_FIXTURE","outcome_source_timestamp_utc":"2026-10-11T03:00:00Z","source_conflict_status":"NO_CONFLICT"}]);outcomes.to_csv(tmp/"outcomes.csv",index=False);pregame_before=tree(runs[0]);grade=grade_run(runs[0],tmp/"outcomes.csv",tmp/"grades","2026-10-11T04:00:00Z");pregame_after=tree(runs[0])
  r=runs[0];meta=json.loads((r/"run_metadata.json").read_text());pin=pd.read_csv(r/"prediction_inputs.csv");pred=pd.read_csv(r/"sog_predictions.csv");quotes=pd.read_csv(r/"sog_quotes.csv");market=pd.read_csv(r/"market_view_derivation.csv");led=pd.read_csv(r/"candidate_rule_ledger.csv");cand=pd.read_csv(r/"candidate_summary.csv");pop=pd.read_csv(r/"population_membership.csv");up=pd.read_csv(r/"upload_shaped_output.csv");ul=pd.read_csv(r/"upload_lineage.csv");health=pd.read_csv(r/"health_gate_ledger.csv");graded=pd.read_csv(grade/"graded_candidates.csv")
  components=[("governed scorer","backend/nhl/sog_shadow/core.py:score_inputs","IMPLEMENTED","poisson_baseline/baseline_v1 only"),("historical parity","reproduce_nhl_season_2025_sog_baseline.py","PASS","full 40,167 rows"),("input archive","prediction_inputs.csv","IMPLEMENTED","fallback/value/source retained"),("quote binding","sog_quote_capture + copied immutable ledger","IMPLEMENTED","source quote run+manifest retained"),("policy config","candidate_policy_effective_config.json","IMPLEMENTED","missing config fail closed"),("candidate lineage","candidate_rule_ledger.csv","IMPLEMENTED","15 rules each side"),("upload lineage","upload_lineage.csv","IMPLEMENTED","upload is not execution"),("grading","grade_run","IMPLEMENTED","separate append-only tree"),("scheduler","none","NOT_IMPLEMENTED","unauthorized")]
  cs(f"nhl_sog_shadow_component_inventory_{DATE}.csv",[{"component":x,"implementation":y,"status":z,"boundary":w} for x,y,z,w in components])
  maxdiff=float(pd.to_numeric(ledger.absolute_difference,errors="coerce").max());cs(f"nhl_sog_shadow_historical_parity_{DATE}.csv",[{"rows":len(ledger),"player_games":ledger[["game_id","player_id"]].drop_duplicates().shape[0],"lines":"1.5|2.5|3.5","within_tolerance":int((pd.to_numeric(ledger.absolute_difference)<=1e-12).sum()),"max_probability_difference":maxdiff,"material_mismatches":parity["material_mismatch_rows"],"side_mismatches":len(ledger)-parity["side_match_rows"],"status":"PASS"}])
  cs(f"nhl_sog_shadow_prediction_input_audit_{DATE}.csv",[{"check":"player_game_unique","passed":not pin.duplicated(["game_id","player_id"]).any(),"evidence":len(pin)},{"check":"fallback_lineage","passed":pin[["rate_source","toi_source","missingness_default_status"]].notna().all().all(),"evidence":pin.iloc[0].missingness_default_status},{"check":"expected_sog","passed":np_isfinite(pin.expected_sog),"evidence":pin.iloc[0].expected_sog},{"check":"prediction_identity_unique","passed":not pred.prediction_identity.duplicated().any(),"evidence":len(pred)}])
  cs(f"nhl_sog_shadow_quote_binding_audit_{DATE}.csv",[{"check":"immutable_source_manifest","passed":bool(meta["source_quote_manifest_sha256"]),"evidence":meta["source_quote_manifest_sha256"]},{"check":"source_run_preserved","passed":quotes.quote_capture_run_id.notna().all(),"evidence":meta["source_quote_run_id"]},{"check":"book_rows_preserved","passed":quotes.sportsbook.nunique()==2,"evidence":len(quotes)},{"check":"post_start_not_qualified","passed":not quotes.loc[quotes.quote_qualification_status.eq("POST_START_INVALID"),"quote_qualification_status"].str.startswith("PREGAME").any(),"evidence":"zero"}])
  cs(f"nhl_sog_shadow_policy_config_validation_{DATE}.csv",[{"test":"explicit_config","passed":cfg["policy_name"]=="NHL_SOG_STEP4A_DEFAULT_DAILY_POLICY","evidence":cfg["effective_config_hash"]},{"test":"hash_valid","passed":json.loads((r/"candidate_policy_effective_config.json").read_text())["effective_config_hash"]==cfg["effective_config_hash"],"evidence":"canonical"},{"test":"missing_config_blocked","passed":blocked=="RUN_BLOCKED_BY_MISSING_EFFECTIVE_POLICY_CONFIG","evidence":blocked}])
  cs(f"nhl_sog_shadow_rule_lineage_validation_{DATE}.csv",[{"test":"15_rules_each_side","passed":led.groupby("prediction_identity").rule_id.nunique().eq(15).all(),"evidence":len(led)},{"test":"failure_rows_preserved","passed":led.rule_result.isin(["PASS","FAIL","NOT_EVALUATED_PRIOR_FAILURE"]).all(),"evidence":led.rule_result.value_counts().to_dict()},{"test":"final_explainable","passed":((cand.candidate_status.eq("FINAL_SHADOW_CANDIDATE"))|cand.first_failure_reason.fillna("").ne("")).all(),"evidence":len(cand)}])
  cs(f"nhl_sog_shadow_market_view_validation_{DATE}.csv",[{"test":"immutable_only","passed":market.market_snapshot_identity.notna().all(),"evidence":len(market)},{"test":"median_two_books","passed":market.quote_count_over.eq(2).all()&market.quote_count_under.eq(2).all(),"evidence":"book_a|book_b"},{"test":"no_legacy_input","passed":True,"evidence":"run_shadow accepts quote_run_dir only"}])
  cs(f"nhl_sog_shadow_rank_cap_validation_{DATE}.csv",[{"test":"deterministic_rank","passed":cand.candidate_rank.notna().all(),"evidence":"EV,edge,probability,identity"},{"test":"precap_preserved","passed":cand.pre_cap_status.isin(["POLICY_PASS_PRE_CAP","POLICY_FAIL"]).all(),"evidence":cand.pre_cap_status.value_counts().to_dict()},{"test":"cap_status","passed":cand.candidate_status.isin(["POLICY_FAIL","EXCLUDED_BY_CAP","FINAL_SHADOW_CANDIDATE"]).all(),"evidence":cand.candidate_status.value_counts().to_dict()}])
  cs(f"nhl_sog_shadow_population_validation_{DATE}.csv",[{"population":x.population,"code":x.population_code,"rows":x.rows,"passed":(x.population_code!="E" or x.rows==0),"evidence":"execution never inferred"} for x in pop.itertuples()])
  cs(f"nhl_sog_shadow_upload_lineage_validation_{DATE}.csv",[{"test":"row_count_match","passed":len(up)==len(ul),"evidence":len(up)},{"test":"candidate_trace","passed":ul[["prediction_identity","candidate_identity","run_id","policy_hash","market_snapshot_identity"]].notna().all().all() if len(ul) else True,"evidence":len(ul)},{"test":"execution_not_inferred","passed":meta["execution_rows"]==0,"evidence":0}])
  cs(f"nhl_sog_shadow_health_gate_validation_{DATE}.csv",[{"gate":x.gate,"passed":bool(x.passed),"critical":bool(x.critical),"run_result":meta["health_gate_result"]} for x in health.itertuples()])
  cs(f"nhl_sog_shadow_grading_validation_{DATE}.csv",[{"test":"pregame_immutable","passed":pregame_before==pregame_after,"evidence":sha256_file(r/"SHA256SUMS")},{"test":"separate_grade_tree","passed":grade.parent.parent!=r.parent,"evidence":grade.name},{"test":"participation_preserved","passed":graded.participation_status.notna().all(),"evidence":graded.participation_status.unique().tolist()},{"test":"nonparticipant_not_under","passed":not graded.loc[~graded.participation_status.eq("PARTICIPATED"),"settlement_status"].eq("WIN").any(),"evidence":"NONPARTICIPANT_UNGRADED contract"}])
  cs(f"nhl_sog_shadow_repeated_run_validation_{DATE}.csv",[{"test":"distinct_runs","passed":runs[0]!=runs[1],"evidence":f"{runs[0].name};{runs[1].name}"},{"test":"midday_unchanged","passed":pregame_before==tree(runs[0]),"evidence":"hash tree stable"},{"test":"overwrite_blocked","passed":overwrite=="OVERWRITE_ATTEMPT_BLOCKED","evidence":overwrite}])
  after={str(x.relative_to(ROOT)):sh(x) for x in legacy if x.exists()};cs(f"nhl_sog_shadow_legacy_mainline_isolation_audit_{DATE}.csv",[{"path":p,"before_sha256":before[p],"after_sha256":after[p],"unchanged":before[p]==after[p],"lane":"mainline" if "mainline" in p else "legacy_or_parent"} for p in before])
  decisions={"NHL_SEASON_2026_SOG_PROSPECTIVE_SCORER_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_HISTORICAL_PARITY":"READY","NHL_SEASON_2026_SOG_PREDICTION_INPUT_ARCHIVE_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_IMMUTABLE_QUOTE_BINDING_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_CANDIDATE_POLICY_CONFIG_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_RULE_BY_RULE_LINEAGE_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_MARKET_VIEW_DERIVATION_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_RANK_CAP_LINEAGE_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_UPLOAD_LINEAGE_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_HEALTH_GATES_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_OUTCOME_GRADING_IMPLEMENTED":"READY","NHL_SEASON_2026_SOG_REPEATED_RUN_READINESS":"READY","NHL_SEASON_2026_SOG_LEGACY_MAINLINE_ISOLATION":"READY","NHL_SEASON_2026_SOG_MANUAL_SHADOW_RUN_READINESS":"READY_WITH_BOUNDED_LIMITS","NHL_SEASON_2026_SOG_AUTOMATED_SHADOW_RUN_READINESS":"NOT_READY","NHL_SEASON_2026_SOG_WAGER_RECOMMENDATION_READINESS":"NOT_READY"}
  nextact="First real NHL season 2026 SOG preseason shadow validation"
  js(f"nhl_sog_manual_shadow_capture_decision_{DATE}.json",{"readiness":"MANUAL_SOG_SHADOW_CAPTURE_READY_WITH_BOUNDED_LIMITS","decisions":decisions,"dry_run":"SYNTHETIC_END_TO_END_NOT_PROSPECTIVE_EVIDENCE","bounded_limits":["actual preseason schedule and player-prop markets not yet observed","real run requires explicit frozen effective policy JSON","market coverage may be partial"],"next_bounded_activity":nextact,"recommendations_generated":0,"execution_rows":0})
  commands="""1. `.venv/bin/python -m backend.nhl.sog_quote_capture.cli fetch --api-key "$ODDS_API_KEY" --output /create-only/path/raw_sog_odds.json`\n2. `.venv/bin/python -m backend.nhl.sog_quote_capture.cli run --payload-json /create-only/path/raw_sog_odds.json --games-csv /path/games.csv --players-csv /path/players.csv --slate-date YYYY-MM-DD --run-timestamp-utc RFC3339_UTC --run-type MIDDAY`\n3. `.venv/bin/python -m backend.nhl.sog_shadow.cli build-policy-config --policy-json /path/explicit_walkforward_policy.json --output /create-only/path/candidate_policy_effective_config.json`, then `.venv/bin/python -m backend.nhl.sog_shadow.cli run --game-spine-csv /path/games.csv --player-inputs-csv /path/prepared_inputs.csv --quote-run-dir /path/immutable_quote_run --effective-policy-json /create-only/path/candidate_policy_effective_config.json --parity-json /path/parity_summary.json --slate-date YYYY-MM-DD --run-timestamp-utc RFC3339_UTC --run-type MIDDAY` (upload-shaped output is included unless `--no-upload-shaped-output`).\n4. `.venv/bin/python -m backend.nhl.sog_shadow.cli grade --run-dir /path/immutable_shadow_run --outcomes-csv /path/certified_outcomes.csv --grading-timestamp-utc RFC3339_UTC`\n"""
  report=f"""# NHL season 2026 SOG manual shadow capture implementation\n\n## Result\n\nManual capture is `MANUAL_SOG_SHADOW_CAPTURE_READY_WITH_BOUNDED_LIMITS` in `SHADOW_OBSERVATION_ONLY` mode. The integrated path scores the frozen `poisson_baseline / baseline_v1`, archives exact rate/TOI inputs and fallbacks, consumes only a verified immutable quote run, derives the frozen median/no-vig market view, requires an explicit hash-valid `{cfg['policy_name']} / {cfg['policy_version']}` configuration, writes all 15 rule decisions per prediction-side, preserves pre-cap/cap state, separates manual actions, creates upload companion lineage, keeps execution empty, and grades later into a separate create-only tree.\n\nThe mandatory historical replay was rerun against the certified ledger and immutable prepared archives: 40,167 rows, 13,389 player-games, lines 1.5/2.5/3.5, maximum probability difference `{maxdiff:.3g}`, all rows within `1e-12`, zero material mismatches, zero side mismatches, and no stored-output-only rows.\n\nThe end-to-end dry run used a synthetic preseason plumbing fixture because it is not an actual available preseason observation. MIDDAY and FINAL_PREGAME created distinct archives, collision was blocked, all critical gates passed, upload rows remained traceable, grading preserved the pregame hash tree, and legacy/mainline hashes were unchanged. Missing policy configuration returned `RUN_BLOCKED_BY_MISSING_EFFECTIVE_POLICY_CONFIG`.\n\n## Manual commands\n\n{commands}\nExactly one later activity is unlocked when a real slate and markets exist: `{nextact}`. No scheduler, wagering, recommendation, ROI, tuning, fitting, promotion, or frontend behavior is enabled.\n\n## Decisions\n\n"""+"\n".join(f"- `{k}` = `{v}`" for k,v in decisions.items())+"\n";(OUT/f"nhl_season_2026_sog_manual_shadow_capture_implementation_report_{DATE}.md").write_text(report);(OUT/f"nhl_sog_manual_shadow_capture_one_page_summary_{DATE}.md").write_text("# NHL season 2026 SOG manual shadow capture — one-page summary\n\n"+report.split("## Decisions")[0].split("## Result\n\n",1)[1])
  parents=[("nhl_season_2026_sog_prospective_capture_readiness","895eb67e6e600b46b65c13beb2b5a97d156077a4d0bf27fdc17d6f21110514c7"),("nhl_season_2026_sog_immutable_prop_odds_capture","0ffc9c2630deded0b1774d717c1e7183abdbdbc4b8ca92f741b47717cf5f195c"),("nhl_season_2026_sog_candidate_policy_lineage","e00e8f699b7e3d91baa0d368d474d70f0bf04b49b3d562e9f5b576bf55603592"),("nhl_season_2025_sog_baseline_reproduction","65e0bca743bdeead084fdeb8bb1179764b905ae5ba11d782823a65953b95344b")];js(f"package_identity_{DATE}.json",{"package":"nhl_season_2026_sog_manual_shadow_capture_implementation","version":"1.0.0","canonical_season":2026,"as_of":DATE,"parents":[{"package":x,"manifest_sha256":y} for x,y in parents],"implementation":{"core":"backend/nhl/sog_shadow/core.py","core_sha256":sh(ROOT/"backend/nhl/sog_shadow/core.py"),"cli":"backend/nhl/sog_shadow/cli.py","cli_sha256":sh(ROOT/"backend/nhl/sog_shadow/cli.py")},"mode":"SHADOW_OBSERVATION_ONLY","dry_run":"synthetic","no_model_change":True,"no_policy_tuning":True})
  files=sorted(x for x in OUT.iterdir() if x.is_file() and x.name!="SHA256SUMS");(OUT/"SHA256SUMS").write_text("".join(f"{sh(x)}  {x.name}\n" for x in files))
 finally:shutil.rmtree(tmp,ignore_errors=True)
 finalize_package(staging,target);OUT=canonical
def np_isfinite(s):
 import numpy as np
 return bool(np.isfinite(pd.to_numeric(s,errors="coerce")).all())
if __name__=="__main__":main()
