-- Applied successfully on 2026-07-28.
-- Canonical idempotent migration:
-- backend/mlb/sql/migrations/20260728_create_mlb_cleanroom_v1.sql
-- This evidence pointer avoids maintaining a divergent duplicate migration.
