name: Backfill Predictions

on:
  schedule:
    - cron: "0 8 * * *" # ⏰ every day at 8am UTC
  workflow_dispatch: # 🔘 allows manual run in GitHub UI

jobs:
  backfill:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Python Setup & Script
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backfill_predictions.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python backend/scripts/shared/backfill_predictions.py
