name: Trigger & Fetch NHL Exports

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 10 * * *" # 03:15 PT daily

concurrency:
  group: nhl-exports
  cancel-in-progress: false

jobs:
  export-and-download:
    runs-on: ubuntu-latest
    steps:
      - name: Set DATE (UTC)
        run: echo "DATE=$(date -u +%F)" >> $GITHUB_ENV

      - name: Trigger export on Render
        run: |
          curl -fsS -X POST \
            "https://baseball-streaks-sq44.onrender.com/admin/refresh-export?token=${{ secrets.EXPORT_TOKEN }}" \
            -o response.json
          cat response.json

      - name: Download SOG CSV
        run: |
          curl -fSL \
            "https://baseball-streaks-sq44.onrender.com/admin/download-export?token=${{ secrets.EXPORT_TOKEN }}&which=sog&date_str=${DATE}" \
            -o train_nhl_sog_v2.csv
          ls -lh train_nhl_sog_v2.csv

      - name: Download Goalie CSV
        run: |
          curl -fSL \
            "https://baseball-streaks-sq44.onrender.com/admin/download-export?token=${{ secrets.EXPORT_TOKEN }}&which=goalie&date_str=${DATE}" \
            -o train_goalie_saves_v2.csv
          ls -lh train_goalie_saves_v2.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nhl-exports-${{ env.DATE }}
          path: |
            train_nhl_sog_v2.csv
            train_goalie_saves_v2.csv
          if-no-files-found: error
          retention-days: 14
