name: Precompute MLB Props

on:
  schedule:
    - cron: "10 10-23 * * *" # hourly :10 (10:00–23:00 UTC)
  workflow_dispatch: {}

jobs:
  precompute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Debug env presence (non-secret)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: >
          python -c "import os;
          print('SUPABASE_URL set? ', bool(os.getenv('SUPABASE_URL')));
          print('Key present?       ', bool(os.getenv('SUPABASE_SERVICE_ROLE_KEY')))"

      - name: Precompute today (ET)
        env:
          PYTHONPATH: backend
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          FEATURE_SET_TAG: v1
        run: python -m scripts.precompute.precompute_props_daily

      - name: Verify rows were written for today (ET)
        env:
          PYTHONPATH: backend
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          FEATURE_SET_TAG: v1
        run: >
          python -c "import os, sys, datetime;
          from zoneinfo import ZoneInfo;
          from scripts.shared.supabase_utils import get_supabase;
          DATE=str(datetime.datetime.now(ZoneInfo('America/New_York')).date());
          TAG=os.getenv('FEATURE_SET_TAG','v1');
          res=(get_supabase().from_('prop_features_precomputed')
              .select('prop_type', count='exact')
              .eq('game_date', DATE).eq('feature_set_tag', TAG).execute());
          total=res.count or 0; print(f'[verify] game_date={DATE} tag={TAG} rows={total}');
          sys.exit(0 if total>0 else 1)"
